### ISSUE TITLE
Add note for Task 4, module 7 - wait time for RBAC access

### ISSUE THREAD

**Issue by markturpinMSFT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#100]
# Module: 07
#### Step: 14

Description of issue
Please add a note that it will take 3-5 minutes for Azure AD role assignment to take effect and allow you to switch Authentication Method to Azure AD User Account without an RBAC error.  Example of error:

![image](https://user-images.githubusercontent.com/55555818/86038100-3d03b280-b9f5-11ea-9763-b57b588545d1.png)

**Comment by polichtm** [comment]
updated
