### ISSUE TITLE
JSON will not upload (Lab 02a, Task 2)

### ISSUE THREAD

**Issue by dnguyen92x** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#105]
# Module: 00
#### Step: 00

Unable to upload the az104-02a-customroledefinition.json file. 

Repro steps:

1. DOwnload az104-02a-customroledefinition.json (after replacing proper subscription ID)
1. Upload file
1. Can't upload, says it failed in white prompt box

**Comment by staleycyn** [comment]
This repository is for distributing lab files to Microsoft Certified Trainers who are teaching the AZ-104 Azure Administrator course. Are you are in class? If so, please ask your instructor for assistance. We are not staffed to provide general help desk support. Thank you.

**Comment by polichtm** [comment]
pls make sure that the role definition follows the format described in https://docs.microsoft.com/en-us/azure/role-based-access-control/custom-roles
rgds
Marcin
