### ISSUE TITLE
Module 11,  Exercise 1, Task 7  Perf table does not store any data, use InsightMetrics instead

### ISSUE THREAD

**Issue by LionelShaul** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#106]
# Module: 11
#### Step: 03

Description of issue

Available Memory is collected in the InsightMetrics table.  Running the example queries for Available Memory will not work because that query uses the Perf table.  In the example query for Available Memory replace Perf with InsightMetrics as shown below.

Repro steps:

original query:

// Virtual Machine available memory 
// Chart the VM's available memory over the last hour. 
Perf
| where TimeGenerated > ago(1h)
| where ObjectName == "Memory" and
(CounterName == "Available MBytes Memory" or // the name used in Linux records
CounterName == "Available MBytes") // the name used in Windows records
| project TimeGenerated, CounterName, CounterValue
| render timechart

updated query:

// Virtual Machine available memory 
// Chart the VM's available memory over the last hour. 
InsightsMetrics
| where TimeGenerated > ago(1h)
| where Name == "AvailableMB"
| project TimeGenerated, Name, Val
| render timechart

**Comment by polichtm** [comment]
updated
rgds
Marcin
