### ISSUE TITLE
Lab 6 Task 1 - Does not configure everything through powershell

### ISSUE THREAD

**Issue by ahmed-babic** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#107]
# Module: https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/tree/master/Instructions/Labs
#### Step: 00

Description of issue
After creating resource groups, I can't see any deployments in Resource group 2 and 3. There are only deployments for resource group 1 in this case. I guess there might be issue within az104-06-vm-template.json.
When I skip to Task 2 for peering, can't find ' az104-06-vnet2 (az104-06-rg2)' or any other.
Repro steps:

Follow all the steps described in the lab.

**Comment by polichtm** [comment]
Unfortunately I cannot reproduce the issue you are referring to. Pls reach out to your instructor regarding this.
rgds
Marcin
