### ISSUE TITLE
Lab 06 Fails when using trial accounts.

### ISSUE THREAD

**Issue by djwagler** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#112]
# Module: 00
#### Step: 00

Description of issue

Note that Lab06 will fail if someone uses a Trial account.  This is because it uses the default type of Standard_D2s_v3 which uses 2 virtual cpus each.  Since trial accounts have a limit of 4 virtual cpus you are unable to deploy the four machines of type Standard_D2s_v3 which uses 8 Virtual cpus.   I would recommend changing the default type to use only one Virtual CPU (such as Standard_B1s).   I have tested the lab using Standard_B1s and it worked well.

Repro steps:

1. Run the commands to create the 2 vms.   This command will succeed on a Trial account
1. Run the command to create 1 more vm.  This command will fail on a Trial account because you have already used 4 Virtual cpus.

I would love to have access so that I could submit fixes myself but hopefully someone will do the fix.   THere simple fix is to change the az104-06-vm-parameters.json file and change the vmSize to Standard_B1s.   The side benifit is this is free for anyone using a trial account.

**Comment by polichtm** [comment]
One of the reasons that the VM size is available as a template parameter is to accommodate scenarios like the one you are describing. While setting a particular default might resolve one type of issue, it could lead to another (a few months back B series VMs were simply not available - in addition, lower size VMs are bound to have inferior performance and increase deployment time). My suggestion would be to ensure that, as an MCT, you identify the type of subscriptions that your students are using and provide the optimal value of the VM size. 
Would adding a note providing this information as part of instructions work for you?
rgds
Marcin

**Comment by djwagler** [comment]
Hello Marcin,

Yes I think a note indicating to use a VM that only uses one Virtual cpu such as a Standard_B1s or a Standard_DS1_v2 would help particularly if other students are using Trail Accounts which have a limit of 4 virtual cpus (unless you send in a request for a limit increase).

Thanks

**Comment by polichtm** [comment]
updated
rgds
Marcin
