### ISSUE TITLE
Lab file name contains space in it

### ISSUE THREAD

**Issue by Manesh-R** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#116]
# Module: 03
## Lab/Demo: A

Description of issue

All lab files are following standard naming for file, which do not include space except for https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/blob/master/Instructions/Labs/LAB_03a-Manage_Azure_Resources_by_Using%20the%20Azure%20Portal.md. Can this be fixed?

**Comment by polichtm** [comment]
Hi Manesh,
is there a particular reason you are considering this to be an issue?
rgds
Marcin

**Comment by polichtm** [comment]
updated
