### ISSUE TITLE
Lab 09c

### ISSUE THREAD

**Issue by djwagler** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#118]
# Module: 00
#### Step: 07

Description of issue

I was unable to deploy the kubernetes clusters.  I found out the issue was that I needed to go to Resource Providers and register Microsoft.Kubernetes and Micrsofot.KubernetesConfiguration.  After registering those two providers I was able to create the kubernetes Cluster.  I would recommend you add a note at the start of Task 1 that tells students to maker sure Microsoft.Kubernetes and Micrsofot.KubernetesConfiguration are registestered with the subscription.  I was using a Trial account when this happened.

Repro steps:

1. Register for a Azure Trial account
1.  Follow Lab/Demo: 09c: Excercise 1 steps 1-7 
1.  The deployment will fail with an error indication Deployment failed.  Deployment to resource group 'az104-09c-rg1' failed.

**Comment by polichtm** [comment]
updated
