### ISSUE TITLE
Duplicate string (Lab 06, Task 4)

### ISSUE THREAD

**Issue by santiagoroman** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#122]
# Module: 00
#### Step: 4

Today while doing the lab 6 I found that step 4 of task 4 had duplicate string. Currently its content is:

```
Click the az104-06-nic0 link next to the Network interface label, and then, on the az104-06-nic0 network interface blade, in the Settings section, in the Settings section, click IP configurations.
```

And after removing the duplicate `in the Settings section` part it would end up like this:

```
Click the az104-06-nic0 link next to the Network interface label, and then, on the az104-06-nic0 network interface blade, in the Settings section, click IP configurations.
```

Thank you very much.

Repro steps:

1. Go to https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/blob/master/Instructions/Labs/LAB_06-Implement_Network_Traffic_Management.md
2. Look for step 4 of task 4

**Comment by polichtm** [comment]
updated
rgds
Marcin
