### ISSUE TITLE
Correction for Module 8

### ISSUE THREAD

**Issue by PaulFou** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#124]
# Module: 08
#### Step: 13

Description of issue
In step 13 it now supplies a setting for Public ip Address Name, in the build that you do in the portal to get the custom deployment you select Public ip none, this item is not needed in the custom settings and is causing confusion for some dlelegates.

Repro steps:

1.Remove Public ip Address Name from custom deployment section
1.
1.

**Comment by polichtm** [comment]
updated
rgds
Marcin
