### ISSUE TITLE
Custom deploy from template does not give you option to change settings.

### ISSUE THREAD

**Issue by pcon0718** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#125]
# Module: AZ-104-MicrosoftAzureAdministrator
#### Step: 11

Description of issue
Custom deploy from template does not give you option to change settings.

Repro steps:

1. Create VM as mentioned in steps 1-10
2. On the deployment blade, click Template
3. Review Template and click deploy.
![image](https://user-images.githubusercontent.com/6722808/88438855-7940ed80-cdbe-11ea-96e5-e2ae6b48ef84.png)

4. Custom Deployment screen does not allow you to specify any settings. 
![image](https://user-images.githubusercontent.com/6722808/88438902-91b10800-cdbe-11ea-9720-5d0168b912af.png)

**Comment by polichtm** [comment]
Hi Philippe,
here is what I'm seeing when following steps provided in the lab instructions:
![image](https://user-images.githubusercontent.com/10284906/88933827-e258b300-d24d-11ea-9089-ecdedca349c0.png)
Pls refer to your lab instructor if you are still running into an issue
rgds
Marcin
