### ISSUE TITLE
Resource group mentioned in lab does not exist.

### ISSUE THREAD

**Issue by pcon0718** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#126]
# Module: AZ-104-MicrosoftAzureAdministrator
#### Step: 3

Description of issue
Resource group 'az104-03a-rg1' mentioned in lab does not exist. 

Repro steps:

1.Login into Azure Portal
2. Click on Resource groups.
3. az104-03a-rg1 is not there.

Recommend just getting rid of steps 3-6 and have the user download templates directly via GitHub as stated on the Notes of step 7.

**Comment by polichtm** [comment]
Hi Philippe,
that resource group is created in the lab 3a. Pls make sure to complete that lab first.
rgds
Marcin
