### ISSUE TITLE
Policy Name Change

### ISSUE THREAD

**Issue by markturpinMSFT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#13]
# Module: 02b
#### Step: 3,4 and Task 2 Description

Description of issue
"Require tag and its value" is potentially two different policy definitions

This should be replaced with "Require a tag and its value on resources" in all 3 places in Task 2 instructions.

If a user selected "Require a tag and its value on resource groups" the exercise will not work.

**Comment by polichtm** [comment]
updated
