### ISSUE TITLE
Issues in module  08 - Manage Virtual Machines

### ISSUE THREAD

**Issue by srushti-714** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#131]
# Module: 08
#### Step: 08

Description of issue
Scale condition is not triggered with the following configurations:
Time aggregation and Time grain statistic is not working (3rd instance is not initiated) if it is set to "Maximum" , it is working fine with "Average" option

# Module: 08
#### Step: 13
Add $pip to print/get the public ip address.

**Comment by mpolicht** [comment]
Could you clarify why you want to display the value of the $pip variable?
rgds
Marcin

**Comment by srushti-714** [comment]
@mpolicht From the instruction:  **run the following to identify the public IP address** of the load balancer in front of the Azure virtual machine scale set az10408vmss0.

$pip = (Get-AzPublicIpAddress -ResourceGroupName $rgName -Name $lbpipName).IpAddress
Above command does not display $pip according to instruction .
so we can add one more line $pip to get the public ip

**Comment by polichtm** [comment]
Unfortunately it's still not clear to me why you would need to display the IP address. 
As per instructions, this IP address is being used to run
while ($true) { Invoke-WebRequest -Uri "http://$pip" }
In other words, there is no need to display it. 
Pls let me know if this requires any additional clarification
rgds
Marcin
