### ISSUE TITLE
Task 4 not in index, Task 4, 5, and6 should now be renumbered Task 5, 6 and 7.

### ISSUE THREAD

**Issue by DailyTech** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#132]
# Module: az104
#### Step: 00

Description of issue
Task 4 not in index, Task 4, 5, and6 should now be renumbered Task 5, 6 and 7.
Repro steps:
1. go to https://microsoftlearning.github.io/AZ-104-MicrosoftAzureAdministrator/Instructions/Labs/LAB_08-Manage_Virtual_Machines.html
2. the Index is incorrect, need renumbering, and addition of "Task 4: Register the Microsoft.Insights and Microsoft.AlertsManagement resource providers."

**Comment by polichtm** [comment]
updated
