### ISSUE TITLE
New tab in Storage account creation

### ISSUE THREAD

**Issue by davidpbedford** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#135]
# Module: Module 07 - Azure Storage
#### Step: 3
This step is now wrong, as a new tab (Data Protection) has been added when creating a storage account.

3. Click Next: Networking >, on the Networking tab of the Create storage account blade, review the available options, accept the default option Public endpoint (all networks} and click Next: Advanced >.

Step 3 should be amended to read and click next: Data Protection.

New step 4 required to be inserted  to read  "and click next to : Advanced"

**Comment by polichtm** [comment]
updated
