### ISSUE TITLE
Module 8 Images Renamed

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#138]
# Module: 08
#### Step: 00

Not a big issue, but I see Azure now lists the available public images with "gen 1" in the name.  
Presumably the students will ignore the  added text to still pick a the right Windows Server image.

![VM Gen 1 Images](https://user-images.githubusercontent.com/16696370/90169248-5629ae00-dd6c-11ea-8d66-183520ee44d9.PNG)

Cheers,
Jeff Smalley MCT
Chicagoville

**Comment by polichtm** [comment]
updated
