### ISSUE TITLE
Add Note about Azure Policy Enablement

### ISSUE THREAD

**Issue by markturpinMSFT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#14]
# Module: 02
#### Step: 09

Description of issue

Hi @polichtm 

Azure Policy takes some time before it will enforce your policy assignment.  Please add a note that it will take anywhere from 5 to 15 minutes to take effect before it will enforce the tagging policy (in both tasks)

**Comment by polichtm** [comment]
updated

**Comment by markturpinMSFT** [comment]
Typo on the note - might - in both notes

**Comment by polichtm** [comment]
This hasn't been my experience (maybe just being lucky) - so my suggestion would be stick to "might" vs "will"
rgds
Marcin

**Comment by markturpinMSFT** [comment]
Sorry Marcin, I wasn't clear - currently it's written as "migth"

"Note: It **migth** take between 5 and 15 minutes for the policy to take effect."

**Comment by polichtm** [comment]
updated ;)
