### ISSUE TITLE
New work

### ISSUE THREAD

**Issue by ajayrajpp** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#140]
{
   "Name": "Support Request Contributor (Custom)",
   "IsCustom": true,
   "Description": "Allows to create support requests",
   "Actions": [
       "Microsoft.Resources/subscriptions/resourceGroups/read",
       "Microsoft.Support/*"
   ],
   "NotActions": [
   ],
   "AssignableScopes": [
       "/providers/Microsoft.Management/managementGroups/az104-02-mg1",
       "/subscriptions/SUBSCRIPTION_ID"
   ]
}

**Comment by polichtm** [comment]
pls advise what's the intention here...
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
