### ISSUE TITLE
No Traffic Manager in Skillpipe

### ISSUE THREAD

**Issue by chris-utter** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#143]
# Module: 06
#### Step: 00

Skillpipe courseware does not mention Azure Traffic Manager.
As the primary study tool for students, Skillpipe should match \reflect the content delivered as part of the course.

**Comment by staleycyn** [comment]
Chris can you clarify what needs to be changed here? The course was updated 7 August and Traffic Manager was removed from Skillpipe and the PPT decks. That was explained in the Change Log. This was done to help shorten the course by removing content that is not on the exam.

**Comment by chris-utter** [comment]
Thanks for the update, I was not aware of the content change. I will download the latest deck.
