### ISSUE TITLE
az104-08-custom_script_extension.json

### ISSUE THREAD

**Issue by MarcelMerk** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#145]
# Module: 08 
#### Step: 00

File az104-08-custom_script_extension.json

Contains a , at the end which causes an issue.

**Comment by polichtm** [comment]
Hi Marcel,
what specifically is the issue you are referring to?
rgds
Marcin

**Comment by MarcelMerk** [comment]
There is a comma in the end of the script which I believe is incorrect

**Comment by polichtm** [comment]
Hi Marcel,
what specifically is the issue you are running into?
Pls provide step by step instructions how to reproduce that issue
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
