### ISSUE TITLE
Boot Diagnostic UI has changed

### ISSUE THREAD

**Issue by chris-utter** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#146]
# Module: 08
#### Step: 08

Description of issue
Instructions say turn Boot diagnostics to On.

Current UI provides three options for boot diagnostics:
-  	Enable with managed storage account (recommended)
- 	Enable with custom storage account
- 	Disable

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
This has been addressed by #144
