### ISSUE TITLE
Lab 11

### ISSUE THREAD

**Issue by parveenkrraina** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#147]
# Module: 11
#### Step: 09

On the Add action group blade, in the **Actions section**, specify the following settings (leave others with their default values):
Settings | Value
-- | --
Action group name | az104-11-ag1 email
Action Type | Email/SMS/Push/Voice

It is under the **Notification** section not Action.
Please check.

**Comment by polichtm** [comment]
updated
rgds
Marcin
