### ISSUE TITLE
LAB_01-Manage_Azure_AD_Identities

### ISSUE THREAD

**Issue by idakir** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#149]
# Module: 01
#### Step: 05

You can not use the user principal name for the user az104-01a-aaduser01 as an Email address for the new guest account, you need to mention an external Email address to create the new guest account, you will get an error "user name already exists in the directory"

**Comment by polichtm** [comment]
updated
rgds
Marcin
