### ISSUE TITLE
Create Virtual Network Wizard

### ISSUE THREAD

**Issue by markturpinMSFT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#15]
# Module: 04
#### Step: 03

Description of issue
Creating a virtual network is now a 5 tab wizard instead of one page creation:
![image](https://user-images.githubusercontent.com/55555818/76352807-e438ce80-62cc-11ea-9f7b-0ee9024d4dfe.png)

Thus, the order of required information has changed.

Basics tab - Create New resource group, vnet instance name, region
IP Addresses tab - IPv4 Address Space, Add subnet (subnet name, IP range)
Security tab\Tags tab - defaults
Review & Create tab - Create

**Comment by polichtm** [comment]
The step doe not reference a wizard or a blade, it states simply


Setting | Value
-- | --
Name | az104-04-vnet1
Address space | 10.40.0.0/20
Subscription | the name of the Azure subscription you will be using in this lab
Resource Group | the name of a new resource group az104-04-rg1
Location | the name of any Azure region available in the subscription you will use in this lab
Subnet Name | subnet0
Subnet Address range | 10.40.0.0/24

This is still accurate - isn't it?
rgds
Marcin

**Comment by markturpinMSFT** [comment]
Thanks for updating the order!  Students will definitely point that out to me otherwise.

**Comment by polichtm** [comment]
Certainly – you’re welcome
