### ISSUE TITLE
Changing instructions to clarify JSON editing

### ISSUE THREAD

**Issue by brentd09** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#155]
# Module: 3
#### Step: 4-5

Description of issue
remove the following lines: 
This creates confusion for students
...
"osType": "[parameters('osType')]"
Note: These parameters are removed since they are not applicable to the current deployment. In particular, sourceResourceId, sourceUri, osType, and hyperVGeneration parameters are applicable to creating an Azure disk from an existing VHD file.

In addition, remove the trailing comma from the following line:

"diskSizeGB": "[parameters('diskSizeGb')]",
Note: This is necessary to account for the syntax rules of JSON-based ARM templates.

Repro steps:

1. Students are prone to removing the comma with the line "osType": "[parameters('osType')]" 
1. It would be more clear to; remove step 5 altogether and in step 4 have students remove "osType": "[parameters('osType')]" ,
1. Previous fix would remove the comma when removing the line making the instructions more clear?

**Comment by polichtm** [comment]
this has been addressed via #156 
rgds
Marcin
