### ISSUE TITLE
Lab3b Exc1 Task1 - Downloaded template is invalid

### ISSUE THREAD

**Issue by Master-Guy** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#157]
# Module: 3
### Task: 1

**Description of issue**
The template that you download using the steps described in steps 1-7 in Task 1 is invalid.
When you try to upload the (unmodified) parameters file, the string values are represented as objects instead, which generates warnings after the upload.

> The template has specified this parameter as type 'string', but the default value is specified as type 'object'. This template may not deploy correctly.

This is an issue for Microsoft, but it does create confusion for the students. They should not be asked to use the downloaded files for the time being.
This issue has not been reported to Microsoft by me.

_Edit_
The template also contains parts for `networkAccessPolicy` which are not supported by the Template Deployment process.
This has been addressed in the PR.

**Repro steps:**

1. Resource Groups --> az104-03a-rg1 --> Settings --> Deployments
1. Select first option in the list --> View template --> Download & Extract
1. Deploy a custom template --> Build your own template in the editor --> Load file --> Upload the downloaded template.json --> Save
1. Edit parameters --> Load file --> Upload the downloaded parameters.json --> Save

The parameters are filled as:
`{"type":"String","value":"ActualValue"}`

**Comment by polichtm** [comment]
This has been updated. Pls let us know if any additional clarification is needed
rgds
Marcin
