### ISSUE TITLE
Movement of item in portal

### ISSUE THREAD

**Issue by PaulFou** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#162]
# Module: 08
#### Step: 14

Description of issue
Item moved in portal, step points to wrong location.
Repro steps:

1.The current step say "On the az104-08-vm1 blade, in the Settings section, click Export template."
1.It should now read because of a move of location "On the az104-08-vm1 blade, in the Automation section, click Export template."
1.

**Comment by polichtm** [comment]
updated
