### ISSUE TITLE
Instruction in lab manual is not correct

### ISSUE THREAD

**Issue by brentd09** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#163]
# Module: 11
#### Step: 19

The instruction in the lab manual for step 19. is not correct, here is the problem: (Copied from lab manual)
19. From the Command Prompt, run the following to copy the restore the hosts file to the original location:

  for /l %a in (0,0,1) do echo a
  
  Note: This will initiate the infinite loop that should increase the CPU utilization above the threshold of the newly created alert rule.

Should read something like:
19. Run this command in the command prompt to increase the CPU utilization above the threshold of the newly created alert 

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
updated
rgds
Marcin
