### ISSUE TITLE
Mistake in 09c - Implement Azure Kubernetes Service

### ISSUE THREAD

**Issue by martintietz** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#167]
# Module: 00
#### Step: 05

Description of issue
The description for step 5 states that for the setting of "Network configuration" the value "Advanced" should be set.
Currently there is no option "Advanced". Instead, the only options listed are "kubenet" and "Azure CNI".

**Comment by polichtm** [comment]
Here is what I'm seeing in the Azure portal
![image](https://user-images.githubusercontent.com/10284906/94815736-deb9e780-03c8-11eb-881e-26d48a5e2b21.png)

Can you provide the screenshot of what you're referring to?
rgds
Marcin

**Comment by tiagocostapt** [comment]
@polichtm , its a recent change. What king of subscription you're using? You should see this:

![image](https://user-images.githubusercontent.com/11490197/94816110-3d945680-03f3-11eb-8bc7-200cf9ee8336.png)

**Comment by polichtm** [comment]
Hi Tiago,
a newly activated (a few days ago) Azure Pass subscription
rgds
Marcin

**Comment by polichtm** [comment]
updated
