### ISSUE TITLE
Lab 6: Wrong instruction of adding load balancing rule

### ISSUE THREAD

**Issue by hiryamada** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#169]
# Module: 06
#### Step: 09 - Add a load balancing rule

Description of issue:

Wrong instruction. Students can't find appropriate selection.

Lab instruction:

    Create implicit outbound rules: Yes

Azure Portal:

    Outbound source network address translation (SNAT):
    Outbound and inbound use the same IP. SNAT port exhaustion may occur.  	
    (Recommended) Use outbound rules to provide backend pool members access to the internet. Learn more

**Comment by polichtm** [comment]
addressed by #171
