### ISSUE TITLE
Wrong name listed for virtual network

### ISSUE THREAD

**Issue by markturpinMSFT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#17]
# Module: 06
#### Step: 07

Description of issue

The instructions say to peer with this virtual network:
Virtual network | az104-06-vnet3 (az104-06-**rg2**)

vnet3 is in rg3, not in rg2.  So, this should read as the following:

Virtual network | az104-06-vnet3 (az104-06-**rg3**)

Here's what my vnet options look like after template deployment:
![image](https://user-images.githubusercontent.com/55555818/76465866-b2466b80-63a3-11ea-87dc-f072295a5384.png)

**Comment by polichtm** [comment]
updated
