### ISSUE TITLE
missing field : Public IP Address Name

### ISSUE THREAD

**Issue by Pickacho** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#178]
# Module: 08 Manage Virtual Machines Student lab manual
#### Step: 00

Description of issue
In exercise 1 task 13 you are expected to create from template a new machine with the following:

13.**On the Custom deployment blade, specify the following settings (leave others with their default values):**
Setting | Value
-- | --
Resource group | az104-08-rg01
Network Interface Name | az104-08-vm1-nic1
**Public Ip Address Name | az104-08-vm1-ip**   This part is missing since in az104-08-vm1 we disabled the public IP address name
Virtual Machine Name | az104-08-vm1
Virtual Machine Computer Name | az104-08-vm1
Admin Username | Student
Admin Password | Pa55w.rd1234
Zone | 2

**Comment by polichtm** [comment]
updated
