### ISSUE TITLE
Wrong name listed for App Gateway

### ISSUE THREAD

**Issue by markturpinMSFT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#18]
# Module: 06
#### Step: 15,16

Description of issue

Current steps list the name of the resource group, not the name of the application gateway:

In the Azure portal, search and select Application Gateways and, on the Application Gateways blade, click az104-06-**rg5**.

On the az104-06-**rg5** Application Gateway blade, note the value of the Frontend public IP address.

Instead, these should say:

In the Azure portal, search and select Application Gateways and, on the Application Gateways blade, click az104-06-**appgw5**.

On the az104-06-**appgw5** Application Gateway blade, note the value of the Frontend public IP address.

Excellent lab btw!

**Comment by polichtm** [comment]
updated
