### ISSUE TITLE
Can not delete tenant/directory

### ISSUE THREAD

**Issue by TechGuyVincent** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#182]
On the last step - we need to delete the directory but thats not possible since the licenses first have to expire. Suggest we add the text "Note that deleting the tenant is not possible until your licenses have expired - but will not incur any cost on you subscription".

**Comment by polichtm** [comment]
Pls provide the reference to the lab, exercise, and task number
rgds
Marcin

**Comment by TechGuyVincent** [comment]
Last part : Clean up resources (No task number) 
Step 7. 

If I understand this correctly, its about deleting the tenant afterwards correct?

**Comment by polichtm** [comment]
Correct. 
Are you still seeing this behavior after you perform the first three steps?

Navigate to the Azure Active Directory Premium P2 - Licensed users blade, select the user accounts to which you assigned licenses in this lab, click Remove license, and, when prompted to confirm, click OK.

In the Azure portal, navigate to the Users - All users blade, click the entry representing the az104-01b-aaduser1 guest user account, on the az104-01b-aaduser1 - Profile blade click Delete, and, when prompted to confirm, click OK.

Repeat the same sequence of steps to delete the remaining user accounts you created in this lab.

rgds
Marcin

**Comment by TechGuyVincent** [comment]
Yes, the erromessage I get is basically that the tenant can't be deleted (when doing the testing if one can delete it or not) if there is an active trial subscription still active. So the license is not attached to any user - but the trial is still activated - and can't be removed until expired. And if the trial can't be removed - then the tenant can't be deleted. 

I can remove the licenses and users - but not the tenant itself (delete the whole tenant) unless the licenses themselves have expired.

**Comment by polichtm** [comment]
updated
rgds
Marcin
