### ISSUE TITLE
lab_06 peering instructions need to be updated

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#185]
# Module: 06
#### Step: 05

Description of issue
1 Peering interface has changed

Allow Gateway Transit not listed anymore

Allow virtual network access from az104-06-vnet01 to az104-06-vnet2 | **Enabled** |
    | Allow virtual network access from az104-06-vnet2 to az104-06-vnet01 | **Enabled** |
    | Allow forwarded traffic from az104-06-vnet2 to az104-06-vnet01 | **Disabled** |
    | Allow forwarded traffic from az104-06-vnet01 to az104-06-vnet2 | **Enabled** |
    | Allow gateway transit | **(Uncheck Box)** |   **Not there anymore**

SHOULD BE

Traffic to remote virtual network .  | **Allow (default)
Traffic forwarded from remote network  | **Block traffic**

![image](https://user-images.githubusercontent.com/24426530/98064557-8e351e80-1e8d-11eb-82c6-408396e929a0.png)

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
updated
