### ISSUE TITLE
lab_06 template location need to be updated

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#186]
# Module: 06
## Lab/Demo: 00
**Exercise 1
#### Step: 00

Description of issue

**\\Allfiles\\Module_06\\az104-06-vms-template.json**, **\\Allfiles\\Labs\\06\\az104-06-vm-template.json**, and **\\Allfiles\\Labs\\06\\az104-06-vm-parameters.json** into the Cloud Shell home directory.

**\\Allfiles\\Module_06\\az104-06-vms-template.json**, 
SHould BE
\\Allfiles\\Labs\\az104-06-vms-template.json**,

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
close ;) - it's actually Labs\\06 - updated
