### ISSUE TITLE
LAB_05 peering instructions need to be updated

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#187]
# Module: 05
#### Step: 00

Description of issue
Peering interface has changed. 

Allow virtual network access from az104-05-vnet0 to az104-05-vnet1 | **Enabled** |
    | Allow virtual network access from az104-05-vnet1 to az104-05-vnet0 | **Enabled** |
    | Allow forwarded traffic from az104-05-vnet1 to az104-05-vnet0 | **Disabled** |
    | Allow forwarded traffic from az104-05-vnet0 to az104-05-vnet1 | **Disabled** | **Not there anymore**

SHOULD BE

Traffic to remote virtual network .  | **Allow (default)
Traffic forwarded from remote network  | **Block traffic**

Please update instructions  on all 3 peerings

![image](https://user-images.githubusercontent.com/24426530/98065537-c0478000-1e8f-11eb-89c9-3c52dc0cc325.png)

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
updated
