### ISSUE TITLE
Lab 8 Manage Virtual Machines Value for Edit Template Line number is wrong

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#188]
# Module: 08
#### Step: 15

Description of issue
 On the **Edit template** blade, in the section displaying the content of the template, replace line **49** (`                    "dataDisks": [ ]` line) with the following code :

SHOULD BE

 On the **Edit template** blade, in the section displaying the content of the template, replace line **50** (`                    "dataDisks": [ ]` line) with the following code :
Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
updated
