### ISSUE TITLE
Lab file - License file has no extension

### ISSUE THREAD

**Issue by markturpinMSFT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#19]
# Module: 07
#### Step: 09

Description of issue

Specifically regarding the License file that's part of the module 7 lab files.

As currently configured, the License file has no extension (or the extension is File).  As a result, when i create the SAS token and hit the URL, my various browsers download the file.  It does not render the file in my browser.  Additionally, if I go to Edit the blob, it warns me "The file 'licenses/LICENSE' may not render correctly as it contains an unrecognized extension.."  

This file should be changed in the lab files to have a txt extension.  I have tested it as License.txt and it works perfectly in Edit (rendering) and when I hit the SAS URL (displays the page).

**Comment by polichtm** [comment]
updated
