### ISSUE TITLE
 Steps not matching the portal

### ISSUE THREAD

**Issue by swptmp** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#191]
# Module: 06
#### Step: 07

Hi, we have a complaint from a customer that the lab steps are not matching what the Azure portal currently resembles.  Her most recent complaint is from Module 06.

Repro steps:

1.
1.
1.

**Comment by staleycyn** [comment]
Can you be more specific? That would include specifying the steps that are not accurate and suggested fixes. Thank you.

**Comment by polichtm** [comment]
updated
rgds
Marcin
