### ISSUE TITLE
az-104-11-rg0 not deploying

### ISSUE THREAD

**Issue by zperk028** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#193]
#### Step: 06

After uploading the JSON template and parameters, and running the PowerShell in Cloud Shell to deploy the resource group, the resource group az-104-11-gr0 is created, but contains nothing. This was discovered later in Task 4, Step 1, when going to the Virtual Machines blade and there are no virtual machines to display. 

The template and parameters JSON files exist when checking `dir` in the Cloud Shell.

**Comment by polichtm** [comment]
I'm not able to reproduce this. Would you mind giving this another try and posting the screenshot of the Cloud Shell pane following the deployment?
rgds
Marcin

**Comment by zperk028** [comment]
> I'm not able to reproduce this. Would you mind giving this another try and posting the screenshot of the Cloud Shell pane following the deployment?
> rgds
> Marcin

Thanks for looking into this. I deleted rg0 and rg1, and went through the steps again, taking screencaps along the way.  I am still left with an empty RG0 and no virtual machines. 

![lab11step1](https://user-images.githubusercontent.com/71294976/98702960-03e73180-2349-11eb-860a-687cdaffa345.JPG)
![lab11step2](https://user-images.githubusercontent.com/71294976/98702972-06498b80-2349-11eb-860c-9c3302579c3d.JPG)
![lab11step3](https://user-images.githubusercontent.com/71294976/98702988-09dd1280-2349-11eb-9ff4-e1925fd045c8.JPG)
![lab11step4](https://user-images.githubusercontent.com/71294976/98702997-0d709980-2349-11eb-9209-363dcd766a20.JPG)
![lab11step5](https://user-images.githubusercontent.com/71294976/98703010-0fd2f380-2349-11eb-8d40-310312b2fb7a.JPG)
![lab11step6](https://user-images.githubusercontent.com/71294976/98703022-13667a80-2349-11eb-9c4d-c0f05d2dcb20.JPG)
![lab11step7](https://user-images.githubusercontent.com/71294976/98703048-18c3c500-2349-11eb-8872-8619a35e1fa6.JPG)
![lab11step8](https://user-images.githubusercontent.com/71294976/98703057-1b261f00-2349-11eb-9a6d-b1650ffa169f.JPG)
![lab11step9](https://user-images.githubusercontent.com/71294976/98703071-1d887900-2349-11eb-8ff9-0060d8a2cc66.JPG)
![lab11step10](https://user-images.githubusercontent.com/71294976/98703090-20836980-2349-11eb-87f3-372acca1dd94.JPG)

**Comment by polichtm** [comment]
Can you re-run the deployment but without the final -AsJob parameter?
rgds
Marcin

**Comment by zperk028** [comment]
> Can you re-run the deployment but without the final -AsJob parameter?
> rgds
> Marcin

When trying with `-AsJob` removed, I get the following error: 

![lab11step1a](https://user-images.githubusercontent.com/71294976/98705012-4447af00-234b-11eb-874f-9a8e7dac3e05.JPG)
![lab11step2a](https://user-images.githubusercontent.com/71294976/98705017-46117280-234b-11eb-806a-1091279e16b3.JPG)

**Comment by polichtm** [comment]
Here is what I'm seeing:
![image](https://user-images.githubusercontent.com/10284906/98878128-3039a580-2450-11eb-909e-0fe5160192c3.png)

Pls post both the template and the parameter file you're using
rgds
Marcin

**Comment by zperk028** [comment]
> Here is what I'm seeing:
> ![image](https://user-images.githubusercontent.com/10284906/98878128-3039a580-2450-11eb-909e-0fe5160192c3.png)
> 
> Pls post both the template and the parameter file you're using
> rgds
> Marcin

Posting the two files as a .zip since it won't allow me to upload .json

[az104-11-vm-template-and-parameters.zip](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/files/5534106/az104-11-vm-template-and-parameters.zip)

**Comment by polichtm** [comment]
These are not valid ARM templates. Pls follow up with your instructor
rgds
Marcin
