### ISSUE TITLE
No option to disable ASC Basic

### ISSUE THREAD

**Issue by markturpinMSFT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#20]
# Module: 08
#### Step: 08

Description of issue

Setting | Value
-- | --
Enable basic plan for free | No

For the setting on the Management tab of the Create a VM wizard, I do not see an option to enable/disable the Basic plan for Azure Security Center.  I am using an MSDN subscription, but I don't believe this option would appear on an Azure Pass subscription either, so we can remove it, unless you know differently.

![image](https://user-images.githubusercontent.com/55555818/76561382-6c9ba880-6460-11ea-937f-6153efe05616.png)

**Comment by polichtm** [comment]
![image](https://user-images.githubusercontent.com/10284906/76701695-bc18e900-6699-11ea-802c-0f3ea3c1feca.png)

**Comment by markturpinMSFT** [comment]
Interesting!  @polichtm Are you doing that from an Azure Pass subscription?

**Comment by polichtm** [comment]
yes
