### ISSUE TITLE
LAB_04 Create new public IP instructions needs to be updated

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#200]
# Module: 00
#### Step: 06

Description of issue
There is some slight  GUI drift from the instructions.

On the **ipconfig1** blade, in the **Public IP address settings** section, select **Associate** and then click **IP address - Configure required settings**. 

On the **Choose public IP address blade**, click **+ Create new** and create a new public IP address with the following settings:

    | Setting | Value |
    | --- | --- |
    | Name | **az104-04-pip0** |
    | SKU | **Standard** |

    **Should Be Changed to** 

 On the **ipconfig1** blade, in the **Public IP address settings** section, select **Associate** and then click **Create new** 
 and create a new public IP address with the following settings:

    | Setting | Value |
    | --- | --- |
    | Name | **az104-04-pip0** |
    | SKU | **Standard** |

![image](https://user-images.githubusercontent.com/24426530/100695078-6a50f400-33cb-11eb-8e5e-1015436a8520.png)

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
updated
