### ISSUE TITLE
Lab_08 custom deployment  pip variable name needs to be changed

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#202]
# Module: 08
#### Step: 12

Description of issue  
Public IP Address Name | **az104-08-vm0-ip* needs to reflect new vm1 name *
 On the **Custom deployment** blade, specify the following settings (leave others with their default values):

    | Setting | Value | 
    | --- | --- |
    | Resource group | **az104-08-rg01** |
    | Network Interface Name | **az104-08-vm1-nic1** |
     | Virtual Machine Name | **az104-08-vm1** |
    | Virtual Machine Computer Name | **az104-08-vm1** |
    | Admin Username | **Student** |
    | Admin Password | **Pa55w.rd1234** |
    | Zone | **2** |

Should Be
| Setting | Value | 
    | --- | --- |
    | Resource group | **az104-08-rg01** |
    | Network Interface Name | **az104-08-vm1-nic1** |
    | Public IP Address Name | **az104-08-vm1-ip**
    | Virtual Machine Name | **az104-08-vm1** |
    | Virtual Machine Computer Name | **az104-08-vm1** |
    | Admin Username | **Student** |
    | Admin Password | **Pa55w.rd1234** |
    | Zone | **2** |

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
updated
rgds
Marcin
