### ISSUE TITLE
Lab11 enable guest-level monitoring not there on diagnostic settings

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#203]
# Module: 11
#### Step: 02

Description of issue
Click *Enable guest-level monitoring** not there.

In this task, you will configure Azure virtual machine diagnostic settings.

1. On the **az104-11-vm0** blade, in the **Monitoring** section, click **Diagnostic settings**.

1. On the **Overview** tab of the **az104-11-vm0 | Diagnostic settings** blade, click **Enable guest-level monitoring**.
Repro steps:

![image](https://user-images.githubusercontent.com/24426530/100995074-3ffd6300-3592-11eb-98b5-0c69186f3154.png)

1.
1.
1.

**Comment by polichtm** [comment]
Hi David,
here is what I'm seeing
![image](https://user-images.githubusercontent.com/10284906/101246398-156df000-36e1-11eb-9dc7-cf9ef927958a.png)

Your screenshot indicates that you have already enabled the diagnostics settings
rgds
Marcin

**Comment by dpapkin** [comment]
> Hi David,
> here is what I'm seeing
> ![image](https://user-images.githubusercontent.com/10284906/101246398-156df000-36e1-11eb-9dc7-cf9ef927958a.png)
> 
> Your screenshot indicates that you have already enabled the diagnostics settings
> rgds
> Marcin

Noted with thanks.
