### ISSUE TITLE
Lab05 peering instructions need some revision due to portal drift

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#204]
# Module: 05
#### Step: 05

Description of issue
The peering instructions have drifted from the portal, also need to have the order changed somewhat. Students getting confused. I have changed all 3 of the peering , rerdered them to follow the portal.

 1. Add a peering with the following settings (leave others with their default values):

    | Setting | Value|
    | --- | --- |
    | Name of the peering from az104-05-vnet0 to remote virtual network | **az104-05-vnet0_to_az104-05-vnet1** |
    | Virtual network deployment model | **Resource manager** |
    | Subscription | the name of the Azure subscription you are using in this lab |
    | Virtual network | **az104-05-vnet1 (az104-05-rg1)** |
    | Name of the peering from az104-05-vnet1 to az104-05-vnet0 | **az104-05-vnet1_to_az104-05-vnet0** |
    | Allow virtual network access from az104-05-vnet0 to az104-05-vnet1 | **Enabled** |
    | Traffic to remote virtual network | **Allow (default)** |
    | Traffic forwarded from remote virtual network | **Block traffic that originates from outside this virtual network** |

    **SHOULD BE**

     Add a peering with the following settings (leave others with their default values):

    | Setting | Value|
    | --- | --- |
    | Below "This virtual network" heading
    | Peering link name (from az104-05-vnet0 to remote virtual network) | **az104-05-vnet0_to_az104-05-vnet1** |
   | Traffic to remote virtual network | **Allow (default)** |
   | Traffic forwarded from remote virtual network | **Block traffic that originates from outside this virtual network** |
   
    Below "Remote virtual network" heading
    |Peering link Name (of the peering from az104-05-vnet1 to az104-05-vnet0) | **az104-05-vnet1_to_az104-05-vnet0** |
    | Subscription | the name of the Azure subscription you are using in this lab |
    | Virtual network | **az104-05-vnet1 (az104-05-rg1)** |
    |Traffic to remote virtual network | **Allow (default)**
    |Traffic forwarded from remote virtual network | **Block traffic that originates from outside this virtual network**
  

    >**Note**: This step establishes two local peerings - one from az104-05-vnet0 to az104-05-vnet1 and the other from az104-05-vnet1 to az104-05-vnet0.

1. On the **az104-05-vnet0** virtual network blade, in the **Settings** section, click **Peerings** and then click **+ Add**.

1. Add a peering with the following settings (leave others with their default values):

    | Setting | Value|
    | --- | --- |
    | Name of the peering from az104-05-vnet0 to remote virtual network | **az104-05-vnet0_to_az104-05-vnet2** |
    | Virtual network deployment model | **Resource manager** |
    | Subscription | the name of the Azure subscription you are using in this lab |
    | Virtual network | **az104-05-vnet2 (az104-05-rg2)** |
    | Name of the peering from az104-05-vnet2 to az104-05-vnet0 | **az104-05-vnet2_to_az104-05-vnet0** |
    | Traffic to remote virtual network | **Allow (default)** |
    | Traffic forwarded from remote virtual network | **Block traffic that originates from outside this virtual network** |

    >**Note**: This step establishes two global peerings - one from az104-05-vnet0 to az104-05-vnet2 and the other from az104-05-vnet2 to az104-05-vnet0.

    **SHOULD BE**

     Add a peering with the following settings (leave others with their default values):

    | Setting | Value|
    | --- | --- |
    | Below "This virtual network" heading
    | Peering link name (from az104-05-vnet0 to remote virtual network) | **az104-05-vnet0_to_az104-05-vnet2** |
   | Traffic to remote virtual network | **Allow (default)** |
   | Traffic forwarded from remote virtual network | **Block traffic that originates from outside this virtual network** |
   
    Below "Remote virtual network" heading
    |Peering link Name (of the peering from az104-05-vnet1 to az104-05-vnet0) | **az104-05-vnet2_to_az104-05-vnet0** |
    | Subscription | the name of the Azure subscription you are using in this lab |
    | Virtual network | **az104-05-vnet2 (az104-05-rg2)** |
    |Traffic to remote virtual network | **Allow (default)**
    |Traffic forwarded from remote virtual network | **Block traffic that originates from outside this virtual network**

1. Navigate back to the **Virtual networks** blade and, in the list of virtual networks, click **az104-05-vnet1**.

1. On the **az104-05-vnet1** virtual network blade, in the **Settings** section, click **Peerings** and then click **+ Add**.

1. Add a peering with the following settings (leave others with their default values):

    | Setting | Value|
    | --- | --- |
    | Name of the peering from az104-05-vnet1 to remote virtual network | **az104-05-vnet1_to_az104-05-vnet2** |
    | Virtual network deployment model | **Resource manager** |
    | Subscription | the name of the Azure subscription you are using in this lab |
    | Virtual network | **az104-05-vnet2 (az104-05-rg2)** |
    | Name of the peering from az104-05-vnet2 to az104-05-vnet1 | **az104-05-vnet2_to_az104-05-vnet1** |
    | Traffic to remote virtual network | **Allow (default)** |
    | Traffic forwarded from remote virtual network | **Block traffic that originates from outside this virtual network** |

    >**Note**: This step establishes two global peerings - one from az104-05-vnet1 to az104-05-vnet2 and the other from az104-05-vnet2 to az104-05-vnet1.

    **SHOULE BE**

     Add a peering with the following settings (leave others with their default values):

    | Setting | Value|
    | --- | --- |
    | Below "This virtual network" heading
    | Peering link name (from az104-05-vnet0 to remote virtual network) | **az104-05-vnet1_to_az104-05-vnet2** |
   | Traffic to remote virtual network | **Allow (default)** |
   | Traffic forwarded from remote virtual network | **Block traffic that originates from outside this virtual network** |
   
    Below "Remote virtual network" heading
    |Peering link Name (of the peering from az104-05-vnet1 to az104-05-vnet0) | **az104-05-vnet2_to_az104-05-vnet1** |
    | Subscription | the name of the Azure subscription you are using in this lab |
    | Virtual network | **az104-05-vnet2 (az104-05-rg2)** |
    |Traffic to remote virtual network | **Allow (default)**
    |Traffic forwarded from remote virtual network | **Block traffic that originates from outside this virtual network**

#### Task 3: Test intersite connectivity 
![image](https://user-images.githubusercontent.com/24426530/101452966-8de6e200-3969-11eb-9c33-5a237659395b.png)

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
updated

**Comment by awillslo** [comment]
I agree, nice job.

**Comment by dpapkin** [comment]
Thank you very much.

Your team is doing an awesome job.

I try and suggest the revisions to try and help to lighten the load on you all. You must be very busy.

Is there other way I can help contribute?

I am trying to get my MVP on Azure.

Trying to help make the world a better place, one web page at a time.....

David Papkin

________________________________
