### ISSUE TITLE
Lab 07 Task 6: Manage network access for Azure Storage 

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#205]
# Module: 07
#### Step: 01

Description of issue

Some portal drift.

1. In the Azure portal, navigate back to the blade of the storage account you created in the first task of this lab and, in the **Settings** section, click **Firewalls and virtual networks**.

**SHOULD BE***

1. In the Azure portal, navigate back to the blade of the storage account you created in the first task of this lab and, in the **Settings** section, click  **Networking** then  **Firewalls and virtual networks**.

![image](https://user-images.githubusercontent.com/24426530/101594694-18444a00-3a2d-11eb-9708-7aedf5a26fc1.png)

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
updated
