### ISSUE TITLE
Setting 'Public IP Address Name' is not an option when deploying from template

### ISSUE THREAD

**Issue by dave-007** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#208]
# Module: 08
#### Step: 13

Description of issue

Student does not have setting for 'Public IP Address Name' when deploying from template created, as the choices from step 7 indicate no public IP.

Repro steps:

1. Perform steps 1-12
1. At Step 13, note there is no 'Public IP Address Name'

Possible workaround to go without public IP, or create one with the 'Public Ip' settings in step 7.

**Comment by polichtm** [comment]
Hi Dave,
would you mind posting the screenshot of what you're referring to?
Here is what I'm seeing:

![image](https://user-images.githubusercontent.com/10284906/101892390-534f9600-3b71-11eb-81c3-56c35dc6e602.png)

rgds
Marcin

**Comment by dave-007** [comment]
It looks like yours now with a Public Ip Address Name :) Not sure what changed in our steps.
Please close.
