### ISSUE TITLE
Creating VM Scale Set workflow has changed

### ISSUE THREAD

**Issue by markturpinMSFT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#21]
# Module: 08
#### Step: 02-06
*Edits made after digging in further

Description of issue

1st Issue - VM size is listed in instructions as D2s v3, but that might confusing to students when they go to resize the VM, since it lists it as D2s_v3 (includes the underscore).
![image](https://user-images.githubusercontent.com/55555818/76588692-db9af080-64a4-11ea-8188-07af63b46ed2.png)

2nd issue - scale sets are now using the new multiple tab wizard style.  This drastically changes how someone would try to follow the existing instructions to create a scale set in the previous method.  Basics, Networking, Scaling, and Management tabs require a different set of instructions. 

A few observations:

The load balancing fields are in Step 2 (which is mostly the Basics tab) but they should be moved to Step 3 (networking tab).  Step 3 is creating the new virtual network and the load balancing settings are located at the bottom, after you configure the vnet.  However, you can't configure a public IP on the LB from this wizard.

In order to configure the NSG settings and create a public IP with and inbound rule (steps 5 and 6), you now have to edit the network interface.  
![image](https://user-images.githubusercontent.com/55555818/76590770-80b8c780-64ab-11ea-8959-e8da981360a5.png)

It should be noted that after you create a new advanced NSG and add the inbound rule (step 6), you have to "enable" the public IP.  There's no option for creating a name for the Azure Resource - Public IP, OR any option for a DNS name label, which are listed in Step 2.
![image](https://user-images.githubusercontent.com/55555818/76591085-777c2a80-64ac-11ea-891f-03bbb1f3e4ea.png)

Lastly, the Scaling policy options are different.  There's no Autoscale option to disable as listed in step 2.  Instead, it is manual/custom, with custom being the autoscale version.  I assume we can just assume defaults here and remove that option from step 2.
![image](https://user-images.githubusercontent.com/55555818/76591149-a8f4f600-64ac-11ea-86c8-43caed55ac57.png)

**Comment by polichtm** [comment]
updated
