### ISSUE TITLE
Lab 08 - Manage Virtual Machines No Default value for boot diagnostics account

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#212]
# Module: 08
#### Step: 08

Description of issue
** Diagnostics storage account | accept the default value.**  There is no default value. You must click **Create new** and create a new storage account

    | Setting | Value | 
    | --- | --- |
    | Boot diagnostics | **Enable with custom storage account** |
    | Diagnostics storage account | accept the default value |

SHOULD BE

 | Setting | Value | 
    | --- | --- |
    | Boot diagnostics | **Enable with custom storage account** |
    | Diagnostics storage account | Click **Create new** and create a new diagnostics storage account

-- | --

![image](https://user-images.githubusercontent.com/24426530/102568532-a485f980-411e-11eb-95d0-236396640ace.png)

Repro steps:

1.
1.
1.

**Comment by AustinP00** [comment]
replacement made in instructions

**Comment by polichtm** [comment]
this was addressed by the most recent PR
rgds
Marcin
