### ISSUE TITLE
Lab07 - new Storage Account UI? 

### ISSUE THREAD

**Issue by tiagocostapt** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#213]
# Module: 07
### Task: 02

Description of issue
Some of my students are seeing a new UI to create Storage Accounts. My Portal is still ok but it seems to be a new UI. Consider update instructions. I will try to get a screenshot to update this issue.

Repro steps:

1. No repro steps...

**Comment by dpapkin** [comment]
it would be helpful to see a screenshot of this new UI. Thanks.

**Comment by polichtm** [comment]
Hi Tiago, 
I'm not seeing any changes to the interface. We'll revisit this once the changes take place
rgds
Marcin

**Comment by tiagocostapt** [comment]
It's showing again to some students.... Again not to all students. It might be interesting to add a note into the instructions? This might be rolling out to all sub types, etc... 

![image](https://user-images.githubusercontent.com/11490197/106861256-7011d100-66bd-11eb-9215-20d52bc678f2.png)
