### ISSUE TITLE
LAB_01 missing new password detail

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#216]
# Module: 01
#### Step: 10

Description of issue

Detail not given to change password to the usual password Pa55w.rd1234. This ambiguity can lead to students  using various passwords that they might not remember and getting locked out.

Open an **InPrivate** browser window and sign in to the [Azure portal](https://portal.azure.com) using the newly created user account. When prompted to update the password, change the password for the user.
SHOULD BE

Open an **InPrivate** browser window and sign in to the [Azure portal](https://portal.azure.com) using the newly created user account. When prompted to update the password, change the password for the user to **Pa55w.rd1234**.

Repro steps:

1.
1.
1.

**Comment by AustinP00** [comment]
made hard replacement - instructions have been edited

**Comment by polichtm** [comment]
Hi David,
that's intentional. AD will occasionally block the use of passwords that are considered "too common" based on heuristics. This is actually meant to avoid confusion.
rgds
Marcin
