### ISSUE TITLE
LAB_03a Create Resource group  portal drift

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#217]
# Module: 03
#### Step: 03

Description of issue. Portal drift on Create Resource Group.

 On the **Resource groups** blade, click **+ Add** and create a resource group with the following settings:

SHOULD BE

 On the **Resource groups** blade, click **+ Create** and create a resource group with the following settings:

![image](https://user-images.githubusercontent.com/24426530/104795973-7b27be80-57ed-11eb-8776-b3a6e4348665.png)

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
Hi David,
here is what I'm seeing

![image](https://user-images.githubusercontent.com/10284906/104796758-2c473e00-5787-11eb-8ce4-aee5db18c1e1.png)

rgds
Marcin

**Comment by dpapkin** [comment]
Hi Marcin, I included a screenshot of what I saw today.

I just tried again, using Chrome(incognito) and Edge. 

![image](https://user-images.githubusercontent.com/24426530/104798138-20975e00-57ff-11eb-80de-de3e78db1897.png)

Perhaps it is because we are in different parts of the world? I am in Singapore.

Regards,

David Papkin

**Comment by polichtm** [comment]
Hi David,
Looks like this might have something to do with regional/language settings... 
Regarding the approach, your suggestion would work - although considering the options, I gather there is not much room for confusion.
My preference would be to stay away from specific portal graphical elements whenever possible. 
How about simply "From the **Resource group**, add a new resource group with the following settings"?
rgds
Marcin
