### ISSUE TITLE
2a lab requirements 

### ISSUE THREAD

**Issue by staleycyn** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#218]
# Module: 00
#### Step: 00

Please add lab requirements to Lab 2a. 

**Lab requirements**: This lab requires that the user have permissions to create users, create administrative users, and/or create or modify policies at a ‘permissions level’. Not all lab hosters may provide this capability. Ask your instructor for the availability of this lab. 

Thanks - Cindy

**Comment by polichtm** [comment]
Hi Cindy,
updated
rgds
Marcin
