### ISSUE TITLE
Automatically created Public IP resource has different name (due to Create a VMSS wizard workflow change)

### ISSUE THREAD

**Issue by markturpinMSFT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#22]
# Module: 08
#### Step: 13

Description of issue

Due to the changes listed in this issue:
https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/issues/21

The user is unable to create the name for the public IP azure resource in previous steps during the Create a VMSS wizard.  The system creates the name instead with the new workflow, and thus has a different name.

Name in instructions (when you could specify the PIP name as part of the Create a VMSS wizard):  az10408vmss0-**pip**

New name (system created): az10408vmss0-**ip**

Changing the code in step 13 to use the new system generated name (az10408vmss0-**ip**) results in success.

**Comment by polichtm** [comment]
updated
