### ISSUE TITLE
Unable to link Automation account and Log Analytics Workspace

### ISSUE THREAD

**Issue by IISanitariumII** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#220]
# Module: 00
#### Step: 06

I keep running into this error via my lab. Any help is most appreciated.
![image](https://user-images.githubusercontent.com/14335020/105667645-4aa4ec00-5ea1-11eb-9cce-6a44c4b38e2b.png)

Repro steps:

1. I am unable to link the Automation account and log analytics account even though they are both within the same region 'CentralUS'

**Comment by polichtm** [comment]
What type of subscription are you using?
Have you tried other combinations (e.g. East US and East US2)?
rgds
Marcin

**Comment by IISanitariumII** [comment]
I have a pay as you go account, if that’s what you are referring to. When I
go home I’ll try some other regions.

**Comment by IISanitariumII** [comment]
I do believe I found out the issue. It was most likely the region mapping I had was incorrect. I am going to go back and retest this theory again.

**Comment by polichtm** [comment]
Pls confirm whether this has been resolved
rgds
Marcin

**Comment by polichtm** [comment]
Closing due to lack of response
