### ISSUE TITLE
parameter not found 'nameSuffix'

### ISSUE THREAD

**Issue by pbrickner2020** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#221]
# Module: AZ-104
#### Step: 06, 08 and 10

Description of issue: fails with error

New-AzResourceGroupDeployment: A parameter cannot be found that matches parameter name 'nameSuffix'.
It will not work with -nameSuffix
![lab05](https://user-images.githubusercontent.com/72821529/105921556-f582ea80-6006-11eb-9ded-835367b4641c.jpg)

Repro steps:

1.
![lab05](https://user-images.githubusercontent.com/72821529/105921580-04699d00-6007-11eb-943c-b5bfcf1720fe.jpg)

1.
1.

**Comment by polichtm** [comment]
Hi Paul,
this works for me without any issues
![image](https://user-images.githubusercontent.com/10284906/106057775-74872a00-60be-11eb-854f-040a4fc5da32.png)
Pls post the content of your template 
rgds
Marcin

**Comment by pbrickner2020** [comment]
The template I downloaded from GitHub and are the exact files in your
screenshot, but it didn't create the subnets and gave error about the
"-nameSuffix 0" parameter

**Comment by polichtm** [comment]
Pls post the template
rgds
Marcin

**Comment by pbrickner2020** [comment]
[ARM_Templates.zip](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/files/5884701/ARM_Templates.zip)

**Comment by polichtm** [comment]
This is not a valid ARM template.
Are you an MCT?
rgds
Marcin

**Comment by pbrickner2020** [comment]
I did get my MCT years ago, but, I am just taking the AZ-104 course and was
trying to do the labs.  The labs pointed me at these ARM templates.

**Comment by polichtm** [comment]
Hi Paul,
this forum is intended for MCTs who are teaching this particular course. Pls reach out to your instructor. The file you are using is not an ARM template
rgds
Marcin
