### ISSUE TITLE
Issue Creating pdfs from markdown 

### ISSUE THREAD

**Issue by jmenne** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#226]
Thank you for your great work with this repository and your fast support!
My issue is not an issue with the course content but with syntx highlighting in created pdfs.
I use pandoc to create .pdf documents directly from the.md files.
If the lines in the fenced code blocks are too long they won't be wrapped in the output.
The reason I found is the ` ```pwsh`, which is unrecognized by pandoc and LaTex. 
If ` ```powershell` is used like in the example below everything is formatted well and long lines are wrapped correctly.
Is it possible to change all occurences of ` ```pwsh` to ` ```powershell` in the lab files?
This would make creating pdfs from markdown so much easier.

```
```powershell
   $scope = (Get-AzRoleAssignment -RoleDefinitionName 'Support Request Contributor (Custom)').Scope

   Remove-AzRoleAssignment -ObjectId '[object_ID]' -RoleDefinitionName 'Support Request Contributor (Custom)' -Scope $scope
   ```
```

**Comment by polichtm** [comment]
This will be addressed shortly
rgds
Marcin

**Comment by polichtm** [comment]
Just to clarify - your example does not account for indentation - is this intentional?
rgds
Marcin

**Comment by jmenne** [comment]
Hi Marcin, it's not intentional. It's enough to change the pwsh to powershell.
Thank's
Jörg

**Comment by polichtm** [comment]
Hi Jorg,
this is completed
rgds
Marcin
