### ISSUE TITLE
Update variable name to match code block name

### ISSUE THREAD

**Issue by markturpinMSFT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#23]
# Module: 09a
#### Step: 05

Description of issue

The variable references deployment_name but should match the code block with deployment_user_name.

Current:
From the Cloud Shell pane, run the following to add the remote git (make sure to replace the [**deployment_name**] and [git_clone_url] placeholders

Suggested:
From the Cloud Shell pane, run the following to add the remote git (make sure to replace the [**deployment_user_name**] and [git_clone_url] placeholders

**Comment by polichtm** [comment]
updated
