### ISSUE TITLE
Improved Templates for Labs 4, 5 and 6

### ISSUE THREAD

**Issue by jmenne** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#232]
Hi!
I've invested some time to improve the templates for Lab 4, Lab 5 and Lab 6. Explicitly in the latter ones Students have to deploy three times with different name suffixes and Azure Regions. This is error prone and time consuming. So I figured out a way to deploy the lab environments with only one template and parameter file per lab. All resources are in one resource group instead of three. The advantage is that you can use Networkwatcher to view the network topology. The deployments do not take that long, are not prone to errors and save us valuable time in class.
If you like the changes, I would be happy if you accept them and insert them into the repo.

Kind regards and stay healthy
Jörg

[loop-templates_and_labfiles.zip](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/files/5936725/loop-templates_and_labfiles.zip)

**Comment by polichtm** [comment]
Hi Jorg,
appreciated - we'll include these updates in the existing content
rgds
Marcin

**Comment by polichtm** [comment]
updated
rgds
Marcin

**Comment by RasmusDK** [comment]
As I right now going through these labs, I just wanted to thank you for the improvement :)

**Comment by koushik80** [comment]
Hi Jörg!

Great Job! Thanks.

Best regards,
Koushik
