### ISSUE TITLE
Unable to get PHP staging app running

### ISSUE THREAD

**Issue by markturpinMSFT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#24]
# Module: 09a
#### Step: 10

Description of issue

Following all instructions through this lab, my staging app does not come up with the Hello World page - staging url still shows the default page.

My git push was successful and i have all the files in the requisite section.
![image](https://user-images.githubusercontent.com/55555818/76689876-a94dd800-65f7-11ea-9c46-0a347c560ecd.png)

![image](https://user-images.githubusercontent.com/55555818/76689948-78ba6e00-65f8-11ea-8858-c7d0dcbbd4ba.png)

My username/password work, my git clone URL is verified.

Perhaps I've made a small mistake somewhere (done this twice), but can you verify this lab works?

**Comment by polichtm** [comment]
Yes - this works for me
![image](https://user-images.githubusercontent.com/10284906/76786162-1e9ee180-678d-11ea-9db3-f81366f2235b.png)
