### ISSUE TITLE
command line to create vm from template does not work

### ISSUE THREAD

**Issue by mvaricak** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#242]
# Module: 00
#### Step: 00

Description of issue
complains that -namesuffix is not a valid parameter
Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
Pls provide the repro steps
rgds
Marcin

**Comment by leonmflai** [comment]
I encountered the same issue, running the cmdlet "New-AzResourceGroupDeployment" with the provided json file cannot create the VM.

**Comment by polichtm** [comment]
Pls provide the JSON file you are using and the repro steps
rgds
Marcin

**Comment by Fimlore** [comment]
I believe this issue is with the updated LAB5 instruction and JSON files.

**Comment by polichtm** [comment]
Pls provide steps to reproduce the issue and a copy of the template
rgds
Marcin

**Comment by leonmflai** [comment]
> Pls provide the JSON file you are using and the repro steps
> rgds
> Marcin

I download those JSON file from this source:

https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/blob/master/Allfiles/Labs/11/az104-11-vm-parameters.json

https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/blob/master/Allfiles/Labs/11/az104-11-vm-template.json

The repo to install the VM Powershell is following:
New-AzResourceGroupDeployment `
   -ResourceGroupName $rgName `
   -TemplateFile $HOME/az104-11-vm-template.json `
   -TemplateParameterFile $HOME/az104-11-vm-parameters.json `
   -AsJob

**Comment by leonmflai** [comment]
> > Pls provide the JSON file you are using and the repro steps
> > rgds
> > Marcin
> 
> I download those JSON file from this source:
> 
> https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/blob/master/Allfiles/Labs/11/az104-11-vm-parameters.json
> 
> https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/blob/master/Allfiles/Labs/11/az104-11-vm-template.json
> 
> The repo to install the VM Powershell is following:
> New-AzResourceGroupDeployment `-ResourceGroupName $rgName`
> -TemplateFile $HOME/az104-11-vm-template.json `-TemplateParameterFile $HOME/az104-11-vm-parameters.json`
> -AsJob

Sorry I know the reason, I just download the file but not "git clone" thus the files are downloaded with lots of XML encoding. Sorry for my mistake

**Comment by polichtm** [comment]
np - appreciate the follow up
rgds
Marcin
