### ISSUE TITLE
\Allfiles\Labs\04\az104-04-vms-loop-parameters.json has whitespace which creates a file not found error

### ISSUE THREAD

**Issue by bsingh23** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#246]
# Module: AZ-104-MicrosoftAzureAdministrator
#### Step: 3,4

Description of issue:
whitespace in filename "az104-04-vms-loop-parameters .json" which gives error in template.

Error: 
New-AzResourceGroupDeployment: Cannot retrieve the dynamic parameters for the cmdlet. Cannot find path '/home/bharat/az104-04-vms-loop-parameters.json' because it does not exist.

Please remove the extra whitespace from filename.

Cheers
Bharat

**Comment by polichtm** [comment]
updated
rgds
Marcin
