### ISSUE TITLE
lab_04 az104-04-vms-loop-parameters .json has a space in the file name causes script to fail

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#247]
# Module: 04
#### Step: 03

Description of issue 
Allfiles\Labs\04\az104-04-vms-loop-parameters .json has a space in the filename name which causes the script to fail.
 New-AzResourceGroupDeployment `
      -ResourceGroupName $rgName `
      -TemplateFile $HOME/az104-04-vms-loop-template.json `
      -TemplateParameterFile $HOME/az104-04-vms-loop-parameters.json

SHOULD BE
Allfiles\Labs\04\az104-04-vms-loop-parameters.json

![image](https://user-images.githubusercontent.com/24426530/108813658-6ad4e180-75ec-11eb-919f-ec3202c430ca.png)

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
HI David,
that's already updated (#246)
rgds
Marcin
