### ISSUE TITLE
Azure Container Instances - new GUI options

### ISSUE THREAD

**Issue by markturpinMSFT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#25]
# Module: 09b
#### Step: 03

Description of issue

These 3 options on the basics tab have changed and will need to be updated:

Image type | Public
Image name | microsoft/aci-helloworld
OS type | Linux

These options are now:
Image Source
Image
Size
![image](https://user-images.githubusercontent.com/55555818/76695083-cefad180-6637-11ea-9608-2c19cda94515.png)

**Comment by polichtm** [comment]
updated
