### ISSUE TITLE
Lab 5, step 6 reports A parameter cannot be found that matches parameter name 'location1'.

### ISSUE THREAD

**Issue by Fimlore** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#251]
# Module: 00
#### Step: 00

Description of issue

New-AzResourceGroupDeployment:
Line |
   5 |     -location1 $location1 `
     |     ~~~~~~~~~~
     | A parameter cannot be found that matches parameter name 'location1'.

Repro steps:

1. Follow instructions for Lab 5
1. Upload template and parameter files
1. execute powershell command as stated in step 6

**Comment by Fimlore** [comment]
never mind; template and parameter files are updated as well.

**Comment by mordzik** [comment]
I have the same problem as Fimlore:
 New-AzResourceGroupDeployment `
>>    -ResourceGroupName $rgName `
>>    -TemplateFile $HOME/az104-05-vnetvm-loop-template.json `
>>    -TemplateParameterFile $HOME/az104-05-vnetvm-loop-parameters.json `
>>    -location1 $location1 `
>>    -location2 $location2
New-AzResourceGroupDeployment:
Line |
   5 |     -location1 $location1 `
     |     ~~~~~~~~~~
     | A parameter cannot be found that matches parameter name 'location1'.
