### ISSUE TITLE
Unnecessary Steps in Task 7

### ISSUE THREAD

**Issue by markturpinMSFT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#26]
# Module: 10
#### Step: 14,15

Description of issue
These steps ask the student to do the following:
"In the Azure portal, open the Azure Cloud Shell by clicking on the icon in the top right of the Azure Portal.

If prompted to select either Bash or PowerShell, select Bash."

The rest of Task 7 does not use Cloud Shell.  The cleanup task after Task 7 does, but it uses PowerShell.  Seems like these two steps can be removed from Task 7.

**Comment by polichtm** [comment]
updated
