### ISSUE TITLE
MOd 5 Latencey VNET Peering not showing up

### ISSUE THREAD

**Issue by MikeVeschi** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#260]
# Module: 05
## Lab/Demo: 5

After deploying templates to resource groups it takes forever for the peering to show up, 

![image](https://user-images.githubusercontent.com/30813190/109718160-974ca880-7b6c-11eb-8d06-bb5db85075f5.png)

Description of issue

Repro steps:

1.
1.
1.

**Comment by staleycyn** [comment]
This is a known issue and may have to do with deprioritization of Azure passes.  Two suggestions:

1. Use PowerShell - something like this:
# Create virtual network 1.
$vnet1 = Get-AzVirtualNetwork -Name 'az104-05-vnet0' -ResourceGroupName 'az104-05-rg0'
$vnet2 = Get-AzVirtualNetwork -Name 'az104-05-vnet1' -ResourceGroupName 'az104-05-rg1'

# Peer VNet1 to VNet2.
Add-AzVirtualNetworkPeering -Name 'LinkVnet1ToVnet2' -VirtualNetwork $vnet1 -RemoteVirtualNetworkId $vnet2.Id

# Peer VNet2 to VNet1.
Add-AzVirtualNetworkPeering -Name 'LinkVnet2ToVnet1' -VirtualNetwork $vnet2 -RemoteVirtualNetworkId $vnet1.Id

2. Reverse the order when creating the peering. For some reason that occassionally works.

**Comment by MikeVeschi** [comment]
Thank you, Here I also revamped for Mod 6

    $vnet1 = Get-AzVirtualNetwork -Name 'az104-06-vnet01' -ResourceGroupName 'az104-06-rg1'
    $vnet2 = Get-AzVirtualNetwork -Name 'az104-06-vnet2' -ResourceGroupName 'az104-06-rg1'
    $vnet3 = Get-AzVirtualNetwork -Name 'az104-06-vnet3' -ResourceGroupName 'az104-06-rg1'

Peer VNet01 to VNet2.
Add-AzVirtualNetworkPeering -Name 'LinkVnet1ToVnet2' -VirtualNetwork $vnet1 -RemoteVirtualNetworkId $vnet2.Id

Peer VNet2 to VNet01.
Add-AzVirtualNetworkPeering -Name 'LinkVnet2ToVnet1' -VirtualNetwork $vnet2 -RemoteVirtualNetworkId $vnet1.Id

    Reverse the order when creating the peering. For some reason that occassionally works.

Peer VNet01 to VNet3.
Add-AzVirtualNetworkPeering -Name 'LinkVnet1ToVnet3' -VirtualNetwork $vnet1 -RemoteVirtualNetworkId $vnet3.Id

Peer VNet3 to VNet01.
Add-AzVirtualNetworkPeering -Name 'LinkVnet3ToVnet1' -VirtualNetwork $vnet3 -RemoteVirtualNetworkId $vnet1.Id

**Comment by otih** [comment]
We had the same issue last week. We figured out, that this is somehow related to the region load. Last week we hat bad experiences with US regions, but very good with "germanywestcentral".
Please try a different region.

**Comment by dpapkin** [comment]
Another fix is to sign out of the portal, wait a few minutes and then back in. This worked on both students affected. Not all students experienced this issue.

**Comment by dpapkin** [comment]
@MikeVeschi  Thanks for the powershell commands. Very helpful. Is also good to reinforce the concept to the students that they shouldn't rely on the GUI solely, they should get comfortable with command line, as they progress....

**Comment by dpapkin** [comment]
@otih Hi Fabian, what were the 2 regions you used?germanywestcentral and what was the second region? 
Thanks

**Comment by dpapkin** [comment]
> Thank you, Here I also revamped for Mod 6
> 
> ```
> $vnet1 = Get-AzVirtualNetwork -Name 'az104-06-vnet01' -ResourceGroupName 'az104-06-rg1'
> $vnet2 = Get-AzVirtualNetwork -Name 'az104-06-vnet2' -ResourceGroupName 'az104-06-rg1'
> $vnet3 = Get-AzVirtualNetwork -Name 'az104-06-vnet3' -ResourceGroupName 'az104-06-rg1'
> ```
> 
> Peer VNet01 to VNet2.
> Add-AzVirtualNetworkPeering -Name 'LinkVnet1ToVnet2' -VirtualNetwork $vnet1 -RemoteVirtualNetworkId $vnet2.Id
> 
> Peer VNet2 to VNet01.
> Add-AzVirtualNetworkPeering -Name 'LinkVnet2ToVnet1' -VirtualNetwork $vnet2 -RemoteVirtualNetworkId $vnet1.Id
> 
> ```
> Reverse the order when creating the peering. For some reason that occassionally works.
> ```
> 
> Peer VNet01 to VNet3.
> Add-AzVirtualNetworkPeering -Name 'LinkVnet1ToVnet3' -VirtualNetwork $vnet1 -RemoteVirtualNetworkId $vnet3.Id
> 
> Peer VNet3 to VNet01.
> Add-AzVirtualNetworkPeering -Name 'LinkVnet3ToVnet1' -VirtualNetwork $vnet3 -RemoteVirtualNetworkId $vnet1.Id

Here is the commands to verify the peerings

Get-AzureRmVirtualNetworkPeering -VirtualNetworkName az104-05-vnet0 -ResourceGroupName az104-05-rg0
Get-AzureRmVirtualNetworkPeering -VirtualNetworkName az104-05-vnet1 -ResourceGroupName az104-05-rg1

**Comment by polichtm** [comment]
updated
rgds
Marcin
