### ISSUE TITLE
Network Watcher - Connection troubleshoot no resource group

### ISSUE THREAD

**Issue by eender** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#265]
# Module: 06
#### Step: 04

Description of issue
I am on the step, mentioned above, did all the steps. But even after waiting for 1 hour.
The resource group is not shown.

I deployed my the script on the region "'westeurope'".

Repro steps:

1. Waited for 1 hour
1. Deleted all network watcher
1. Recreated network watcher for the selected regions.

**Comment by polichtm** [comment]
updated
rgds
Marcin
