### ISSUE TITLE
Addition to Clean up Steps

### ISSUE THREAD

**Issue by markturpinMSFT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#27]
# Module: 10
#### Step: 04

Description of issue
After going through all module 10 labs and optional labs, I had an additional RG that was created.  Please add a step to delete this recovery group:
"AzureBackupRG_[region]_1"

I'm not sure if it gets created during backup labs or the optional restore labs.  If during the restore portions, then we should include a note "you may also need to delete this resource group"

**Comment by polichtm** [comment]
updated
