### ISSUE TITLE
Module 2 Lab A

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#276]
# Module: 02
#### Step: 09

Description of issue

Module 2 Lab A
In the Clean up resources section, Step 9:  It states "On the Subscriptions blade, right-click the ellipsis icon to the right of the entry representing your Azure subscription and click Move."  
It should not be a right-click, it should just be a click.
![Left Click the Ellipse](https://user-images.githubusercontent.com/16696370/114472372-b3a22300-9bb7-11eb-8600-588ca7a3ccdb.png)

Cheers,
Jeff Smalley MCT
Chicagoville

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
updating

**Comment by azharkhuwaja** [comment]
There is another right click in the last step of Cleaning Resources.

11. Navigate back to the Management groups blade, **right click** the ellipsis icon to the right of the az104-02-mg1 management group and click Delete.
