### ISSUE TITLE
VM Logs Instructions Edit

### ISSUE THREAD

**Issue by markturpinMSFT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#28]
# Module: 11
#### Step: 06

Description of issue
The instructions state "On the az104-11-vm0 - Logs blade, ensure that the Log Analytics workspace you created earlier in this lab is selected in the Choose a Log Analytics Workspace drop-down list and click Enable."

There's no option for choosing the workspace until you click Enable, select the workspace, and then click Enable a second time.
![image](https://user-images.githubusercontent.com/55555818/77350272-78f1f200-6cf9-11ea-849d-868cf13c04d9.png)
![image](https://user-images.githubusercontent.com/55555818/77351118-91aed780-6cfa-11ea-9038-1b5d9c316c27.png)

So the instructions should say:

On the az104-11-vm0 - Logs blade, click Enable and select the Log Analytics workspace you created earlier in this lab from the Choose a Log Analytics Workspace drop-down list, and click Enable again.

**Comment by polichtm** [comment]
updated
