### ISSUE TITLE
Lab 11 Issue

### ISSUE THREAD

**Issue by GitHubGitSum** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#280]
# Module: Implement Monitoring
#### Step: 05

Description of issue
Hi.  I am running into an error whenever I try to add a region to deploy my Azure VMs.  When I input the following command I don't receive an error: $location = '[EastUs]'

But when I try to type in the following command and point the location back to EastUS I get an error:  New-AzResourceGroup -Name $rgName -Location $location

New-AzResourceGroup: The specified location '[EastUS]' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'.

StatusCode: 400

ReasonPhrase: Bad Request

OperationID : f8b8c2d2-8393-4004-9bea-f1dca51e6e1d

I have no issues manually assigning the region by using the following command: -Location "EastUS"

Repro steps:

1.
1.
1.

**Comment by rlthompson904** [comment]
@GitHubGitSum  You'll want to remove the brackets.
$location = 'EastUS' should work for you.

**Comment by polichtm** [comment]
@GitHubGitSum - pls follow up regarding this with your instructor
rgds
Marcin
