### ISSUE TITLE
Lab02A

### ISSUE THREAD

**Issue by GitHubGitSum** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#281]
# Module: 00
#### Step: 06

Description of issue
Hi.  I tried going through the lab exercise and am stuck on step 6.  I have done everything according to the instructions in the Git Hub lab 02a but get the below error:

Remove-AzRoleAssignment -ObjectId '[db4d2d5a-3546-4a36-84ae-ecefdcbdff0c]' -RoleDefinitionName 'Support Request Contributor (Custom)' -Scope $scope

Remove-AzRoleAssignment: The Principal ID '[db4d2d5a-3546-4a36-84ae-ecefdcbdff0c]' is not valid. Principal ID must be a GUID.

The object id was copied from the user role created and I have also tried to use az104-02-aaduser01 and get the same error.  Is this a problem with Azure? Thanks for any help.
Repro steps:

1.
1.
1.

**Comment by rlthompson904** [comment]
@GitHubGitSum  the brackets tripped you up on this one too.  If you remove the brackets from around the guid it should work. 
The square brackets themselves are special characters in Powershell that typically denote arrays. You will want the guid to be passed as a string(surrounded by quotes).

**Comment by polichtm** [comment]
@GitHubGitSum 
pls follow up with your instructor if you need additional help regarding this
rgds
Marcin

**Comment by azharkhuwaja** [comment]
I just removed the "custom" and it works.

$scope = (Get-AzRoleAssignment -RoleDefinitionName 'Support Request Contributor').Scope

Remove-AzRoleAssignment -ObjectId 'c4e88c99-20d9-4ad5-88c9-25deea41b8c6' -RoleDefinitionName 'Support Request Contributor' -Scope $scope

**Comment by GitHubGitSum** [comment]
Thank you so much for this!  I will try to apply it to the excercise.

LP

**Comment by GitHubGitSum** [comment]
Thanks rlthompson904.  I think this works.  I'll verify again once I have
some time to sit down and play with this.

LP
