### ISSUE TITLE
AZ-104-MicrosoftAzureAdministrator/Instructions/Labs/LAB_11-Implement_Monitoring.md

### ISSUE THREAD

**Issue by GitHubGitSum** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#282]
# Module: 00
#### Step: 6

Description of issue
When I run this task as is with single quotes, Azure cloudshell states -TemplateFile $HOME/xxxxxx.json is not a recognized name
as well as AsJob 
Repro steps:

PS /home/l> New-AzResourceGroupDeployment '
>> -ResourceGroupName $rgName '
>> -TemplateFile $HOME/az104-11-vm-template.json '
>> -TemplateParameterFile $HOME/az104-11-vm.parameters.json '
>> AsJob
New-AzResourceGroupDeployment: A positional parameter cannot be found that accepts argument '
-ResourceGroupName $rgName '.
-TemplateFile:
Line |
   3 |  -TemplateFile $HOME/az104-11-vm-template.json '
     |  ~~~~~~~~~~~~~
     | The term '-TemplateFile' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
AsJob:
Line |
   5 |  AsJob
     |  ~~~~~
     | The term 'AsJob' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Also, when running New-AzResourceGroupDeployment without quotes, the syntax changed but cloudshell is saying it could not see part of the path, even though the file is saved:

PS /home/l> New-AzResourceGroupDeployment

cmdlet New-AzResourceGroupDeployment at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
ResourceGroupName: $rgName
TemplateFile: $HOME/az104-11-vm-template.json
New-AzResourceGroupDeployment: Could not find a part of the path '/home/l/$HOME/az104-11-vm-template.json'.
PS /home/l> dir

    Directory: /home/l

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
l----           4/24/2021  1:45 PM                clouddrive -> /usr/csuser/clouddrive
-----           4/17/2021  5:15 PM            449 az104-02a-customRoleDefinition.json
-----           4/20/2021 12:31 AM            389 az104-06-vms-loop-parameters.json
-----           4/20/2021 12:30 AM           9867 az104-06-vms-loop-template.json
-----           4/19/2021  1:47 PM           1174 az104-11-vm-parameters.json
-----           4/19/2021  1:48 PM           8577 az104-11-vm-template.json
-----           4/19/2021  2:25 PM          39710 azure_regions.json

**Comment by polichtm** [comment]
Pls contact me directly at liveid223@outlook.com
rgds
Marcin
