### ISSUE TITLE
Lab 7, Task 2, Step 2, v2 and GRS with checkbox

### ISSUE THREAD

**Issue by TammySmithMCT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#287]
# Module: 07
#### Step: 02

Description of issue
Account kind was removed and RA-GRS is now configured by selecting GRS and enable read access checkbox 

Please change the following:
Remove:  Account kind | Storage (general purpose v1)
Change:  Replication | Read-access geo-redundant storage (RA-GRS)
and remove steps 7-9, given the storage account is v2 and can not be upgraded to v2

To:  

Replication | Geo-redundant storage (GRS)
Enable Make read access to data available in the event of regional unavailability. 

![sagrs](https://user-images.githubusercontent.com/11367710/116440196-3b299c00-a81e-11eb-846b-d518b7cfbc1d.PNG)

**Comment by polichtm** [comment]
updated
