### ISSUE TITLE
Module 2, lab 02a

### ISSUE THREAD

**Issue by LionelShaul** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#289]
# Module: 002
#### Step: 08

Description of issue

Repro steps:

1.  The instructions as listed do not work.  There are no ellipsis to the right of the subscription.
2.  Instead, select the root Management Group, Select the **0** hypertext link under child subscriptions.
3. Then click the **+add** hypertext link.
4. In the pop up window, within the pull down bar, select your subscription to move your subscription underneath the Root Management Group.
5. Now you can proceed with deleting the Subordinate Management Group.
1.

**Comment by polichtm** [comment]
udpated
rgds
Marcin
