### ISSUE TITLE
Mod 11 Instruction Edit

### ISSUE THREAD

**Issue by markturpinMSFT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#29]
# Module: 11
#### Step: 03, 11

Description of issue
Sample Queries (toolbar button) has been renamed Example Queries
![image](https://user-images.githubusercontent.com/55555818/77461743-3f37ee80-6dc0-11ea-91f9-6d48ffde886b.png)

"Click Sample queries in the toolbar"
replace with
"Click Example queries in the toolbar"

**Comment by polichtm** [comment]
updated
