### ISSUE TITLE
Incorrect answer in review questions segment

### ISSUE THREAD

**Issue by DanielMcKinney-LODS** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#290]
# Module: 05
## Review Questions 

Description of issue:  Question 1  - " Which of the following is NOT true about VNet Peering?".  As you can see in the image below, all of these statements are true.  The problem is that we're looking for a statement that is NOT true.  

The first statement: " The virtual networks can exist in any cloud region " which is CORRECT. 

The statement should be changed to something like " The virtual networks can only exist in the same azure cloud region. " or something along those lines, so that the statement is INCORRECT. 

![image](https://user-images.githubusercontent.com/62155069/117132456-7b31d700-ad68-11eb-9b0e-215644aad537.png)

**Comment by polichtm** [comment]
Hi Daniel,
this repo is dedicated to the lab related topics. Pls raise this on the MCT forum
rgds
Marcin

**Comment by staleycyn** [comment]
The next update of AZ-104 is 21 May. All the questions are being reviewed and this one will be fixed. Thanks for the feedback.
