### ISSUE TITLE
Azure Pass / Region changes affecting multiple deployments

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#292]
# Module: Multiple
## Lab/Demo: Multiple

Description of issue
I delivered AZ-104 3 weeks ago with no issues and am again delivering it this week, During this weeks delivery, my students encountered an issue deploying the VMs for Lab 4. 

After some digging, I discovered that either the Azure Passes may have changed in the sizes they can provision OR some regions may be limiting sizes for Azure Passes.

After running a Get-AzComputeResourceSku for 2 locations (australiaeast and australiasoutheast) where the restriction does not equal 'NotAvailableForSubscription', I found that no virtual machines can be provisioned in australiasoutheast on Azure Pass Accounts and in australiaeast, you can only provision the below.

![image](https://user-images.githubusercontent.com/12164329/117095712-6ece6e00-adaa-11eb-859c-b76a92b7d34f.png)

I know this isn't an issue with the lab steps per se, however, there may be other regions that encounter this issue, so I figured I would post this here.

**Comment by craigbeeremct** [comment]
I start almost every Azure class by trying to create VMs in various regions, to work out which we can use.

West US 2 and Central US usually work for us (with the benefit that both are zone-capable regions).

After my teach of WS-050 last week, I came up with the following.

```powershell
$Location = "West US 2"
#$Location = "Central US"

Get-AzVMUsage -Location $Location `
| Select-Object @{l="ResourceType";e={$PSItem.Name.LocalizedValue}}, CurrentValue, Limit `
| Where-Object { $PSItem.ResourceType -in "Standard DSv3 Family vCPUs", "Standard FSv2 Family vCPUs", "Total Regional vCPUs" }

#Get-AzComputeResourceSku -Location $Location | gm

Get-AzComputeResourceSku -Location $Location `
| Where-Object { ($PSItem.Family -in "standardDSv3Family", "standardFSv2Family" ) -and ( $PSItem.ResourceType -eq "virtualMachines" ) } `
| Sort-Object Family, Name `
| ft Name, Family, @{l="Restriction";e={$PSItem.Restrictions.ReasonCode -join ", "}}
```

**Comment by WigF1** [comment]
Thanks, Craig. 

Do you have the students run that? Using my MCT Azure benefit, I can create in any region, so the output I pasted above was from a students session. 

Or do you also use an Azure Pass and not your MCT benefit?

**Comment by ITBlandMCT** [comment]
Steve, MCTs can requests Azure Passes for themselves (if teaching an Azure class) here: https://vouchers.cloudapp.net/AzurePass/
That, and other MCT benefits from Microsoft are listed here: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE23o0Z 
I try to use the Azure Pass for demos in class so I can see if there are any restrictions that the students might run into.
Thanks for the quick script @craigbeeremct , that's really handy!

**Comment by WigF1** [comment]
Yeah, the only downside to that is the 'hurry up and wait' while things provision.

I prefer to have established app services, compute, storage etc.

Can the azure pass be used for the same MSA?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by polichtm** [comment]
Pls continue if needed on the MCT forum
rgds
Marcin
