### ISSUE TITLE
Not all azurepass have permission to add another managment group. Module 2a - Managment Subscriptions and RBAC

### ISSUE THREAD

**Issue by JuanQuijano** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#295]
# Module: Module 02 - Governance and Compliance
#### Step: 06

Description of issue
Not all azurepass have permission to add another managment group

We waiting above 20 minutes, and never show the new managment group.

Better change the az104-02a-customRoleDefinition.json file an quit the ManagementGroup AssignableScopes line. Like this:

{
   "Name": "Support Request Contributor (Custom)",
   "IsCustom": true,
   "Description": "Allows to create support requests",
   "Actions": [
       "Microsoft.Resources/subscriptions/resourceGroups/read",
       "Microsoft.Support/*"
   ],
   "NotActions": [
   ],
   "AssignableScopes": [
       "/subscriptions/<subscriptionId>"
   ]
}

And assign the Role at Subscription scope, not at ManagmentGroup scope, and the lab run fine.

**Comment by polichtm** [comment]
updated
rgds
Marcin
