### ISSUE TITLE
Permission Error Cloud Slice Labs Module 10

### ISSUE THREAD

**Issue by zzenonn** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#296]
Not sure if this is the right place to post this, but this issue is specific to LODS cloud slice labs.

# Module: 10
##### Step: 4

Description of issue:  Create Storage Failed

Repro steps:  When my students select the Azure Cloud Shell icon at the very start of the lab, it prompts them to select Bash or PowerShell.  After selecting PowerShell they have a choice to click "Create storage" button or "Close button".  Once they select the "Create storage" button it fails at this point with an error message "Storage creation failed"  Error 403.  "The 
 client LabUserxxxxxx@cloudslice.onmicrosoft.com.....does not have authorization to perform action (please see attached screenshot).

This happened to all students in an AZ-104 class today May 12, 2021 around 4:10pm GMT+8.

**Comment by berkenbrack** [comment]
Hello Miguel, thank you very much for bringing this to our attention.   Please perform the following steps:

1.  In Azure Cloud Shell, select Powershell.
2.  Click show advanced settings. 
3. Under resource group, leverage the existing resource group (use existing should be selected). 
4. For Storage account and File share, please create a new one on each with a naming convention of your choice. 
5. Click create storage. 

I have added clarification to the instructions as well to avoid future confusion. Thank you again for brining this to our attention.

**Comment by polichtm** [comment]
Pls use gtlsupport@learnondemandsystems.com for any LODS-specific platform related issues.
Considering that this one has been resolved, I'll be closing it
rgds
Marcin
