### ISSUE TITLE
Mod 5 lab: Implementing Intersite Connectivity

### ISSUE THREAD

**Issue by swthibodeau** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#297]
# Module: 05
#### Step: 06

Description of issue: When the PowerShell script is run for the ResourceGroupDeployment, it does create the Vnets and VM's however they get created all in one Resource Group (based on the $rgName from step 5) They need to be distributed across the three RG's. So, does that mean that the PowerShell script needs to be run three separate times to get VM's into each of the RG's?

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
Would you mind clarifying why the virtual networks need to be "distributed across the three RG's"?
rgds
Marcin

**Comment by swthibodeau** [comment]
Marcin,
Hello and thank you for reaching out. After more trial and effort with the lab, I came to the conclusion that the lab instructions were just fine, and the culprit of my confusion and frustration was that the lab graphic in the PPT slide deck for Mod 5 is incorrect! The diagram in the MCT slide deck shows two regions, however it shows the resources in three separate RG’s: RG0, RG1 and RG2. So my assumption was that the PowerShell script was going to replicate what was shown in the PPT slide. 

I was able to work through the lab just fine after realizing that everything was created in the one RG and all worked as expected, so feel free to close this ticket. 

Regards,

Scott

**Comment by polichtm** [comment]
Hi Scott,
appreciate the clarification
rgds
Marcin

**Comment by staleycyn** [comment]
The Module 05 PPT lab diagram will be corrected in the next course update, 21 May. The MCT Courseware forum has a thread with a more complete list of fixes.

**Comment by swthibodeau** [comment]
Thank you.
