### ISSUE TITLE
Mod 7 Ex1 various steps Storage account changes

### ISSUE THREAD

**Issue by MikeVeschi** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#298]
# Module: 07
#### Step: 01

Mod 7 Ex1 Task2 Step 1 Change +Add to +New

Mod 7 Ex1 Task2 Step 7
Change Settings to Data Management

Step 8 Should read Settings/Configuration Blade

Task 3 Step 1 Should read Click Data Storage / Containers

Task5 Step should read Data Storage / File Shares

Also changes to type not listed in courseware.
interface changes, No more gen 1 account now file share and container separate accounts and blob and standard gen v2 types

**Comment by staleycyn** [comment]
Please be more specific on which slides in the courseware need to be changes. Thanks.

**Comment by swthibodeau** [comment]
Hello,

 

It looks like slide 32 in Mod 5. The lab network diagram:

It describes the resources being deployed into three different resource groups.

Regards,

Scott

**Comment by MikeVeschi** [comment]
In Mod 7 Slide 7 the kinds should reflect the new kinds in the article here:

Types of storage accounts
https://docs.microsoft.com/en-us/azure/storage/common/storage-account-overview

**Comment by staleycyn** [comment]
Both the Mod 05 lab slide and the Mod 07 Account Kinds topics will be updated for the 21 May release. There is a MCT Courseware Forum thread with more details. You can reply to the broader audience there if you have something else. Thanks for the feedback.

**Comment by polichtm** [comment]
The lab steps have been updated
rgds
Marcin

**Comment by chercm** [comment]
hi i kept getting error when trying to run this command : New-AzResourceGroupDeployment `
   -ResourceGroupName $rgName `
   -TemplateFile $HOME/az104-07-vm-template.json `
   -TemplateParameterFile $HOME/az104-07-vm-parameters.json `
   -AsJob

The job kept failing even though i have followed the instructions
