### ISSUE TITLE
Module 4, Exercise 1, Task 4 - RDP to VM0 fails but works fine for VM1

### ISSUE THREAD

**Issue by tncrazvan** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#299]
# Module: 04
#### Step: 12 and 13

Description of issue

As far as I can tell, from the previous tasks in this same lab, the Network Interface Card configuration called ```az104-04-nic0``` is relative to the Virtual Machine called ```az104-04-vm0``` and the NIC ```az104-04-nic1``` is relative to the VM ```az104-04-vm1```.

So TLDR;
NIC0 --> VM0
NIC1 --> VM1

The association on task 4 step 11 is made with the NIC1 (thus VM1).
However in the next two steps of task 4, step 12 and 13, the guide indicates to connect to VM0, which has no association with the inbound security rules that allow remote connection (these rules are set on task 4 step 9).

That being said the RDP connection works twards VM1, because the association has been made for NIC1.

Here's a preview of it working and pinging VM0:
![image](https://user-images.githubusercontent.com/6891346/118641439-6f1f2e00-b7da-11eb-8705-4d4c468ab692.png)

Repro steps:

1. Follow all tasks and steps untill task 4 step 14
1. Try connect to VM0 as suggested in task 4 step 14.

**Comment by polichtm** [comment]
The step 11 states the following:
Associate the az104-04-nsg01 network security group with the **az104-04-nic0** and az104-04-nic1 network interfaces.

Rather than:
"The association on task 4 step 11 is made with the NIC1 (thus VM1)."

rgds
Marcin
