### ISSUE TITLE
LAB_02a_Manage_Subscriptions_and_RBAC.md

### ISSUE THREAD

**Issue by TommyKobber** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#30]
# Module: 02
#### Step: 00

Rewrite to portal

Now that it's possible to create Custom roles in the portal it might be a good idea to rewrite the task to be done there instead of a json script

**Comment by renaudwangler** [comment]
Hello !
I Don't fully agree : the GUI for creating roles in the portal is currently in preview.
So it may be mentioned in the lab/course but I'm not a big fan of using "preview" items in the labs. I think this is not the right message to bring to the students : preview must not be used in production environments...

**Comment by TommyKobber** [comment]
@renaudwangler I didn't see in the portal that it was still in preview, but I see it in the documentation. I don't see it as a problem using preview features in the labs, as long as it is mentioned at some point that it is a preview. But I'll leave it to the moderator to decide

**Comment by polichtm** [comment]
Hi Tommy,
I'd agree with Renaud. As far as I can tell, there are at least three potential issues with using a GUI-based preview feature (in particular, if the corresponding functionality is already GA via other means):
- the possiblity that GUI will change is obviously considerably higher (which, in turn, is likely increase maintenance overhead and lead to confusion when following lab instructions).
- one of the purposes of the labs is to prepare students for the exam. As far as I understand, preview features are, in general, excluded from the exam. Students should, however, be familiar with the corresponding GA features.
- another purpose of the labs is to prepare students for real-world, production scenarios. Preview features should not be used in such scenarios.
Hope this makes sense - but I'll gladly consider counter-arguments
rgds
Marcin

**Comment by TommyKobber** [comment]
@polichtm @renaudwangler Hi there. I agree with your arguments, so I withdraw my suggestion. I still wonder though why it doesn't appear in the portal that this is a preview feature. Usually it does.
Best regards, Tommy

**Comment by polichtm** [comment]
Hi Tommy,
appreciate the speedy response
rgds
Marcin
