### ISSUE TITLE
Azure Staging and Production 

### ISSUE THREAD

**Issue by GitHubGitSum** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#301]
# Module: Az104-MicrosoftAzureAdministrator
#### Step: 01-04

Description of issue
Staging and Production pages are not swapped
Repro steps:

1. Navigate back to the blade displaying the production slot of the web app.

2. In the Deployment section, click Deployment slots and then, click Swap toolbar icon.

3. On the Swap blade, review the default settings and click Swap. (Source is the staging slot, destination is production slot fyi)

4. Click Overview on the production slot blade of the web app and then click the URL link to display the web site home page in a new browser tab. (Web page displays original production page, not Hello World! page)

**Comment by polichtm** [comment]
Each slot has its dedicated URL.
What page are you seeing when you navigate directly to the URL of the staging slot?
rgds
Marcin

**Comment by GitHubGitSum** [comment]
Hi.  The page on the staging slot opens up a link to to the **Hello World!** page.  But step 5 indicated Overview on the production slot blade should show **Hello World!** after the swap.

5. Verify the default web page has been replaced with the Hello World! page.

**Comment by polichtm** [comment]
Unfortunately I cannot reproduce it. Is this just you - or do your students are seeing the same behavior?
rgds
Marcin

**Comment by GitHubGitSum** [comment]
I discussed this issue with one of the people in the course and we managed to run through the instructions no issues this time.  Copied the username and password as instructed and noticed afterwards that the production website reproduce the Hello World! page.  Please go ahead and resolve.  Thank you for looking into this.
