### ISSUE TITLE
Useless file names vs Useful file names

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#306]
# Module: ALL

I'm gonna keep filing issues each and every time I have I have to take time to update file names.

Prior to the update, my PowerPoint file is named something like:
   AZ-104T00A-06-NetTrafficMgmt.pptx

After the update, I get file names like:
  AZ-104T00A-ENU-PowerPoint_06.pptx

- [ ] I know what language I'm teaching in. It doesn't change mid-course.
- [ ] The point of file extensions ("pptx") is to know what type of file we have. It is redundant and useless to include "PowerPoint" in the name.
- [ ] What's missing is any indication of what the file might contain.

Yes, I can go look it up. Yes, if this is the only course I ever teach, I might come to memorize the name of every module. But it's not and I don't.

I have been previously told this is needed of "consistency" and "build purposes". That might be true... I suppose... if it's true that the world's largest software company doesn't have a reasonable build process... but designing and publishing for the convenience of internal build process over over usability for paying customers (including MCTs) is misguided.

**Comment by staleycyn** [comment]
AZ-104 uses the required file naming convention as all other Microsoft courses. To help our instructors learn the course organization AZ-104 also provides a course outline (AZ-104T00A-ENU-CourseOutline), a visual representation of the schedule (AZ-104T00A-ENU-PowerPoint_00), a syllabus page (SkillPipe Welcome section), and list of the modules in the Trainer Prep Guide (AZ-104T00A-ENU-TrainerPrepGuide).

**Comment by boomalator** [comment]
This comment does not address the concern.

The "convention" is unhelpful and should be changed. It conveys only duplicate and not useful information. Directing me to go to another resource to look up the contents of a file is silly.

Might as well just name files with GUIDs. (Oh wait, that was the "convention" for old MSDN DVDs, wasn't it?)

________________________________

**Comment by polichtm** [comment]
Pls raise this issue on the MCT forum
rgds
Marcin
