### ISSUE TITLE
Are lab recordings supposed to be available?

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#307]
I receive an error accessing lab recordings:

![image](https://user-images.githubusercontent.com/17992669/121088355-da896980-c7a2-11eb-886c-929d2a45b120.png)

**Comment by staleycyn** [comment]
From the MCT Courseware Forum - 
The Demo lab links are no longer working and the team has made a decision to archive the repo.  - MicrosoftLearning/Lab-Demo-Recordings: Recordings and Demos of Labs (github.com). Going forward, there will be no new videos as this is something that the team can no longer sustain.

**Comment by boomalator** [comment]
> From the MCT Courseware Forum -
> The Demo lab links are no longer working and the team has made a decision to archive the repo. - MicrosoftLearning/Lab-Demo-Recordings: Recordings and Demos of Labs (github.com). Going forward, there will be no new videos as this is something that the team can no longer sustain.

Also from the Courseware Forum:

"You have reached Microsoft Certified Trainer Support page on where we can provide assistance for the exams and certifications that can be found on Microsoft Learning website including MCT Enrollment assistance.

Regarding your access to the Lab Demos for AZ-104, please contact GitHub support directly as they can further assist and check on the error you have encountered."

June 3, from one of the "moderators" -- https://trainingsupport.microsoft.com/en-us/tcmct/forum/tcmct_courses-tcmct_coursecont/not-being-able-to-access-az-104-azure/34c47126-1507-4eac-b47a-f487252ff21b

**Comment by staleycyn** [comment]
Your response from Support was on 3 June. The video retirement posting on the MCT Forum is from 4 June. Support should now convey the new messaging.

**Comment by polichtm** [comment]
If you have any additional questions regarding this topic, pls raise them on the MCT forum
rgds
Marcin
