### ISSUE TITLE
Kubernetes Cluster

### ISSUE THREAD

**Issue by GitHubGitSum** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#309]
# Module: Az-104-MicrosoftAzureAdministrator
#### Step: 02

Description of issue

Instructions do not say what to do for availability zone when creating Kubernetes cluster.

**Comment by polichtm** [comment]
The instructions state:
On the Basics tab of the Create Kubernetes cluster blade, specify the following settings **(leave others with their default values):**
pls simply use the default value
rgds
Marcin
