### ISSUE TITLE
Where is the Student Handbook ?

### ISSUE THREAD

**Issue by garymitchell** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#31]
What about changes to the student handbook?
We will review the student handbook on a quarterly basis and update through the normal MOC release channels as needed.

**Comment by staleycyn** [comment]
This course officially releases 27 March. At that time the student handbook will be available on the MCT Download Center. Is that what you are asking?

**Comment by garymitchell** [comment]
Yes and Thanks …
