### ISSUE TITLE
Unable to connect to AKS

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#310]
# Module: 10
## Lab/Demo: 10

Description of issue

Unable to connect to AKS. See screenshot. 
Tested with the "connect" info from the portal as well.

![image](https://user-images.githubusercontent.com/17992669/121585588-fcc3f700-c9ef-11eb-83f3-63c65f1ef882.png)
![image](https://user-images.githubusercontent.com/17992669/121585596-0188ab00-c9f0-11eb-882a-a230193eef06.png)

**Comment by polichtm** [comment]
Unfortunately I cannot reproduce this issue.
Was this something that affected multiple students?
rgds
Marcin

**Comment by boomalator** [comment]
We did that particular lab as a group exercise/demo. I did not hear anything one way or another from students. 

As I mentioned in my report, I don't know where the issue may have been. Perhaps it was something transient or something bizarre in that particular tenant. (But on the other hand, I know I wasn't making it up. :) )

Thank you for checking.

**Comment by polichtm** [comment]
You're welcome...
rgds
Marcin
