### ISSUE TITLE
Incorrect name for image

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#311]
# Module: 09

Instructions say:

````
Image Source	Quickstart images
Image	microsoft/aci-helloworld (Linux)
````

Actual name in screenshot.

![image](https://user-images.githubusercontent.com/17992669/121585900-56c4bc80-c9f0-11eb-90bf-2e9b332de8f0.png)

**Comment by polichtm** [comment]
updated
