### ISSUE TITLE
Incorrect label for +New (+Create)

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#312]
# Module: 09

Instructions say:
````
In the Azure portal, search for locate Container instances and then, on the Container instances blade, click + New.
````

I swear there is a dedicated team at Azure who randomly changes + Add, + Create, and + New across the platform on a weekly basis to ensure that when one page gets updated to + Add, another page must get changed to + Create, and so on.

(Secondly, please note that "blade" is not a term found in the UI and is not understood by most students, especially outside of English-speaking North America and Europe).

![image](https://user-images.githubusercontent.com/17992669/121586108-8247a700-c9f0-11eb-908b-9ffa6f86cf9f.png)

**Comment by craigbeeremct** [comment]
I feel your pain with the "New", "Add" and "Create"! I was just ranting about this in class last week.

As for "blade", it is a technical term. If you hover the mouse over that pushpin, it says "Pin blade to dashboard." I'm just happy that Microsoft dropped the term "journey".  :-) 

Should we use the term "pane" instead? The [Microsoft Style Guide ](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/b/blade )says "Use blade to refer to a pane in the Azure portal. "

**Comment by boomalator** [comment]
If the UI now includes "Blade", then the UI wins. :) (For a long time "blade" and "tenant" were not in the product, just used a lot.)

I think most students new to Azure just say "page", as it's not always clear whether a blade is part of the page or the whole page. 

Some frameworks for SPAs use "drawer" for something that slides in and closes, but I think that would be worse.

**Comment by polichtm** [comment]
Appreciate the feedback. Pls feel free to submit a PR if you have a recommended approach to addressing these inconsistencies. In the meantime, I gather that making your students aware of these inconsistencies might minimize their potential confusion
rgds
Marcin

**Comment by dpapkin** [comment]
Hi,

I think I can shed some light on the mystery of the random changing New /  Add./ Create


This has to do with language/region settings of the users computer.

I had raised this issue last year.

David Papkin
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: BP ***@***.***>
Sent: Friday, 11 June 2021, 03:37
To: MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator
Cc: Subscribed
Subject: [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator] Incorrect label for +New (+Create) (#312)


Module: 09

Instructions say:

In the Azure portal, search for locate Container instances and then, on the Container instances blade, click + New.


I swear there is a dedicated team at Azure who randomly changes + Add, + Create, and + New across the platform on a weekly basis to ensure that when one page gets updated to + Add, another page must get changed to + Create, and so on.

(Secondly, please note that "blade" is not a term found in the UI and is not understood by most students, especially outside of English-speaking North America and Europe).

[image]<https://user-images.githubusercontent.com/17992669/121586108-8247a700-c9f0-11eb-908b-9ffa6f86cf9f.png>
