### ISSUE TITLE
Instructor demos not supported on CloudSlice

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#313]
While this is a LODS issue, much more so than a content issue, course developers and instructors should be aware that LODS has stated that Cloud Slice "does not support Instructor demos". (As per Sharon, June 9, in Ticket 324250).

**Comment by berkenbrack** [comment]
Hello:

Please note this repository is intended to report Microsoft content issues directly and not ALH specific issues - however we happen to see this and wanted to provide clarity. We (LODS) do allow instructor prep in these lab environments but within context of lab environment/instruction authoring. These restrictions we have put in place are  to prevent nefarious activities and limit the scope of deployments to the instructions as authored. We do encourage MCT's to use their provided Azure pass credit, which would allow for additional deployments to be demonstrated, if they fall outside of the content as authored. This can be leveraged in the same lab environment but would require logging into the proper account (MCT account with Azure credit). Apologies for any confusion in the ticket reply and we will pass this message along internally to avoid future confusion.

**Comment by polichtm** [comment]
Pls follow up regarding this on the MCT forum
rgds
Marcin
