### ISSUE TITLE
Kubernetes cluster name 

### ISSUE THREAD

**Issue by GitHubGitSum** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#315]
# Module: 00
#### Step: Task 2 Kubernetes cluster name and Task 3 Kubernetes service blade /node pools blade

Description of issue

Naming of the the Kubernetes cluster name in task 2 and 3 are different.  Task 2 has the name az104-9c-aks1, Task 3 has the name az104-9c-aks1.  When calling AKS_CLUSTER='aks-09c-aks1' cloudshell can not find it.

**Comment by polichtm** [comment]
Could you clarify where exactly you are seeing the reference to 'aks-09c-aks1' ?
rgds
Marcin

**Comment by GitHubGitSum** [comment]
Please look at Task 2 Step 2, then compare this to Task 3 step 6.  I receive an error that  az104-09c-rg1 does not exist, even though it was created in the previous steps.

**Comment by polichtm** [comment]
So here is the screenshot of Exercise 1 Task 2 Step 2
![image](https://user-images.githubusercontent.com/10284906/122215756-97ea2000-ce79-11eb-8ffe-7048e488f711.png)

And here is a screenshot of Exercise 1 Task 3 step 6
![image](https://user-images.githubusercontent.com/10284906/122215800-ac2e1d00-ce79-11eb-85e4-98cc8f6d6d50.png)


Pls clarify what specifically you are referring to

rgds
Marcin

**Comment by polichtm** [comment]
Closing due to lack of response
