### ISSUE TITLE
Step 6 isn't resolving even though all the above steps have completed successfully. 

### ISSUE THREAD

**Issue by abduttawab1981** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#331]
# Module: AZ-104
#### Step: 04

Description of issue
Step 6 isn't resolving even though all the above steps have completed successfully. 
Check is not returning anything even after a long time (approx. 1 hour)
Stuck and Checking connectivity...
![az104-lab6-task3-step4](https://user-images.githubusercontent.com/87466808/126076637-01889051-52b0-4e81-8dd6-3cbe1cd355e5.jpg)

Repro steps:

1.
1.
1.

**Comment by staleycyn** [comment]
Please ask your instructor for assistance. This repo is for students attending an instructor-led class.
