### ISSUE TITLE
Lab 02a - Manage Subscriptions and RBAC

### ISSUE THREAD

**Issue by angelyk** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#333]
# Module: 00
#### Step: 00

Description of issue
The instructions to create the lab virtual machine are not added in the instructions of the labs 
Repro steps:

1.
1.
1.

**Comment by staleycyn** [comment]
Please ask your instructor on how to access your classroom lab machine.

**Comment by angelyk** [comment]
Thank you for your response.

I’m self-studying, and I found this lab repository on google. I’ll investigate how to generate the virtual lab machine to continue working.

Best regards.

Angelica Rivas
Senior Systems Engineer
Resource Manager
MX Security Competency
 Email: ***@***.******@***.***>
Guadalajara,  Mexico  epam.com<http://www.epam.com>


CONFIDENTIALITY CAUTION AND DISCLAIMER
This message is intended only for the use of the individual(s) or entity(ies) to which it is addressed and contains information that is legally privileged and confidential. If you are not the intended recipient, or the person responsible for delivering the message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. All unintended recipients are obliged to delete this message and destroy any printed copies.
