### ISSUE TITLE
Multiple node pools get created if you do not change the scale method option

### ISSUE THREAD

**Issue by alextoma89** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#334]
# Lab/Demo: 09c
#### Step: 2

Description of issue
Scale method- Select **manual** and enter **1**.
It is specified in Step 3 of Task 3 "On the az104-9c-aks1 - Node pools blade, verify that the cluster consists of a **single** pool with **one** node. Leaving the Scale method option on Automatic will create more than one node.

**Comment by FireyJoe** [comment]
I tested this. The instructions don't say anything about availability zones and probably need updated. 

You need to uncheck all the zones on the "Basics" tab when creating the cluster. After this, I got one pool with one node. You can leave "Scale Sets" enabled at this point (although the Azure interface will allow you to turn it off if you uncheck all the Availability Zones), and will still get a single one-node pool. 

I made a pull request that adds unchecking all the availability zone boxes. #335
