### ISSUE TITLE
There is a typo within the Module 11 lab in Task 7, Step 2 - The name of the vm is not correct

### ISSUE THREAD

**Issue by ac-cmuszak** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#336]
# Module: 11
#### Step: 02

Description of issue

VM is named "a104-11-vm0" instead of "a**z**104-11-vm0"

**Comment by staleycyn** [comment]
The two names you have provided are identical. Can you clarify what is the issue?

**Comment by ac-cmuszak** [comment]
I’m not in front of my computer, but if I remember correctly, the typo is a104… instead of az104… basically it is just missing the “z” in the VM name in that step.


COREY MUSZAK
Enterprise Engineer, Escalations
Advanced Technology Solutions

All Covered, IT Services from Konica Minolta
Office: (212) 294-6483
www.allcovered.com<http://www.allcovered.com>

________________________________
