### ISSUE TITLE
no ellipsis icon 

### ISSUE THREAD

**Issue by Sbekemeier2487** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#338]
# Module: 02
#### Step: 00

Description of issue
i cant change mt root tenant back from az104-02-mg1 on the clean up resources 

Repro steps:

1.
1.
1.

**Comment by Sbekemeier2487** [comment]
no ellipsis sign on my version you just have to right click on the az104-02-mg1 and then the move/delete option pops up.

**Comment by staleycyn** [comment]
Please ask your instructor for assistance. This repo is for students attending an instructor-led class.
