### ISSUE TITLE
Lab 2a - Cleanup resource - step 5 - Not able to remove role assignment

### ISSUE THREAD

**Issue by kiran3490** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#342]
# Module: 02
#### Step: 05

Description of issue

Not able to remove role assignment

due to this not able complete step 6.
Remove-AzRoleDefinition -Name 'Support Request Contributor (Custom)' -Force

Repro steps:

1. Tried steps as per suggestion but not working.

![image](https://user-images.githubusercontent.com/6681850/127744959-334d8745-5175-4207-8a92-555d39971566.png)

**Comment by kiran3490** [comment]
Please suggest manual process using azure portal as an alternative solution.

**Comment by staleycyn** [comment]
These instructions are for use in a Microsoft class. Are in class? Do you have access to the instructor?

**Comment by kiran3490** [comment]
Yes, I attended az-104 training last week, but i am doing labs as per my convenient time and I encounter this.

**Comment by jbpaux** [comment]
I had the same issue with my students today. Scope variable is null, I asked them to use the portal to delete the assigment
