### ISSUE TITLE
Issue with Lab 5

### ISSUE THREAD

**Issue by masifshabir** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#355]
# Module: 05
#### Step: 06

Description of issue
While trying to run below command.  I am getting error.  I have uploaded the required files.

 New-AzResourceGroupDeployment `
>>    -ResourceGroupName $rgName `
>>    -TemplateFile $HOME/az104-05-vnetvm-loop-template.json `
>>    -TemplateParameterFile $HOME/az104-05-vnetvm-loop-parameters.json `
>>    -location1 $location1 `
>>    -location2 $location2
New-AzResourceGroupDeployment:
Line |
   5 |     -location1 $location1 `
     |     ~~~~~~~~~~
     | A parameter cannot be found that matches parameter name 'location1'.

Repro steps:

1.
1.
1.

**Comment by staleycyn** [comment]
This repo is for Microsoft Certified Instructors that are teaching classes. If you are having issues with the labs please ask your instructor.
