### ISSUE TITLE
Templates cannot be used with Free Azure Trial

### ISSUE THREAD

**Issue by hieronymussheesh** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#369]
# Module: 
#### Step: 06

Description of issue
The free azure trial has the limitation of 4 vCPUs per Region.

Workaround/ alternate Template for Free Trials: use VM Size Standard_D1_v2 instead of Standard_D2_v2

This is probably slower, but at least everyone with a free trial can participate in this lab :)

Screenshot before changing size:
![image](https://user-images.githubusercontent.com/93213795/138921950-591449ab-9512-4337-a650-267acbd7163a.png)

Screenshot after changing size:
![image](https://user-images.githubusercontent.com/93213795/138922071-4080394e-59c5-4f73-a70e-128865a8c5cc.png)

BR

**Comment by OverhaulSVG** [comment]
Hi @hieronymussheesh, can you share the modified template? Please.

**Comment by staleycyn** [comment]
Reminder this repo is for Microsoft instructors teaching Microsoft courses.
