### ISSUE TITLE
Mod04Lab04Ex01Task03Step07 - Change Enabled to Associate

### ISSUE THREAD

**Issue by TammySmithMCT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#37]
# Module: 04
##### Step: 07

Description of issue
Change the word **Enabled** to **Associate**:

On the ipconfig1 blade, set Public IP address to **Enabled** and then click IP address - Configure required settings.

On the ipconfig1 blade, set Public IP address to **Associate** and then click IP address - Configure required settings.

_NOTE:  I also changed the issue content to add Exercise Number._

Repro steps:

1.  see attached image
![az104lab04ex01task03step07Associate](https://user-images.githubusercontent.com/11367710/78789603-5c9db880-797b-11ea-91f9-b6c38218d49d.PNG)

**Comment by polichtm** [comment]
updated
rgds
Marcin
