### ISSUE TITLE
Question on optimizing instructions for LOD labs

### ISSUE THREAD

**Issue by ITBlandMCT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#40]
Whenever there is a code block in the instructions, if more than one command is in the block it causes difficulties for the students using Learn on Demand labs (due to the way LOD handles code blocks). Would creating pull requests separating those steps into multiple single-line code blocks be acceptable? 
Example:
1. From the Cloud Shell pane, run the following commands (replace the `[Azure Region]`...
    ```powershell
    $location = '[Azure_region]'
    $rgName = 'az104-10-rg0'
    New-AzResourceGroup -Name $rgName -Location $location
    ```
Would become:
1. In the Cloud Shell run the following command (replace the `[Azure Region]`...:
    ```powershell
    $location = '[Azure_region]'
    ```
2. In the Cloud Shell run the following command:
    ```powershell
    $rgName = 'az104-10-rg0'
    ```
3. In the Cloud Shell run the following command:
    ```powershell
    New-AzResourceGroup -Name $rgName -Location $location
    ```
EDIT: It is primarily a problem when there is a "replace" in a line like the example above--as an alternative to splitting every code block, just splitting the line(s) that need a value replaced, 
My preference would be to consistently do one line at a time in all code blocks.

**Comment by polichtm** [comment]
Could you clarify why students cannot copy individual lines in the current form?

I'd also be interested in opinion of others regarding this. 
I gather, as usual, there is a potential drawback - which requires copying/pasting each command individually

rgds
Marcin

**Comment by staleycyn** [comment]
@ITBlandMCT - We have many different lab hosters using these instructions. What works best for one hoster may not work for another. You are welcome to maintain and distribute your own lab instructions. You could also add a note to Module 00 to emphasize this with your students. Best, Cindy.

**Comment by ITBlandMCT** [comment]
Thanks.
