### ISSUE TITLE
Suggest renaming az104-06-rg01 to az104-06-rg1

### ISSUE THREAD

**Issue by simplescripter** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#41]
# Module: 06
## Lab/Demo: 01

Description of issue

This lab names the first resource group az104-06-rg01, adding a zero before the number. But the second and third resource group names eliminate the zero (az104-06-rg2 and az104-06-rg3), as do the lab instructions for the other labs in AZ-104. For consistency, I'd recommend renaming  az104-06-rg01 to az104-06-rg1

**Comment by polichtm** [comment]
Would you mind clarifying why you consider this to be an issue?
rgds
Marcin

**Comment by polichtm** [comment]
updated
rgds
Marcin
