### ISSUE TITLE
Lab 6 may not work in Azure Pass accounts. The Azure Portal Network Watcher page does not display the resource groups.

### ISSUE THREAD

**Issue by microsmith** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#412]
# Module: 06
#### Step: 04

Description of issue
Lab 6 may not work in Azure Pass accounts.  The Azure Portal Network Watcher page does not display the resource groups.

**The lab steps do work in a normal Azure account.**

Repro steps:

1. Follow the lab steps to where you are asked to select the Resource Group. (Task 3, Step 4) The dropdown is blank.
1.
1.

**Comment by Mrtmarkov1111** [comment]
T

**Comment by microsmith** [comment]
Update... this may an intermittent thing. None of my students got this to work during class. I could not get it to work after class with Azure Pass, but could get it to work with another Azure subscription. One of the students reported this morning that late last night they got it to work with Azure Pass.

**Comment by azharkhuwaja** [comment]
I always experience issues when using **Network Watcher** whether it is AZ-303 class or AZ-104 or any other course. They take longer to work. I usually delete existing Network Watcher and re-create them. This usually works for me.

**Comment by azharkhuwaja** [comment]
There is a workaround of this issue as this issue is not related to Azure Pass or Subscription type.

Just delete all Network Watcher resource groups you already have before starting this lab. It should work fine then.
