### ISSUE TITLE
broken type text with PS script

### ISSUE THREAD

**Issue by MOC-Labs-Review** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#413]
# Module: 
#### Step: 

Description of issue
After copying the 'shell script' from this step (by   pressing the [T] button on the instruction), the shell automatically executes   partial command (before clicking Enter key) and displays an error. 

Repro steps:

1. Placed https://raw.githubusercontent.com/LODSContent/All-MOC/master/MOC/MultiLineCodeHint.md at beginning of lab.

![image](https://user-images.githubusercontent.com/91673275/142488034-5db49a41-e918-4942-85c3-78598385b0e7.png)

**Comment by staleycyn** [comment]
Is there a change that is required on this github?

**Comment by MOC-Labs-Review** [comment]
This issue has been resolved.
