### ISSUE TITLE
Mod 3 PS issue Task 2 Update

### ISSUE THREAD

**Issue by MOC-Labs-Review** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#416]

**Comment by MOC-Labs-Review** [comment]
# Module: 03
## Lab/Demo: 3d
### Task: 02
#### Step: 1

Description of issue- 
After copying the 'shell script' from this step (by pressing the [T] button on the instruction), the shell automatically executes partial command (before clicking Enter key) and displays an error.


Repro steps:

1. On this issue - we most likely need to look at the Code block being ran - after double checking this issue (seemed more complicated than what I had previously suggested/thought) it seems that the Variables being used for Diskname and RGname have incorrect syntax - See screenshot below: there is no $ symbol to declare the variable compared to 2nd screenshot where i used the $ to declare the variable.


![image](https://user-images.githubusercontent.com/91673275/142889019-6bc868d1-f3e7-48bb-be81-a900c963e8ac.png)

![image](https://user-images.githubusercontent.com/91673275/142892927-46a9c9aa-cba9-451f-85b6-a0c983c8f730.png)

2. Further more, the $LCOATION variable is being called from when previously declared in previous task (i did not complete previous task which is why im, recieving the error in my screenshot). There is also a note stating please do not delete since resources will be further used, therefore, *by adding the $ to declare the variables being used should resolve this for issue for task 2 step 1.*

**Comment by staleycyn** [comment]
Is this an internal communication for MOC-Labs-Review? This issue has been opened and closed several times.

**Comment by MOC-Labs-Review** [comment]
Internal for MOC - new issue on mod 3d that had to get double checked to fix what the issue presented to be - within the cloud shell can be ran as PS command if no subscription is present or portal down for any reason - that being said, these are variables being declared so if we look at this example:
![image](https://user-images.githubusercontent.com/91673275/142896383-2945de08-64ce-433e-893b-fdac4a14df6d.png)

we see that within the cloudshell we are writing PS commands as we are here and to declare variables we would still need proper syntax

If we want to declare '...rg1' as our RGNAME variable, we would have to present it as $RGNAME='....'

**Comment by craigbeeremct** [comment]
I think the issue above is that the required shell is Bash, not PowerShell.

Both the Bash and PowerShell shells allow the running of both PowerShell cmdlets and CLI commands, but in Bash you have to follow Bash convention (for example, variable names are defined without using a $ symbol).
