### ISSUE TITLE
Mod08Lab08Task01Step09 - change Management tab to Advanced tab

### ISSUE THREAD

**Issue by TammySmithMCT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#42]
# Module: 08
#### Step: 09

Description of issue
Change Management tab to **Advanced** tab given that step 8 was on Management tab but step 9 is on Advanced tab.

Change Step 9:
Click Next: Advanced >, on the **Management** tab of the Create a virtual machine blade, review the available settings without modifying any of them, and click Review + Create.

To:
Click Next: Advanced >, on the **Advanced** tab of the Create a virtual machine blade, review the available settings without modifying any of them, and click Review + Create.
Repro steps:

8. Click Next: Management > and, on the Management tab of the Create a virtual machine blade, specify the following settings (leave others with their default values): ...
9.  Click Next: **Advanced** >, on the **Management** tab of the Create a virtual machine blade, review the available settings without modifying any of them, and click Review + Create.

See image attached below.
![tab](https://user-images.githubusercontent.com/11367710/78929415-5e957380-7a70-11ea-93aa-ac881da23c66.PNG)

**Comment by polichtm** [comment]
updated
rgds
Marcin
