### ISSUE TITLE
PHP version on instructions no longer supported

### ISSUE THREAD

**Issue by georgiakalyva** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#434]
# Module: 09
#### Step: 03

Description of issue

PHP 7.3 can no longer be found on the dropdown. The Runtime stack in the instructions should be updated to PHP 7.4

![image](https://user-images.githubusercontent.com/17426707/148576228-07a8a95d-ea4e-4d64-b833-2f3e54241065.png)

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review solved this issue with pull request #441
