### ISSUE TITLE
No virtual networks in this subscription 

### ISSUE THREAD

**Issue by devopski** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#436]
# Module: 05
#### Step: 06

Description of issue

After RG creation it's not possible to create network peerings, because of this error:
![image](https://user-images.githubusercontent.com/77720864/149143139-149e4857-c559-45ef-9c31-60af0b88623e.png)

When I created other networks not from provided scripts - all fine, I was able to create peering.

Repro steps:

1. Create RG with VNETs
2. Try create peering via Azure Portal

**Comment by staleycyn** [comment]
These lab instructions are for use in Microsoft classes. Are you in class? If so, can you ask your instructor for assistance. This could be a temporary Azure outage.
