### ISSUE TITLE
Mod 6 - Task 3 - Step 2 - Confusing wording should be revised.

### ISSUE THREAD

**Issue by ac-cm** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#437]
# Module: 06
#### Step: 02

Description of issue:

General grammar: this step is written in a way that does not really make sense. "...service is enabled in the Azure into which you deployed...".  Also, it is unclear what to 'expand' in regard to the Azure regions.  This may simply mean to ensure that the location column is present, but it is hard to determine if that is the case.

Full text of the step: On the Network Watcher blade, expand the listing of Azure regions and verify that the service is enabled in the Azure into which you deployed resources in the first task of this lab.

Repro steps:
Just an inquiry about how the step is written.

**Comment by staleycyn** [comment]
resolved.
