### ISSUE TITLE
Unable to complete "Create a web app in the Azure portal", verify work failed

### ISSUE THREAD

**Issue by sjansen1** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#438]
# Module: 03
#### Step: Check your work

Description of issue
Task requires to create an web app service in azure portal. Creating the web service works fine but the learning portal is unable to verify my work. The webservice is correctly created under the concierge sub with the parameters from the learning portal. I skipped that task and did the next one (Unit 4) that required to deploy an app in this web service, that worked fine. I am unable to complete Unit 3 because verification of my work fails.

Repro steps:

1. Create Web App
2. Verifify my work
3. fails.

**Comment by staleycyn** [comment]
These lab instructions are for students in a Microsoft class. Are you in a class? If so, can you ask your instructor for assistance?

**Comment by sjansen1** [comment]
Oh, no i am not in class, its an issue i have with the learning website on docs.microsoft.com. Looks like this issue board is for something else, i close the issue.
