### ISSUE TITLE
Not able to Deploy JSON files

### ISSUE THREAD

**Issue by anshuman-nath** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#44]
# Module: 00
#### Step: 4

Description of issue
I'm unable to deploy VMs using JSON files as explained in the Lab instructions. Have tried using Powershell from Cloud Shell as well as using Custom deployment using Templates in Azure portal.

Have attached screenshots of the error msg. Not sure how to get past this.

Repro steps:

1. Launched Cloudshell
2. Uploaded both the files "az104-04-vms-parameters.json" & "az104-04-vms-template.json" in Home directory
3. Executed the following commands as in instructed

$rgName = 'az104-04-rg1'

New-AzResourceGroupDeployment `
   -ResourceGroupName $rgName `
   -TemplateFile $HOME/az104-04-vms-template.json `
   -TemplateParameterFile $HOME/az104-04-vms-parameters.json

P.S. I had already created resource group with above name in Azure portal.

In azure Portal
1. Searched "Custom Deployment" and navigated to it
2. Click "Build your own template in editor
3. Click "Load File" and from the file browser, selected the JSON file
4. Click "Save" 

Attached the screenshots for both attempts
![error_VM deployment in Powershell ](https://user-images.githubusercontent.com/38008770/79071457-729fd600-7cf9-11ea-853e-80ce721f0880.png)
![error_VM deployment in Azure Portal](https://user-images.githubusercontent.com/38008770/79071479-92cf9500-7cf9-11ea-9434-13137fc16187.png)

**Comment by polichtm** [comment]
Just to confirm - are you an MCT?
rgds
Marcin

**Comment by anshuman-nath** [comment]
No, I'm not an MCT. Just using this lab exercises to prepare for Azure Administrator certification exam.

**Comment by TammySmithMCT** [comment]
You need to download the zip file and extract the zip file before you upload the JSON files. Use the Upload icon (located to the right of the settings icon) in Cloud Shell [PowerShell] to upload one JSON file at a time.  In the Template use the Load file button (located at top).  I hope that helps.
