### ISSUE TITLE
Get-AzRoleAssignment is not working

### ISSUE THREAD

**Issue by marcelojaf** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#444]
# Module: 02
#### Step: 05

Description of issue

Repro steps:

1. Item 5 of Clean Up process is not working. Nothing comes out from (Get-AzRoleAssignment -RoleDefinitionName 'Support Request Contributor (Custom)').Scope
1.
1.

**Comment by staleycyn** [comment]
These lab steps are for instructors teaching Microsoft courses. If you are in a class, please ask your instructor for assistance. Thanks.
