### ISSUE TITLE
Task 2: Create custom RBAC roles

### ISSUE THREAD

**Issue by leizem** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#445]
# Module: 02
#### Step: 06

Description of issue

After I've change my ID SUBSCRIPTION at json file, I got this error message using Azure Cloud Shell:

New-AzRoleDefinition: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

Repro steps:

1. I've uploaded the .json file afer change my ID SUBSCRIPTION
2. Tried to run New-AzRoleDefinition -InputFile $HOME/az104-02a-customRoleDefinition.json
3. Got this message after run this command: New-AzRoleDefinition: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

**Comment by staleycyn** [comment]
These instructions are for instructors teaching Microsoft courses. Please ask your instructor for assistance.
