### ISSUE TITLE
Mod 8 Task 2 Step 4 - CSE upload from storage account 

### ISSUE THREAD

**Issue by TammySmithMCT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#45]
# Module: 08
#### Step: 04

Description of issue
VM CSE upload requires upload from storage account.  Mod 8 Task 2 Step 4 From the Install extension blade, upload the script az104-08-install_IIS.ps1 from \Allfiles\Labs\08 and click OK.  Needs to be updated with instructions to use a storage account. 
![cse (2)](https://user-images.githubusercontent.com/11367710/79758939-0a01bc00-82ec-11ea-89d2-55bada0ab15b.jpg)

1.
1.
1.

**Comment by Mitaric** [comment]
This is due to a recent portal change.  Can we please have the instructions updated?  Thanks!

**Comment by polichtm** [comment]
updated
rgds
Marcin
