### ISSUE TITLE
Azure_Region must be set to EastUS2

### ISSUE THREAD

**Issue by zbskillable** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#451]
#### Step: 05

Description of issue
Step 5 requires the user to select an Azure_Region where their resource group will be hosted. This region is already set to EastUS2. If the student chooses a different region they will be unable to complete the lab. The lab instructions should be updated so that the student chooses East_US_2
![image](https://user-images.githubusercontent.com/42649591/152165196-5726dbc4-097e-4619-b778-c3997d38f011.png)

**Comment by renaudwangler** [comment]
Are you providing "Azure pass" subscriptions or using an hosted lab ?
The lab is written for "Azure Pass" subscriptions : students may use the region of your/their choice ;)
