### ISSUE TITLE
Mod 09 Lab 9C DNS name prefix is found on Networking tab

### ISSUE THREAD

**Issue by TammySmithMCT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#46]
# Module: 09
#### Step: 03

DNS name prefix is not found on the Basics tab, it is found on the Networking tab. 

Move the following setting to Step 6.
DNS name prefix | any valid, globally unique DNS host name

Repro steps:
![aksdns](https://user-images.githubusercontent.com/11367710/79785328-b1451a00-8311-11ea-9f5a-b872f344ead3.PNG)

**Comment by Mitaric** [comment]
This is due to a recent portal change.  Can we please have the instructions updated?  Thanks!

**Comment by polichtm** [comment]
updated
rgds
Marcin
