### ISSUE TITLE
DNS Name Not Available

### ISSUE THREAD

**Issue by markturpinMSFT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#47]
# Module: 04
#### Step: 02

Description of issue
Contoso.org DNS zone deployment will fail as it is not an available DNS name for Azure DNS Zones "Bad Request, the zone 'contoso.org' is not available"

Before step 2, we should insert a test to validate an available DNS name.  Example:

In the Cloud Shell pane, run the following command, substituting the placeholder <custom-label> with any string which is likely to be unique and the placeholder <location> with the name of the Azure region into which you want to deploy, and validate the command returns "True" before you proceed.

Test-AzDnsAvailability -DomainNameLabel <custom-label> -Location '<location>'

Modify the DNS zone name parameter in step 3 to say:

"Use the DNS zone name you validated as available in the previous step"

**Comment by polichtm** [comment]
Test-AzDnsAvailability is not intended for this purpose. If you run it against any domain name (rather than a short name), it will generate an error message.
Instructions updated to test for uniqueness - although a bit differently from this suggestion
rgds
Marcin
