### ISSUE TITLE
Lab 8, Task 5 missing details

### ISSUE THREAD

**Issue by skellogg** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#48]
# Module: 00
#### Step: 4

The steps below fail to mention that the file mentioned needs to be added to a container (either new or the existing one) as it was in Task 2 in order to Upload and Select it.

**Task 5: Configure Azure virtual machine scale sets by using virtual machine extensions**
In this task, you will install Windows Server Web Server role on the instances of the Azure virtual machine scale set you deployed in the previous task by using the Custom Script virtual machine extension.

1. In the Azure portal, refresh the Virtual machine scale sets blade and click az10408vmss0.
2. On the az10408vmss0 blade, click Extensions, and the click + Add.
3. On the New resource blade, click Custom Script Extension and then click Create.
4. From the Install extension blade, upload the script az104-08-install_IIS.ps1 from \Allfiles\Labs\08 and click OK.

Repro steps:

https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/blob/master/Instructions/Labs/LAB_08-Manage_Virtual_Machines.md#task-5-configure-azure-virtual-machine-scale-sets-by-using-virtual-machine-extensions

**Comment by ITBlandMCT** [comment]
As you noted, the script was uploaded in Task 2, we don't need to upload it again, we just need to change the Browse step to point to the script already in the container from Task 2.

**Comment by skellogg** [comment]
I see, I didn't read the file name carefully and thought it was directing to upload a _new_ file from "Allfiles."
