### ISSUE TITLE
Module 11 Steps - Revision

### ISSUE THREAD

**Issue by markturpinMSFT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#49]
# Module: 11
#### Step: 05

Description of issue

These instructions need one modification and removal of a duplicate instruction.

Step 5 needs to be updated to say:
On the az104-11-vm0 blade, in the Monitoring section, click Logs **and click Enable.**

Step 6 - no change

Step 7 - not needed, please remove

**Comment by polichtm** [comment]
updated
