### ISSUE TITLE
How once good way become different

### ISSUE THREAD

**Issue by HelgiBergmann** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#492]
I think I in captivity of Russian, in Krakow and they doing shokoterapia to me. My computer has a lot of backdoors. They use natural language processing for very bad purposes . I have huge electrical box which goes to my house. My chandelier when I go there was with nazi symvolic. And I feel like they mess with me.

**Comment by staleycyn** [comment]
This is active GitHub repository for Microsoft Certified Trainers. Please limit your remarks to the focus of the classroom labs.
