### ISSUE TITLE
Custom diagnostics storage account empty but mandatory

### ISSUE THREAD

**Issue by jkulbe** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#504]
# Module: 08
#### Step: 08

Instructions say to enable boot diagnostics with custom storage account and accept the default value for the "Diagnostics storage account". In this case, the default is empty but mandatory. 
Suggested update to the instructions: click "create new" under "Diagnostics storage account" to create a new diagnostics storage account.

Repro steps:

1. follow instructions until step 8, select "Boot diagnostics" with value "Enable with custom storage account"
2. line "Diagnostics storage account" in the portal is empty but mandatory
3. notes below the config table advises to use an existing storage account, but there is nine if resources have been cleaned up as per previous lab instuctions..

**Comment by staleycyn** [comment]
The lab steps were reviewed this month, and this was not identified. If you feel a change is still required, please reopen the issue.
