### ISSUE TITLE
under network watcher the resource group does not show up

### ISSUE THREAD

**Issue by sudlo** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#505]
# Module 06 - Network Traffic Management
#### Step: 03 

Description of issue  :under network watcher the resource group does not show up

Repro steps: Followed the steps given in the lab 

[https://microsoftlearning.github.io/AZ-104-MicrosoftAzureAdministrator/Instructions/Labs/LAB_06-Implement_Network_Traffic_Management.html](url)

1. In the Azure portal, search for and select Network Watcher.
2. On the Network Watcher blade, expand the listing of Azure regions and verify the service is enabled in region you are using.
3. On the Network Watcher blade, navigate to the Connection troubleshoot.
4. On the Network Watcher - Connection troubleshoot
5. under resource group - Resource group does not give the list of groups which i have created previously

Region - Eastus

attached screenshot for your reference.

![Network watcher](https://user-images.githubusercontent.com/2640256/155765323-024b4ad0-6ae6-4cc7-853f-2315212bd55a.jpg)

**Comment by staleycyn** [comment]
This is an intermittent problem. There are 2 closed issues which may offer suggestions.

[The Azure Portal Network Watcher page does not display the resource groups. #412](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/issues/412)

[Network Watcher - Connection troubleshoot no resource group #265](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/issues/265)

There is also at least one Forum post.
[Azure Network Watcher resources not visible while created from Azure Portal](https://docs.microsoft.com/en-us/answers/questions/147292/azure-network-watcher-resources-not-visible-while.html)

Hope that helps.
