### ISSUE TITLE
AZ104- Mod5 Lab

### ISSUE THREAD

**Issue by amysy** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#517]
# Module: 05
#### Step: 05 onwards none of the powershell commands work.

Description of issue- errors in Cloud PowerShell command tocreate  vNet and VMs. Instructions are not clear.
 - admin user/password are provided. Why there is a need for password change. 
(Get-AzLocation).Location not working.

Repro steps:

1. location1= 'eastus' // where to change this?
1. New-AzResourceGroupDeployment is not working either and not recognized as cmdlet or function.
Rest of the tasks are incomplete because of prior errors.
Note: I removed the ticks and ran commands but that didn't work either. Please see attached screens.
![az104-mod5 step5err2](https://user-images.githubusercontent.com/13893456/160250607-07f8b4ba-7912-4220-99a9-752c8792d04d.png)
![az104-mod5 step5err](https://user-images.githubusercontent.com/13893456/160250608-74da9fe8-93d2-470b-8434-d2e59c3d6d24.png)

**Comment by staleycyn** [comment]
There are known issues with creating VMs in the cloud shell. You can view these Azure issues on the GitHub - https://github.com/Azure/CloudShell/issues/147

The password change is a known security issue as documented on the Readme page. 

This repo is for instructors teaching Microsoft courses. If you are in class, please ask your instructor for assistance.

**Comment by amysy** [comment]
Ok - Our class ended and I don't know any other ways to get support.

**Comment by staleycyn** [comment]
Microsoft Learn provides free sandboxes for creating Windows and Linux virtual machines. There is also a nice lab on distributing services that you may find helpful.

[Distribute your services across Azure virtual networks and integrate them by using virtual network peering](https://docs.microsoft.com/en-us/learn/modules/integrate-vnets-with-vnet-peering/)

[Create a Windows virtual machine in Azure](https://docs.microsoft.com/en-us/learn/modules/create-windows-virtual-machine-in-azure/)

[Create a Linux virtual machine in Azure
](https://docs.microsoft.com/en-us/learn/modules/create-linux-virtual-machine-in-azure/)

**Comment by staleycyn** [comment]
Also,

[Secure and isolate access to Azure resources by using network security groups and service endpoints](https://docs.microsoft.com/en-us/learn/modules/secure-and-isolate-with-nsg-and-service-endpoints/)
