### ISSUE TITLE
Authentication tab renamed to Access tab

### ISSUE THREAD

**Issue by georgiakalyva** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#518]
# Module: 09
#### Step: 04

Description of issue

The Authentication tab is renamed to Access tab. This should also be corrected in the instructions

Repro steps:

These are the current instructions:

![image](https://user-images.githubusercontent.com/17426707/161001880-fadca789-fff5-4b80-b658-bab0b8f014f0.png)

This is the portal page:

![image](https://user-images.githubusercontent.com/17426707/161001935-2a365ba8-719a-4ca2-8c5d-f193dc42acad.png)

**Comment by staleycyn** [comment]
Corrected. Thanks.
