### ISSUE TITLE
Enable virtual machine scale sets option not found in Node pools tab

### ISSUE THREAD

**Issue by georgiakalyva** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#519]
# Module: 09
#### Step: 03

Description of issue

The _Enable virtual machine scale sets_ option is not found in tab Node Pools. It needs to be removed from the instructions.

Repro steps:

These are the instructions

![image](https://user-images.githubusercontent.com/17426707/161002546-568215b3-1af8-444e-b401-84537734278c.png)

This is the portal page
![image](https://user-images.githubusercontent.com/17426707/161002697-ae73caf7-68a3-44af-90ee-20c95caab864.png)

**Comment by staleycyn** [comment]
Corrected. Thanks.
