### ISSUE TITLE
Module 2B Task 1 and 2

### ISSUE THREAD

**Issue by sarahkong** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#522]
# Module: 2B
#### Step: all steps

Description of issue
In this lab we have task 1 that has users create 2 tags in the Resource Group via the portal manually. 
In Task 2 you  have the users create the same 2 tags using an Azure policy.
This creates confusion for 2 reasons.
1. You can't add 2 tags in a policy.
2. The same tags are used and they are already there.

I would like to suggest that you have them create a different tag in the policy so they can see the difference of tagging using Tags directly in the RG or tagging using Tag in a policy

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by jfinleynz** [comment]
I was reviewing this again today, and did not experience this issue. I suspect it has been cleaned up.
