### ISSUE TITLE
Module 2 Lab 02a -PowerShell Error in clean up

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#523]
# Module: 02
#### Step: 05

Description of issue

PowerShell doesn't work: throws error.

Command:
$scope = (Get-AzRoleAssignment -RoleDefinitionName 'Support Request Contributor (Custom)').Scope

Error:
WARNING: We have migrated the API calls for this cmdlet from Azure Active Directory Graph to Microsoft Graph.
Visit https://go.microsoft.com/fwlink/?linkid=2181475 for any permission issues.

I am not sure what the fix is....  The $scope variable doesn't get set. 

![Lab2A-CleanUpError](https://user-images.githubusercontent.com/16696370/161646271-0d85416a-4eb3-4f28-98cb-2f9ecd3e42b3.PNG)

Repro steps:

1.
1.
1.

**Comment by staleycyn** [comment]
Addressed in another issue.
