### ISSUE TITLE
Module 4  Task 6 Configure Azure DNS for external name resolution

### ISSUE THREAD

**Issue by Franlusan** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#54]
Step 2 says create external DNS with the name Contoso.org. If one student creates that DNS name, the others will have to create a different one not all the same. Finally with testing the name resolution it appears a message "Server refused request". I think it is not correctly designed because if the external DNS worked correctly, the name resolution should work not only from the virtual machines in the lab but also with our personal computers.

**Comment by polichtm** [comment]
It appears that you are using outdated content. Pls refer to the current version
rgds
Marcin

**Comment by Franlusan** [comment]
OK. thank you
