### ISSUE TITLE
ServiceUnavailable - Lab 08

### ISSUE THREAD

**Issue by sudlo** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#542]
# Module: 08
#### Step: 10

Description of issue: during deployment of the vm, we are getting request timed out 

Repro steps:

1. performed the step given in the lab guide.
2. After clicking on create it stalls on - [RoleAssignments821] -  status ServiceUnavailable

(https://portal.azure.com/#blade/HubsExtension/DeploymentDetailsBlade/id/%2Fsubscriptions%2F305b2fe1-dbf4-4309-97ea-19ef469c9564%2Fproviders%2FMicrosoft.Resources%2Fdeployments%2FRoleAssignments821)

operation details are as follows

Operation ID
/subscriptions/305b2fe1-xxxxxxxxx/resourceGroups/az104-08-rg01/providers/Microsoft.Resources/deployments/CreateVm-MicrosoftWindowsServer.WindowsServer-201-20220409205126/operations/7215878281B03A78

Operation name - 7215878281B03A78

Provisioning operation - Create

Provisioning state - Running

Timestamp - 4/9/2022, 9:29:12 PM

Tracking ID - e2394ac7-6499-489e-a906-7da87dafe299

serviceRequestId - 9b5fa30d-6498-4573-920d-34585dd28131

Status - ServiceUnavailable

status message : 

`{
    "status": "Failed",
    "error": {
        "code": "ServerTimeout",
        "message": "The request timed out. Diagnostic information: timestamp '20220409T155911Z', subscription id '305b2fe1-dbf4-4309-97ea-19ef469c9564', tracking id '9b5fa30d-6498-4573-920d-34585dd28131', request correlation id 'bb6e2b61-1e06-433c-9f4c-95090ea58a74'."
    }
}`

Type Microsoft.Resources/deployments
Resource RoleAssignments821

**Comment by staleycyn** [comment]
I was able to complete the steps without a problem. Please try again or ask your instructor or classmates for help. If this has been resolved, please close the issue. Thanks.

**Comment by staleycyn** [comment]
If there are no other suggestions on how to troubleshoot this message, then I will close the issue. This repo is for distributing lab instructions to instructors teaching Microsoft courses. Please understand we are not able to provide help desk support. No classes have reported this issue.
