### ISSUE TITLE
Mod 6/Slide 8 - Graphic and wording clarifications

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#546]
# Module: 6
## Slide 8

Description of issue
1. It is confusing to call it the "frontend subnet" when the name of the subnet is (apparently) "public". Or is the "public" subnet actually the "DMZ"? Which is the "private" subnet? Graphic should be updated to match screen shot.

2. It would be beneficial if the graphic included the IP Addressing scheme.

3. "DMZ" should not be used according to the Microsoft Style Guide (https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/d/demilitarized-zone-dmz)

4. Yellow bullet numbers do not match.  Are you setting the route table on the Front End subnet or the DMZ subnet?

**Comment by staleycyn** [comment]
This repo is only for logging issues and PRs against the lab instructions. We will log a bug against the course asking PPT 6, Examine a Routing Example, be reviewed.

**Comment by boomalator** [comment]
Might be an idea to name the repo appropriately. Such as including “Labs” in the name.


Mobile: big fingers, little buttons, and don't get me started about autocorrect.

On Apr 13, 2022, at 10:42 AM, staleycyn ***@***.***> wrote:

﻿

This repo is only for logging issues and PRs against the lab instructions. We will log a bug against the course asking PPT 6, Examine a Routing Example, be reviewed.
