### ISSUE TITLE
Mod 4 - Review Question Ambiguity

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#547]
# Module: 4
#### Question 4

Description of issue
Technically, an AAAA record would meet the requirement of "resolving to an IP address" since the question does not specify resolving to an IPv4 address.

**Comment by staleycyn** [comment]
This repo is only for logging issues and PRs on the lab instructions. Are you referring to Question 2 on this [Learn page](https://docs.microsoft.com/learn/modules/configure-azure-dns/9-knowledge-check)? If so, please use the "reporting an issue" link at the bottom of that page to create a bug. Please be specific on what needs to be changed. Thanks.

**Comment by boomalator** [comment]
I’m sorry. I don’t have time to chase down three or four websites to correct author errors.

Best wishes.


Mobile: big fingers, little buttons, and don't get me started about autocorrect.

On Apr 13, 2022, at 10:49 AM, staleycyn ***@***.***> wrote:

﻿

This repo is only for logging issues and PRs on the lab instructions. Are you referring to Question 2 on this Learn page<https://docs.microsoft.com/learn/modules/configure-azure-dns/9-knowledge-check>? If so, please use the "reporting an issue" link at the bottom of that page to create a bug. Please be specific on what needs to be changed. Thanks.
