### ISSUE TITLE
Misleading deployment name

### ISSUE THREAD

**Issue by strugdt** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#553]
# Module: 01
#### Step: 06

Description of issue - Learners get confused because name of the deployment is not always what we are mentioning here. If we don't specify deployment name in this format anymore, we could just say that click on the first deployment. 

"On the **Microsoft.ManagedDisk-XXXXXXXXX** | Overview blade, click Template."

Repro steps:

1.
1.
1.

**Comment by staleycyn** [comment]
The first deployment may not be the ManagedDisk one. What do you want this changed to? Or do you want an explanatory note? The lab steps are designed with having an instructor nearby. Write back if you want something changed.
