### ISSUE TITLE
Mod 4 - Lab 4 - vmSize default value doesn't work for several regions and should be changed

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#557]
# Module: 04 and others
#### Step: 05

The vmSize 'Standard_D2s_v3' used in the current parameter templates is not available in several regions worldwide, mostly but not only limited to Azure Pass subscriptions. I know there is a note in this lab instructing the students to find and replace the vmSize by an available size in their region of choice, but for a while now at least 30%-50% of all learners run into this issue and struggling finding a size that works.

I'd like to suggest changing to a widely available size like 'Standard_D2ads_v5' instead of keeping just the note in. The note has not been added to all labs where the deployment of VMs fails for the same reason (e.g. Lab 6, Lab 7, Lab 8).

**Comment by staleycyn** [comment]
I have modified the Note (ask your instructor for assistance) and added the Note to Lab 06 and Lab 07. I didn't find a place to add the Note to Lab 08. We have changed the vm size before and it stopped working along the way. Some lab hosters have already changed the size to work best in their lab environment. Write back if something else needs to be added.
