### ISSUE TITLE
LAB08/Task6/Step18 - UI changes

### ISSUE THREAD

**Issue by cnschindler** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#56]
# Module: 08
#### Step: 18

Description of issue

Step 18 refers to "Storage" when it is called "Disks" in the Azure VM UI.

Change step 18, so it reads as follows:

On the az10408vmss0 blade, click Disks, click + Add data disk, and attach a new managed disk with the following settings (leave others with their default values):

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
updated
