### ISSUE TITLE
Module 1 - Exercise 1 error creating AAD

### ISSUE THREAD

**Issue by cdanvergara** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#573]
# Module: 01
#### Step: 07

Description of issue

We are having issues while creating the AAD tenant.
All students can not create a new AAD tenant, the captcha validation just keeps asking for the code to prove you're not a robot, even when the right code it's provided.
So far, we tried closing and relaunching everything like 70 times, still the same result.

Students unable to create the AAD tenant:

Error message:
![image](https://user-images.githubusercontent.com/6410720/168679964-df365524-c2bb-487d-8249-472a31b4260f.png)

Repro steps:

From the Azure Active Directory Overview blade, select Manage Tenants and then + Create.

On the Basics table of the Create a directory blade, select Azure Active Directory, then select Next: Configuration .

On the Configuration tab, configure the following fields then click Review + Create, and then Create:

**Comment by RivasMario** [comment]
Repeated  steps and I was able to create a new AAD tenant

Were the students using unique names for the orgs every time? If there is another version  in use in public it blocks you.

**Comment by cdanvergara** [comment]
Looks like it was a transient error.
I retried five minutes ago and was able to do it on the first attempt:
![image](https://user-images.githubusercontent.com/6410720/168700164-11c2e0b3-f4e7-4998-9b73-5b80af764d51.png)

Closing this issue...
