### ISSUE TITLE
Task 2 

### ISSUE THREAD

**Issue by pagar-aqui** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#574]
Description of issue
not able to create a new AZ Rule definition 
I keep getting the forbidden error, I am the global admin so I don't believe it's a permissions issue.
The .json has been modified with the ID 
I also do not see where the $Home variable was created. I am not sure if that may be related to the issue. 

![image](https://user-images.githubusercontent.com/105683923/168877558-bc379a5b-b1b9-40c7-b917-ed8d337549c9.png)

**Comment by Fouyoufr** [comment]
HI.
$HOME is a system variable. Are you a trainer ?
If you're a student, please ask your trainer to help you verifying the content of your json role definition file ;)

**Comment by staleycyn** [comment]
No response, closing the ticket.
