### ISSUE TITLE
Getting error at Task1 Step 6 - Doesn't work!

### ISSUE THREAD

**Issue by kapil0239** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#58]
# Module: AZ-104-MicrosoftAzureAdministrator
# Lab/Demo: LAB_05
#### Step: 06

Description of issue
++++++++++++++++++++++++++++++++++++++++++++++++
S /home/kapil> New-AzResourceGroupDeployment `
>>    -ResourceGroupName $rgName `
>>    -TemplateFile $HOME/az104-05-vnetvm-template.json `
>>    -TemplateParameterFile $HOME/az104-05-vnetvm-parameters.json `
>>    -nameSuffix 0 `
>>    -AsJob
New-AzResourceGroupDeployment:
Line |
   5 |     -nameSuffix 0 `
     |     ~~~~~~~~~~~
     | A parameter cannot be found that matches parameter name 'nameSuffix'.

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Repro steps:

1.
1.
1.

**Comment by al-lac** [comment]
I tried to reproduce the error. Works on my side without any problems. Did you use the Cloud Shell?

**Comment by polichtm** [comment]
Pls make sure you use the exact format as the one provided in the instructions
rgds
Marcin

**Comment by kapil0239** [comment]
Thanks for the response guys!
Yes, I used the cloud shell and I copy pasted the code from the lab instructions...I just tested again and same error...
![image](https://user-images.githubusercontent.com/64970280/81323957-db3d6100-90b3-11ea-818e-d2cb503659fa.png)

Attached - error!

**Comment by al-lac** [comment]
Hey @kapil0239, it seems to me like the file az104-05-vnet-template.json is somehow corrupted on your azure storage. nameSuffix is a parameter from that file, if it is not there you get exactly that error. I changed the value to "nameTest", after that i got the same error but i could use -nameTest 0 as a parameter. Try to reupload the template file and check for the following parameter in there:

```json
...
"parameters": {
      "vmSize": {
        "type": "string",
        "defaultValue": "Standard_D2s_v3",
        "metadata": {
          "description": "Virtual machine size"
        }
      },
      "nameSuffix": {
        "type": "string",
        "allowedValues": [
          "0",
          "1",
          "2"
        ],
        "metadata": {
          "description": "Naming suffix"
        }
      },
...
```

**Comment by kapil0239** [comment]
The above mentioned section is missing in the parameter file...what should I do?

**Comment by polichtm** [comment]
Pls reach out to your instructor/MCT regarding this
rgds
Marcin

**Comment by al-lac** [comment]
@kapil0239 The section i was refering to should be in the template file. You can just grab the correct  files from here: https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/tree/master/Allfiles/Labs/05

**Comment by kapil0239** [comment]
That's the link I've downloaded the files..I tried typing all these commands but still the same issue.

**Comment by kapil0239** [comment]
Got this guys!!!
The json files I was downloading were getting corrupt...Actual Filesize were less 10KB, however when I was downloading from gitub, the size was way bigger than actual.

**Comment by al-lac** [comment]
Glad you were able to resolve it!
