### ISSUE TITLE
Lab 9c Monitoring tab is Integrations tab now

### ISSUE THREAD

**Issue by TammySmithMCT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#59]
# Module: 09
#### Step: 07

Description of issue:  GUI updated - instructions need updating
change this:
Click Next: Monitoring >, on the Monitoring tab of the Create Kubernetes cluster blade, set Enable container monitoring to No, click Review + create and then click Create.

to this:
Click Next: **Integrations** >, on the **Integrations** tab of the Create Kubernetes cluster blade, **set  container monitoring to Disabled**, click Review + create and then click Create.

Repro steps:

![integrations](https://user-images.githubusercontent.com/11367710/81343922-d791e600-9083-11ea-9b64-46720daecdb0.PNG)

**Comment by polichtm** [comment]
updated
rgds
Marcin
