### ISSUE TITLE
Concept

### ISSUE THREAD

**Issue by Sambech** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#592]
Currently the labs consist of a small introduction and then a step-by-step solution to the problem. I think, it would be better to describe the problem completely, so that students can try to solve it without further guidance and only lookup the solution after they solved the problem. I think, this is how learning and exercises are done generally (e.g. mathematics, physics, ...) and this might lead to a far better understanding.

**Comment by staleycyn** [comment]
@Sambech - These labs are used in our instructor- led courses and not designed for independent study. I would suggest you try our online Learn sandboxes, like this one: [Create a storage account](https://docs.microsoft.com/en-us/learn/modules/create-azure-storage-account/)
