### ISSUE TITLE
Error/changes in Lab 09C

### ISSUE THREAD

**Issue by TommyKobber** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#593]
# Module: 00
#### Step: 02

The portal has changed.

Repro steps:

Between "Resource Group" line and "Kubernetes Cluster name" line should be :
Cluster preset Configuration" Choose "Dev/Test ($)"
Below "Kubernetes Version" line, add new line:
"API Server availability" "accept the default"

Step 05: Write a unique DNS Name Prefix

**Comment by staleycyn** [comment]
Made the corrections. Thanks for reporting.
