### ISSUE TITLE
Lab03b Missing template json values Task2 step 4

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#595]
# Module: 03
#### Step: 00

Description of issue Some  Template Key/values listed in the lab are missing 

This is from the lab instructions Task2 #4 . I have bolded the missing key/value

"sourceResourceId": {
    "type": "String"
},
**"sourceUri": {                          MISSING
    "type": "String"
},
"osType": {                                MISSING
    "type": "String"
},**
AND
**"osType": "[parameters('osType')]",**  MISSING

THIS is From the portal

{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "diskName": {
            "type": "String"
        },
        "location": {
            "type": "String"
        },
        "sku": {
            "type": "String"
        },
        "diskSizeGb": {
            "type": "Int"
        },
        "sourceResourceId": {
            "type": "String"
        },
        "createOption": {
            "type": "String"
        },
        "hyperVGeneration": {
            "defaultValue": "V1",
            "type": "String"
        },
        "diskEncryptionSetType": {
            "type": "String"
        },
        "dataAccessAuthMode": {
            "type": "String"
        },
        "networkAccessPolicy": {
            "type": "String"
        },
        "publicNetworkAccess": {
            "type": "String"
        }
    },
    "resources": [
        {
            "type": "Microsoft.Compute/disks",
            "apiVersion": "2021-12-01",
            "name": "[parameters('diskName')]",
            "location": "[parameters('location')]",
            "tags": {},
            "sku": {
                "name": "[parameters('sku')]"
            },
            "properties": {
                "creationData": {
                    "createOption": "[parameters('createOption')]"
                },
                "diskSizeGB": "[parameters('diskSizeGb')]",
                "encryption": {
                    "type": "[parameters('diskEncryptionSetType')]"
                },
                "dataAccessAuthMode": "[parameters('dataAccessAuthMode')]",
                "networkAccessPolicy": "[parameters('networkAccessPolicy')]",
                "publicNetworkAccess": "[parameters('publicNetworkAccess')]"
            }
        }
    ]
}

Repro steps:

1.
1.
1.

**Comment by staleycyn** [comment]
Can you please clarify this Issue. Lab 03b Task 2 Step shows the values you have listed.

**Comment by dpapkin** [comment]
WHat I am saying is that the instructions ask you to remove the following from the downloaded template file.

 "sourceResourceId": {
"type": "String"
},
"sourceUri": { MISSING
"type": "String"
},
"osType": { MISSING
"type": "String"
},
AND
"osType": "[parameters('osType')]", MISSING

The downloaded template file does NOT have the following jason key/value pair

"sourceUri": { MISSING
"type": "String"
},
"osType": { MISSING
"type": "String"
},
AND
"osType": "[parameters('osType')]", MISSING

David Papkin

**Comment by staleycyn** [comment]
The template file being referenced is in Allfiles/Labs/03/az104-03b-md-template.json. That file appears to have the parameters.

**Comment by dpapkin** [comment]
Yes, I am aware of what file but if you follow the instructions and DOWNLOAZD your deployment, those are missing. Obviously there has been some change in the back end. Several students experienced and I personally verified this.

Those values are NOT there,

I redid the lab and have verified this.

The template file
 Allfiles/Labs/03/az104-03b-md-template.json is not current.

Here is teh contents of the Template file downloaded from a freshly done lab.

****************
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "diskName": {
            "type": "String"
        },
        "location": {
            "type": "String"
        },
        "sku": {
            "type": "String"
        },
        "diskSizeGb": {
            "type": "Int"
        },
        "sourceResourceId": {
            "type": "String"
        },
        "createOption": {
            "type": "String"
        },
        "hyperVGeneration": {
            "defaultValue": "V1",
            "type": "String"
        },
        "diskEncryptionSetType": {
            "type": "String"
        },
        "dataAccessAuthMode": {
            "type": "String"
        },
        "networkAccessPolicy": {
            "type": "String"
        },
        "publicNetworkAccess": {
            "type": "String"
        }
    },
    "resources": [
        {
            "type": "Microsoft.Compute/disks",
            "apiVersion": "2021-12-01",
            "name": "[parameters('diskName')]",
            "location": "[parameters('location')]",
            "tags": {},
            "sku": {
                "name": "[parameters('sku')]"
            },
            "properties": {
                "creationData": {
                    "createOption": "[parameters('createOption')]"
                },
                "diskSizeGB": "[parameters('diskSizeGb')]",
                "encryption": {
                    "type": "[parameters('diskEncryptionSetType')]"
                },
                "dataAccessAuthMode": "[parameters('dataAccessAuthMode')]",
                "networkAccessPolicy": "[parameters('networkAccessPolicy')]",
                "publicNetworkAccess": "[parameters('publicNetworkAccess')]"
            }
        }
    ]
}

********************

David Papkin



________________________________
