### ISSUE TITLE
lab06 GUI Drift

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#597]
# Module: 06
#### Step: 00

Description of issue

GUi Drift. The students have alot of difficulty following instructions.

Task 5(load balancer) Step 7 - 15 quite different than instructions
Task 6 (AGW)  STep  7 - 15 quite different

Please  update the instructions to match.   Alot of student complaints in this batch about GU drift. 

. I teach this course many many times. every month.
Repro steps:

1.
1.
1.

**Comment by staleycyn** [comment]
Fixed up Task 5 (load balancer) and Task 6 (application gateway). Write back on how it goes.
