### ISSUE TITLE
lab11 Task5 Step 5 GUI Drift

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#599]
# Module: 11
#### Step: 05

Description of issue

On the az104-11-vm0 blade, in the Monitoring section, click Log Analytics Agent and then click Enable

SHOULD BE

On the az104-11-vm0 blade, in the Monitoring section, click Logs, then Select Log Analytics Agent and then click  Configure, then Enable.

![image](https://user-images.githubusercontent.com/24426530/187884296-b35df36c-f9b5-4a81-9f40-ee7cf38e1a7f.png)

Repro steps:

1.
1.
1.

**Comment by staleycyn** [comment]
This was corrected in Issue #594 https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/issues/594
