### ISSUE TITLE
I need to set up Microsoft Azure

### ISSUE THREAD

**Issue by JoHaRo1** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#603]

**Comment by staleycyn** [comment]
This is an active GitHub repository. Is there some reason for this Issue?

**Comment by JoHaRo1** [comment]
I need help setting up the Azure

**Comment by staleycyn** [comment]
This repository is for students attending Microsoft courses with a Microsoft Certified Trainer. If you are in class, please ask for assistance. If you are not in class, please try the [self-paced Learn content](https://docs.microsoft.com/en-us/training/browse/).
