### ISSUE TITLE
Lab 8 step 8, change Management to Monitoring

### ISSUE THREAD

**Issue by TammySmithMCT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#606]
# Module: 08
#### Step: 08

Description of issue
Change Management to Monitoring in two places.

Update Next: Management to Next: Monitoring 
Update Management tab to Monitoring tab 

Repro steps:
![image](https://user-images.githubusercontent.com/11367710/190234833-b6fe0ffa-3b1a-4572-b076-daf745906e7b.png)

![image](https://user-images.githubusercontent.com/11367710/190235932-7b0442ea-9844-4f17-9a8b-74fa9cb72afb.png)

**Comment by staleycyn** [comment]
This has been corrected. Another user logged an Issue on this lab that the zone deployment failed. Did you have a similar problem? Issue https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/issues/604

**Comment by mkennten** [comment]
I just opened a new issue #612 for this - the UI corrections are not done, the lab instructions don't work currently. And I can confirm that the deployment in Zone 2 does not work.
