### ISSUE TITLE
Lab 7 Task 1 Step 6

### ISSUE THREAD

**Issue by jourdanparham** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#609]
# Module: 07 Manage Azure Storage
#### Step: 06

Description of issue: The step of creating a new resource group named 'az104-07-rg0-lod#######' has already been created by the CloudSlice lab. Instructing learners to create a new resource group with the same name of the existing resource group causes confusion because it results in an error. I recommend adding a note to the CloudSlice labs that explains the resource group has already been created. Learners should instead use the existing resource group to deploy their virtual machine.

Repro steps:

![image](https://user-images.githubusercontent.com/21994425/191550673-470577fe-3477-4d2e-bc59-a70202a17865.png)

![image](https://user-images.githubusercontent.com/21994425/191552852-f4499001-cfe9-480e-9e8f-9bcfae2c5900.png)

**Comment by staleycyn** [comment]
Forwarded to Skillable help desk to adjust their instructions.
