### ISSUE TITLE
Lab 11 Task 6 Steps 4-11 

### ISSUE THREAD

**Issue by TammySmithMCT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#61]
# Module: 11
#### Steps: 04-11

Description of issue
Step 4 results in the following error:  Cannot read property 'eventCategory' of undefined
Also, GUI changed.

To fix:
Add this step prior to step 4:
In the METRICS drop-down list, select Percentage CPU, in the AGGREGATION drop-down list, select Avg, and review the resulting chart.

Delete Step 5.

Change step 6 from this:
On the Create rule blade, in the CONDITION section, click Add.
To this:  On the Create rule blade, in the CONDITION section, click on existing condition.

Change step 7 from this:
On the Configure signal logic blade, in the list of signals, click Percentage CPU, in the Alert logic section, specify the following settings (leave others with their default values) and click Done:
To this:
On the Configure signal logic blade, in the list of signals, in the Alert logic section, specify the following settings (leave others with their default values) and click Done:

Change Step 8 from this:
On the Create rule blade, in the ACTION GROUPS (optional) section, click Create.
To this:
On the Create rule blade, in the ACTION GROUPS (optional) section, select action group then click the + Create action group button.

Delete Step 11.

![alertruleerror](https://user-images.githubusercontent.com/11367710/81484615-de039780-9214-11ea-96ab-ad8e89a4a80f.PNG)

![create alert rule](https://user-images.githubusercontent.com/11367710/81484617-e6f46900-9214-11ea-9fd3-560f53d9d43c.PNG)

**Comment by polichtm** [comment]
updated
