### ISSUE TITLE
Lab 8 - Manage Virtual Machines - Updates required due to UI changes

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#612]
# Module: 08
#### Step: 08

In step 8 the instructions state to Click "Next: Monitoring" but at that point (on the Networking tab), the button actually says "Next: Management".

Adding to this, in step 8 "Patch orchestration options" should be set to "Manual updates" - this option is on the Management Tab, not Monitoring.

The next step from the "Management" tab is "Monitoring" (where settings need to be checked/changed from step 8), and from there the next tab is "Advanced"

**Comment by staleycyn** [comment]
Made some changes. Write back if something else needs to be changed.
