### ISSUE TITLE
Lab 07 Task 2

### ISSUE THREAD

**Issue by Commochief** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#613]
# Module: 07
#### Step: 7-8

Description of issue
Lab -07 Task 2 Step 7 is wrong - On the Storage account blade, in the Data management section, click Redundancy and note the secondary location.
Should be - On the Storage account blade, in the Data management section, click Geo-Location and note the secondary location.

Lab -07 Task 2 Step 8 is wrong - In the Redundancy drop-down list select Locally redundant storage (LRS) and save the change. Note, at this point, the Storage account has only the primary location.
Should be - On the Storage account blade, in the Settings section, click Configuration, find the Replication drop down list select Locally redundant storage (LRS) and save the change. Note, at this point, the Storage account has only the primary location.

**Comment by renaudwangler** [comment]
Sorry to tell I think the lab instructions are actually right : the UI has changed (or, since you see the old one, is currently changing). I was used to see the same information you point here but, this week, my students and I had the new one ;)
(Indeed I was surprised and discovered the new UI during a demonstration)

**Comment by Commochief** [comment]
It could be because we are using Azure Government that we are seeing the old UI and Azure Commercial is seeing a new UI. Thanks for that info. Will pass it along to my class.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by staleycyn** [comment]
Closing without a change. Write back if there is still an issue.
