### ISSUE TITLE
Lab 9c - UI changes need to be reflected in the instructions

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#614]
# Module: 09
#### Step: 04

In step 4 the user should verify that both System-assigned managed identity and Role-based access control (RBAC) in enabled.

The UI has changed in a way 1) the system-assigned managed identity cannot be changed and is a bit more difficult to find (I wouldn't even mention this anymore) and 2) RBAC is not just a checkbox anymore but a dropdown with different RBAC options. The instruction should clarify which of those option is to be picked (or if the default should be left).

![image](https://user-images.githubusercontent.com/37703728/193066271-5fcc8f9b-4ee9-4586-9d96-b34f5ff671b0.png)

**Comment by renaudwangler** [comment]
Hi.
Just ran in the same problem with a student : I porposed a PR about this lab : just leave the default values on this page...

**Comment by staleycyn** [comment]
Approved the PR, closing the issue.
