### ISSUE TITLE
Lab 11 Task 7 Step 3 & 7 not working - change query

### ISSUE THREAD

**Issue by TammySmithMCT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#62]
# Module: 11
#### Step: 03 and 07

Description of issue

Running Virtual machine available memory and Virtual machine free disk space = no results found.

Change Step 3 from this:
Click Example queries in the toolbar, in the Get started with sample queries pane, review each tab, locate Virtual machine available memory, and click Run.

To this:
Click Example queries in the toolbar, in the Get started with sample queries pane, review each tab, locate Track VM availability, and click Run.

Delete Step 11.

![memnoresults](https://user-images.githubusercontent.com/11367710/81485571-e9a68c80-921b-11ea-8fa2-3b145e305b0e.PNG)

![freediskspacenoresults](https://user-images.githubusercontent.com/11367710/81485572-ef03d700-921b-11ea-8901-b1825da3de8a.PNG)

![trackvmavailabilityresults](https://user-images.githubusercontent.com/11367710/81485575-f4f9b800-921b-11ea-941c-5d97e04c6f5f.PNG)

**Comment by polichtm** [comment]
updated
