### ISSUE TITLE
Errors and unfortunate formatting in the course

### ISSUE THREAD

**Issue by mcdoubleyou** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#621]
Hey folks,

I have just done the course and unfortunately there are again differences with the view in Azure in some places, also the wording is very complicated sometimes although the task would actually be quite simple.

In addition, it is not optimal that some info areas are really relevant and helpful but others are actually only optional.
Maybe a distinction could be made here.

I think it would be a good idea to use italics in addition to the bold formatting.
But of course this should be consistent and follow defined rules.
A suggestion here would be to always make the current object italic and bold while the referenced ones are only bold.

EG: Click on _**example Link**_ on **Monitor | Overview**

Optimal would be of course images, because they would lighten the reading flow a bit. But I realize that this is probably not possible.

However, jump marks at each number to save a link when Azure takes a little longer and you skip the current point would also be helpful.

Cheers mcdy

**Comment by staleycyn** [comment]
The instructions are for lab hosters to use in their environment. They often change the formatting and add features like auto typing. If you have a specific issue with an instruction (broken link, UI label is wrong, typo) please write back.
