### ISSUE TITLE
Lab 4 - New interface for ip address spaces and subnets

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#623]
# Module: 04
#### Step: 00

Description of issue
The interface for creating a network with address space, submask and subnets has changed. Instead of adding 10.0.0.0/20 you have to add 10.0.0.0 and specifiy the address space size.

![image](https://user-images.githubusercontent.com/10166617/198019694-646757e1-f5b6-4fcb-9ee4-64413eb61a45.png)

Repro steps:

1.
1.
1.

**Comment by staleycyn** [comment]
Changed to:
1. Click **Next : IP Addresses** and then click **Add an IP Address**. Click **Add** when completed. 

    | Setting | Value |
    | --- | --- |
    | Starting address | **10.40.0.0** |
    | Address space size | **/20 (4096 addresses)** |
