### ISSUE TITLE
Lab 09a, minor phrasing perhaps UI drift, remove "default"

### ISSUE THREAD

**Issue by craigbeeremct** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#625]
# Lab 09a
#### Step 3

Replace:
Leave the default option Scale based on a metric selected and click + Add a rule
With:
Leave the option Scale based on a metric selected and click + Add a rule

The option scale to a specific instance count now appears to be the default option, not scale based on a metric.

**Comment by staleycyn** [comment]
corrected.
