### ISSUE TITLE
Button has been renamed - minor issue

### ISSUE THREAD

**Issue by brentd09** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#627]
# Module: NA
#### Step: 12

Description of issue
The Resize button has now been changed to a save button, the attached picture shows the screen shot.
Repro steps:

1.
1.
1.
![AZ104-Lab3a-03-12](https://user-images.githubusercontent.com/18732050/201789410-a381e4da-07ac-4134-a7e2-7999f0d5d527.jpg)

**Comment by staleycyn** [comment]
Corrected.
