### ISSUE TITLE
Wrong Instruction in lab

### ISSUE THREAD

**Issue by brentd09** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#628]
# Module: NA
#### Step: 04

Description of issue
The lab asks the student to click on "Click Next : IP Addresses and then click Add an IP Address. Click Add when completed."
The option to add an IP address does not exist and the students need to replace the current address with the one in the lab, as they do so the original subnet is removed making the rest of the lab task 1 function normally.
Repro steps:

1.
1.
1.
![AZ104-Lab04-01-04](https://user-images.githubusercontent.com/18732050/201817152-5c2540c3-addf-420f-889e-9aa0ab453769.jpg)

**Comment by staleycyn** [comment]
Corrected.
