### ISSUE TITLE
Network Watcher is not detecting Resource Groups

### ISSUE THREAD

**Issue by brentd09** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#630]
# Module: NA
#### Step: 04

Description of issue
When the students go to the network watcher the instruction to choose the resource group cannot be completed as there are no RGs in the RG pull down box.
Repro steps:
How we over came this issue was to remove the current network watcher and add another watcher in the same region as the previous one. This then show the RG immediately.. After doing some research online it seems to be an issue with the network watchers as others appear to have the same problem. 

![AZ104-Lab06-03-04](https://user-images.githubusercontent.com/18732050/202045063-204471b4-a2b3-40df-a491-c953ab4fe348.jpg)
![AZ104-Lab06-03-04a](https://user-images.githubusercontent.com/18732050/202047270-0a1373f4-a7af-4132-a7e2-f20dce926594.jpg)

**Comment by staleycyn** [comment]
Can you propose a Note that can be added to the lab instructions? And where it should be added. Thanks.

**Comment by brentd09** [comment]
The issue here is that I do not know whether this is a bug with Azure or if by waiting it will eventually show the Resource Group?

However a note could be added: 
If the Resource Group is not listed in the Connection Troubleshooter, it can be populated by:
1. deleting the Network Watcher
2. recreating a new Network Watcher
3. retry the connect troubleshooter again

**Comment by staleycyn** [comment]
Added the note. Thanks.
