### ISSUE TITLE
Mod 06 Error in creating load balancing rule

### ISSUE THREAD

**Issue by ITBlandMCT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#632]
# Module: 06
#### Step: 05

Description of issue
When creating the load balancing rule, the student is instructed to use "**az104-06-pip4**", but the drop-down only lists the **Frontend IP configuration** name, not the pip name (the pip has not been created at this point.) In Step 3, the instruction is to use "any unique name", would there be a problem with naming it something like: "az104-06-lb4-fe1"?

**Comment by staleycyn** [comment]
Have you watched the Interactive Lab Simulation for this lab - https://mslabs.cloudguides.com/guides/AZ-104%20Exam%20Guide%20-%20Microsoft%20Azure%20Administrator%20Exercise%2010.
The load balancer starts at about the 6 min mark. For the rule it says "az104-06-pip4 (to be created)."

**Comment by staleycyn** [comment]
Closing. Write back if still a concern.
