### ISSUE TITLE
App Service PHP 7.4 no longer available

### ISSUE THREAD

**Issue by chris-utter** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#640]
# Module: 09
#### Step: 03

Description of issue
Instructions say to choose PHP 7.4 , which no longer exists.
PHP 8.0 is the oldest version available.
Choosing PHP8.0 grays out Windows OS, which is also in the instructions.

SOLUTION: Choose PHP 8.0 and the Linux OS, EXCEPT the authentication doesn't work with the Linux instance.

**Comment by staleycyn** [comment]
This has been reported (PR #639) and requires further research. If we have a Linux machine, then In Task 5, we will not be able to use Process Explorer to verify. Investigating options.

**Comment by staleycyn** [comment]
Corrected.
