### ISSUE TITLE
Lab 6 Task 6 Step 7 - wrong resource group name?

### ISSUE THREAD

**Issue by TammySmithMCT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#646]
# Module: 06
#### Step: 07

Description of issue
There is no resource group named az104-06-rg

Resource group | az104-06-rg6

Change to:  Resource group | az104-06-rg1

**Comment by SEALTeamA** [comment]
Resource group should me modified to :az104-06-rg6 and not consider :az104-06-rg1

**Comment by staleycyn** [comment]
The architecture diagram shows **rg5** and that is what the lab step shows. I will send a support request to the Skillable vendor to precreate the resource group so it shows in the drop-down.
