### ISSUE TITLE
Wrong name for the frontend Public IP

### ISSUE THREAD

**Issue by brentd09** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#647]
# Module: NA
#### Step: 05

Description of issue
In Step 3 a frontend public IP address was created with a name of the student's choice.

When we get to step 5, the same address is asked for but the name in the lab instructions is wrong, the lab should ask for the the name that the student chose for the front end public address, the name will then show as To be created next to the name.

The lab instruction is misleading. 

Repro steps:

1.
1.
1.

**Comment by staleycyn** [comment]
**Name** was listed twice in Step #3 - Once with the student choice and once with the Step #5 name. I removed the student choice information.
