### ISSUE TITLE
Lab 02A Clean-up fails

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#650]
# Module: 02
#### Step: 00

When learners run the PowerShell cmdlets as printed approx 30-40% of learners see an error message when running the Remove-AzRoleDefinition cmdlet because the assignment to the management group still exists. The reason for this is that the values of array AssignableScope are sometimes in a different order.

What is expected (management group assignment at [0], following the order defined in the JSON):
![image](https://user-images.githubusercontent.com/37703728/211387938-30c07657-e285-4a37-ab63-acd1f0669876.png)

And sometimes it’s the other way around (subscription scope at [0], managementgroup at [1])

Because the cmdlet in step 5 uses the string variable $scope which is filled with only the first element of the returned array of AssignableScopes the following Remove-AzRoleAssignment cmdlet (tries to) remove(s) the assignment at AssignableScopes[0] which will only work as expected when the array has the order managementgroup,subscription. If the order is reversed, then the cmdlet tries to delete a non-existing assignment at the subscription level (which will not present any error or warning message) and that causes the cmdlet Remove-AzRoleDefinition in Step 6 to fail (because an assignment to the MG still exists).

This can be fixed by either parsing the the AssignableScopes for the managementgroup-level scope (recommended):
$scope = (Get-AzRoleDefinition -Name 'Support Request Contributor (Custom)').AssignableScopes | Where-Object {$_ -like '*managementgroup*'}
Remove-AzRoleAssignment -ObjectId '[object_ID]' -RoleDefinitionName 'Support Request Contributor (Custom)' -Scope $scope

 
or as follows (which would try to delete any assignment at each assignable scope and it doesn’t throw an exception if there’s none):

$scope = (Get-AzRoleDefinition -Name 'Support Request Contributor (Custom)').AssignableScopes
$scope | %{Remove-AzRoleAssignment -ObjectId '[object_ID]' -RoleDefinitionName 'Support Request Contributor (Custom)' -Scope $_}

Action: please replace the clean-up PowerShell statements with one of the above to avoid the described error.

**Comment by staleycyn** [comment]
Replaced step #5 with the first set of commands.
