### ISSUE TITLE
Confusing wording in Lab 02a

### ISSUE THREAD

**Issue by ac-cm** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#651]
# Module: 02
#### Step: 05

Description of issue
Step 5 is currently worded as: "Select the Role and click Next. On the Members tab, click + Select members and select your user account az104-********.***.onmicrosoft.com. Click Next and then Review and assign."

This has confused multiple people in class several times thinking they are supposed to select their own account since it says, "select _your_ user".  What would be clearer is if it would say:  "...Select members and select user az104-02-aaduser1.***.onmicrosoft.com"

**Comment by staleycyn** [comment]
Removed the work "your". If that doesn't help, write back. Thanks for reporting.
