### ISSUE TITLE
New resource groups available to see

### ISSUE THREAD

**Issue by jleblancxaf** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#653]
# Module: 02A Manage Subscriptions and RBAC
#### Step: 07

The user the instructions instruct the user to login with does not have access to see any resource groups.

<img width="956" alt="Screenshot_1" src="https://user-images.githubusercontent.com/110999055/212143778-86991971-9f88-4289-8992-b0231bd9df57.png">

**Comment by staleycyn** [comment]
This is on the hosting side and has been forwarded to their support group.
