### ISSUE TITLE
Deletion of AzRoleDefinition not successful

### ISSUE THREAD

**Issue by pkosiol-cc** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#661]
# Module: Administer Governance and Compliance
#### Step: 5

Description of issue
The command `(Get-AzRoleDefinition -Name 'Support Request Contributor (Custom)').AssignableScopes | Where-Object {$_ -like 'managementgroup'}` gives no return. The reason seams to be the filter-condition of the where-object. Without the Where-Object I get the mgmt group and my subscription as result. With the filter I get no return. 

Repro steps:

1. Just run in the code an insert the object_id as discribed

**Comment by staleycyn** [comment]
This was just changed last week. Can you please review this Issue - https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/issues/650

**Comment by pkosiol-cc** [comment]
@staleycyn The Problem is not solved jet. I have attached a screenshot from my cloud-shell session. As you can see without the Where-Object I get 2 objects as a return value. With the Wehere-Objekct there is no return at all. 

When I execute the following command I get a proper result:
`(Get-AzRoleDefinition -Name 'Support Request Contributor (Custom)').AssignableScopes | Where-Object {$_ -like '/providers/Microsoft.Management/managementGroups/az104-02-mg1'}`
It seams like the -like parameter is not working properly. 


![Powershell-error](https://user-images.githubusercontent.com/66460618/212839023-da06fb07-b5f6-48f4-a69d-bfe16975dcfd.png)

**Comment by staleycyn** [comment]
@pkosiol-cc  Changed to use a wildcard - from PR https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/pull/663
