### ISSUE TITLE
Routing configuration of vm1 missing

### ISSUE THREAD

**Issue by pkosiol-cc** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#662]
# Module: Administer Network Traffic Management
#### Step: 9

Description of issue
In task 4 only the vm0 is configured for routing an these steps are missing for the vm1. Therefor the lb will never serve requests to the vm1

Repro steps:

**Comment by staleycyn** [comment]
Not sure what you are seeing. Task 5, Step 4, assigns both vms to the backend pool. Task 5, Step 9, verifies both vms answer.

**Comment by staleycyn** [comment]
No response, closing the issue.
