### ISSUE TITLE
Change in GUI lab 10

### ISSUE THREAD

**Issue by TommyKobber** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#664]
# Module: 10
#### Step: 09

The text states: On the Security Settings blade, note that Soft Delete (For workload running in Azure) is Enabled. Disable Security Features (For workloads running on-premises) and click Save

The text in the GUI states: Enable soft delete and security settings for hybrid workloads. That should be disabled

1.
1.
1.

**Comment by staleycyn** [comment]
Can't replicate. Soft delete is enabled by default on newly created vaults to protect backup data from accidental or malicious deletes. Write back if something else. 
![vault](https://user-images.githubusercontent.com/45440075/213198525-40dcbb10-e62f-41b3-9e40-5e888f4db753.png)

**Comment by TommyKobber** [comment]
Actually, we're both right, depending of where we deploy our RSV.  Please see https://learn.microsoft.com/en-us/azure/backup/backup-azure-enhanced-soft-delete-about#supported-scenarios
I just tested in 2 different regions, first East Us which is one of the preview regions
![preview-eastus](https://user-images.githubusercontent.com/57709815/213212571-c8c8d559-d00c-48c2-891d-4299b16f132b.jpg)

Then West Europe which is not
![ga-westeurope](https://user-images.githubusercontent.com/57709815/213212788-31e30a80-92d8-4002-833f-b97d26a243f1.jpg)

So at some point in the feature my suggestion will give meaning everywhere. For now I think we should leave it

**Comment by staleycyn** [comment]
Thanks for playing along.
