### ISSUE TITLE
New layout - instructions needs an update

### ISSUE THREAD

**Issue by Vincent-MicrosoftTechnicalTrainer-MTT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#665]
# Module: 11
#### Step: 01-04

Description of issue

The Log analytics agent part has been moved to the LOGS tab of the VM, and is not available in the Diagnostic Settings tab anymore (enable guest level monitoring). 

Repro steps:

1.
1.
1.

**Comment by arnoldvilleneuve** [comment]
I am teaching AZ-104 next week. Hope the updates get complete before then.

**Comment by staleycyn** [comment]
Corrected.
