### ISSUE TITLE
LAB 2a

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#673]
# Module: 2a
#### Step: 3-c

Description of issue

Unable to select YES and Save. 

![image](https://user-images.githubusercontent.com/1082625/217356795-b29203f0-01c5-4897-82ae-c8bb9ceed8f0.png)

Lab cannot be completed. 

Repro steps:

1.
1.
1.

**Comment by staleycyn** [comment]
This should be directed to the lab hoster (LODS) help team. The instructions work correctly as shown in the Interactive Lab Simulation link at the top of the lab page.

**Comment by arnoldvilleneuve** [comment]
Hello
You wrote: 
"The instructions work correctly as shown in the Interactive Lab Simulation link at the top of the lab page."
The fact that the Interactive Lab Simulation, a scripted video of a movie, works fine is very nice. I am very happy the lab simulation works.  
However, we are not using the Interactive Lab Simulation but rather doing the real lab and the real lab is not working! 
When it comes to Microsoft lab steps not working Skillable refers me to Microsoft - always. 
I can assure you that all of my students ran into the same issue as I did and documented. You don't have to believe me but I have 16 students who can attest to the same failed results.  
I really hate this finger-pointing. At the end of the day, this is a Microsoft course. 
It is obvious that the Cloudslice account we were provided and the Policies and restrictions associated with it are not correct in the real lab. As we are not using the Interactive Lab Simulation I am not sure how the fact that it works helps out students. 
I will leave it to Microsoft to work with the lab hoster to work out the Issues reported. I have no control over the lab hoster. 
Thank you for your full attention to this Microsoft lab issue. 
Arnold Villeneuve 613-833-0984 

    On Tuesday, February 7, 2023 at 03:39:09 p.m. EST, staleycyn ***@***.***> wrote:  
 
 


This should be directed to the lab hoster (LODS) help team. The instructions work correctly as shown in the Interactive Lab Simulation link at the top of the lab page.

**Comment by arnoldvilleneuve** [comment]
And I would like to remind everyone looking at this that every Student ran into the same issue in Lab02a. It could not be completed. 
That is the important message that I hope is being received.  
Arnold Villeneuve 613-833-0984 

    On Tuesday, February 7, 2023 at 04:42:25 p.m. EST, Arnold Villeneuve ***@***.***> wrote:  
 
 
Hello
You wrote: 
"The instructions work correctly as shown in the Interactive Lab Simulation link at the top of the lab page."
The fact that the Interactive Lab Simulation, a scripted video of a movie, works fine is very nice. I am very happy the lab simulation works.  
However, we are not using the Interactive Lab Simulation but rather doing the real lab and the real lab is not working! 
When it comes to Microsoft lab steps not working Skillable refers me to Microsoft - always. 
I can assure you that all of my students ran into the same issue as I did and documented. You don't have to believe me but I have 16 students who can attest to the same failed results.  
I really hate this finger-pointing. At the end of the day, this is a Microsoft course. 
It is obvious that the Cloudslice account we were provided and the Policies and restrictions associated with it are not correct in the real lab. As we are not using the Interactive Lab Simulation I am not sure how the fact that it works helps out students. 
I will leave it to Microsoft to work with the lab hoster to work out the Issues reported. I have no control over the lab hoster. 
Thank you for your full attention to this Microsoft lab issue. 
Arnold Villeneuve 613-833-0984 

    On Tuesday, February 7, 2023 at 03:39:09 p.m. EST, staleycyn ***@***.***> wrote:  
 
 


This should be directed to the lab hoster (LODS) help team. The instructions work correctly as shown in the Interactive Lab Simulation link at the top of the lab page.

**Comment by arnoldvilleneuve** [comment]
Thank you to the people at Skillable LODS for finding a workaround to this solution so quickly. Much appreciated. 

=============================
You will need to assign the custom role at both the subscription and management group level in order to proceed.

In the Azure portal, navigate back to the MOC Subscription--lod47784992 subscription and display its details.

Click Access Control (IAM), click + Add and then Add role assignment. On the Role tab, search for Support Request Contributor (CustomXXXXXXXX).
 
Select the Role and click Next. On the Members tab, click + Select members and select user account az104-***********.**.onmicrosoft.com. Click **Next and then Review and assign.
 
From here you should be able to proceed with the lab

**Comment by staleycyn** [comment]
Skillable's LODS help desk is 24 x 7 and responds very quickly. I forwarded your problem to them and will close this ticket.

**Comment by arnoldvilleneuve** [comment]
FYI - We have 2 more AZ-104 classes scheduled in Feb. One on the 21st and one on the 28th.

Please either ensure us the cloud slice labs will be fixed for our upcoming events, or advise if we should instead revert to using the Azure Pass version of the labs?

Thank you.

Best Regards,
Dave

David O'Neal
P: +1.703.709.6338 | M: +1.703.489.9996

**Comment by tinodo** [comment]
I have the same issue for 2 participants in my delivery. 1 of them also has the 'green bar' on the instructions. I could not resolve the issue with the steps provided.
