### ISSUE TITLE
Lab 8 - Task 1 - Steps 10 and 11 need to be reversed in their order. 

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#675]
# Module: 8
#### Step: Steps 10 and 11 need to be reversed. They are in the wrong order.
 
![image](https://user-images.githubusercontent.com/1082625/217935021-b4a488dd-8e07-4eac-8418-491a97e50790.png)

If you click Create you will create the VM and not be able to then click on the Template and then Deploy it. 

Description of issue
The steps are out of order. 

Repro steps:

Move step 10 to 11 and current step 11 to 10. 

1.
1.
1.

**Comment by staleycyn** [comment]
Corrected.

**Comment by arnoldvilleneuve** [comment]
Thank you Staleycyn for addressing this issue. Very much appreciated.

**Comment by renaudwangler** [comment]
Sorry, but I think the original order was right : When you click **Create**, the deployment blade opens, which contains a **template** tab. You may click it to access the template used by the first deployment and change it, in order to launch a second deployment...

**Comment by arnoldvilleneuve** [comment]
Steps 11 and 12 (not 10 and 11) are not in the correct order. If you followed the steps as they were and click Create you create the VM and never get the chance to click on the Template tab and then select Deploy. 

16 Students can't be wrong. 

However, your mileage may vary.

**Comment by arnoldvilleneuve** [comment]
I will verify again tonight. 
What I do know is that we had to do what we did in order to get the lab steps to make sense. 
Thank you for your attention to this Renaud. We will get it right in the end so this is a good discussion. 
Arnold Villeneuve 613-833-0984 

    On Friday, February 10, 2023 at 08:54:05 a.m. EST, Renaud ***@***.***> wrote:  
 
 


Sorry to tell you 16 students may be wrong if we don't explain them there is a "template" tab on the Deployment page that appears after the Create button is clicked ;) : please check again (I did check the process and interface before submitting this message : there is no Template link or button but a Download a template for automation link).
Please change back to previous version since the current one makes no sense with the actual interface.
