### ISSUE TITLE
Lab 09c - Implement Azure Kubernetes Service - New Azure option appears on 'Create Kubernetes Cluster' page

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#676]
# Module: 09C
#### Step: 06

Description of issue

At some point recently, Azure has added a new option 'Enable recommended alert rules' to the 'Create Kubernetes cluster' that appears to be selected by default.  This would not normally be a problem, but for ALHs who need to 'cloudslice' their labs, needing this option present will require some additional prep in security/ACPs so as to enable it to work as expected.

If this option is deselected, as seen below, labs run as before:

![image](https://user-images.githubusercontent.com/49700217/218190158-93dfe085-826a-4772-a976-708db0d9920a.png)

**Question:**  If this functionality is not required for the rest of the lab, would it be possible to add a short update to the note immediately after that step indicating to deselect that box?

That could be as simple as adding this to existing 'note':     _Disable "Enable recommended alert rules."_

Thanks for your consideration! :)

**Comment by staleycyn** [comment]
No worries. Try now. Write back if something else needs to be changed.

**Comment by TesterTesterson1004** [comment]
That was perfect, just tested out fine end-to-end (Skillable) and I thank you very much!
