### ISSUE TITLE
Error running PowerShell 

### ISSUE THREAD

**Issue by SATech66** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#678]
# Module: 00
#### Step: 00

Description of issue:  New-AzResourceGroupDeployment: Invalid character after parsing property name. Expected ':' but got: h. Path '', line 2, position 12.

Repro steps:

1.  Tried to find where the issue was, but couldn't find it.
1.
1.

**Comment by staleycyn** [comment]
This GitHub repository is for distributing files to Microsoft Certified Trainers teaching courses. Unfortunately, we are not staffed to provide technical support. Are you in class and can ask your instructor?

**Comment by SATech66** [comment]
I'm in a Udemy course.  I'll try on there to see if they have any answers.
