### ISSUE TITLE
Error on LAB-02, Unable to figure what is wrong 

### ISSUE THREAD

**Issue by nauben00** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#683]
#### Step: 06

Description of issue
New-AzRoleDefinition: Operation returned an invalid status code 'NotFound'
After executing the command 
New-AzRoleDefinition -InputFile $HOME/az104-02a-customRoleDefinition.json
to test I run the JSON file with a wrong subscription ID  and my result was FORBIDEN
so it mean my file  is OK
My Json fil is copied exactly as it is !  IN Task2 Step one 
something wrong in the file ?

**Comment by staleycyn** [comment]
Hello - This GitHub repository is for distributing files to Microsoft Certified Trainers teaching courses. Unfortunately, we are not staffed to provide technical support. Are you in class and can ask your instructor?

**Comment by nauben00** [comment]
no I'm stand alone by doing these labs using UDEMY  !
I was on the impression this github  repertory was for everyone intersted in passing AZ-104 Cert !
I check the interactive labs, and did the same ,  but it is not working for me  !
I was thinking there was an issue in the Json files 
I understand , thank you ! for the answer

**Comment by gottagetgit** [comment]
This lab is creating a custom role.

Custom roles require Azure AD Premium P1 or P2 plan. I suspect this lab cannot be completed by anyone not paying for Azure AD...
