### ISSUE TITLE
Lab 04 - Virtual networking (IP address UX)

### ISSUE THREAD

**Issue by staleycyn** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#687]
# Module: 00
#### Step: 04 -05

UI change

Task 1, step 4: incorrect steps provided. Once you delete the address space, you need to create a new one and the interface do not offer CIDR notation. Same for subnet.

![image](https://user-images.githubusercontent.com/45440075/225029847-5ded1133-7851-4eb8-8672-374ce1aefd85.png)

@msebbane

**Comment by staleycyn** [comment]
@msebbane - Please check to ensure you are not working in the Portal Preview version. The screenshot with starting address and address space size is for the Preview. If there is still a problem, write back. Thanks.

**Comment by devnull-hub** [comment]
@staleycyn Not sure how Portal Preview is being rolled out as I have not changed any of the defaults. What I am presented with and what is being reported is that you can no longer just copy and paste `10.40.0.0/24` this is a drop down box now. User must enter `10.40.0.0` and then select Subnet size. See the following:

![az104-lab04](https://user-images.githubusercontent.com/79267415/225662850-7a35e9a7-76a2-4445-8a2c-745fb01d95dd.gif)

Steps Might be:
Next to the Add a subnet hidden menu select Delete address space then Add an IP address space....

**Comment by staleycyn** [comment]
Made a correction.
