### ISSUE TITLE
Missing Step & Missing Warning: @ Lab 10 / Task 6 / Step 16

### ISSUE THREAD

**Issue by gyssels** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#69]
# Module: 10
#### Step: 16

//***1: Missing Step***//
Description of issue
After downloading the recovery executable file to the download folder, students couldn't Succesful launch the restore after entering the recovery password.
CAUSE:
The file was "Blocked" we should have instruction to right click and "unblock" it or through PowerShell.
Repro steps:
1. Execute all the lab's steps until you find the error on the cmd line window
//***2: Missing Warning***//
Description of issue
When executing the recovery executable file in the download folder, students "astonished "that there a BIG RED WARning that the file could be harmful to their computer.
CAUSE:
The file was "Blocked" we should have instruction to right click and "unblock" it or through PowerShell.
Repro steps:
1. Execute all the lab's steps until you find the warning...

**Comment by polichtm** [comment]
updated
