### ISSUE TITLE
LAB01 Manage AAD identities - tenant creation is failig

### ISSUE THREAD

**Issue by gchoquetMS** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#692]
# Module: 01
#### Step: 10

Description of issue
tenant creation is failing and is inconsistent. Error message " Tenant creation failed. too many requests. please try again later. "
Some participants managed to create the AZ tenant after multiple try. 
 
 Please update or replace the lab steps

**Comment by staleycyn** [comment]
The lab includes this note:

**Note** There is a known issue with the Captcha verification in the lab environment. If you receive the error Creation failed. Too many requests, please try later, do the following:

- Try the creation a few times.
- Check the Manage tenant section to ensure the tenant wasn’t created in the background.
- Open a new InPrivate window and using the Azure Portal and try to create the tenant from there.
- Raise the problem with the trainer, then use the [interactive lab simulation](https://mslabs.cloudguides.com/guides/AZ-104%20Exam%20Guide%20-%20Microsoft%20Azure%20Administrator%20Exercise%201) to view the steps.
- You can try this task later, but creating a tenant isn’t required in other labs.
