### ISSUE TITLE
lab 08 - fails to deploy virtual machine using script extensions

### ISSUE THREAD

**Issue by rykku** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#694]
# Module: Manage Virtual Machines
#### Step: 15

Description of issue
Unable to deploy VM using script extensions, error below appears during the deployment. Can someone test or am I doing something wrong?

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"VMExtensionProvisioningError","message":"VM has reported a failure when processing extension 'CustomScriptExtension'. Error message: \"Command execution finished, but failed because it returned a non-zero exit code of: '1'. The command had an error output of: 'At C:\\Packages\\Plugins\\Microsoft.Compute.CustomScriptExtension\\1.10.15\\Downloads\\1\\az104-08-install_IIS[1].ps1:208 \r\nchar:17\r\n+             Sign&nbsp;up\r\n+                 ~\r\nThe ampersand (&) character is not allowed. The & operator is reserved for future...' For more information, check the instance view by executing Get-AzVmssVm or Get-AzVm (https://aka.ms/GetAzVm). These commands can be executed using CloudShell (https://aka.ms/CloudShell)\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSEWindowsTroubleshoot "}]}

**Comment by staleycyn** [comment]
Hello - This repository is for the distribution of files to Microsoft trainers teaching classes. We are not staffed to provide troubleshooting and help desk support. Please ask your instructor for assistance. Thank you.
