### ISSUE TITLE
Change Lab 02 from assigning RBAC on the management group to assigning RBAC on a resource group under the subscription

### ISSUE THREAD

**Issue by sayedimac** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#695]
# Module: 02
#### Step: 00

Description of issue
In Microsoft we have moved to the Cloud Slice service in the Learnondemand environment for ESI customers. So this lab breaks terribly in that scenario because learners do not have access to the subscription. My suggestion would be to ignore the Management Group aspect of this lab and rather let students create a resource group under the subscription and assign RBAC there.  Failing that the rest of the lab breaks seeing as students in cloudslice share subscriptions. This means students with their own subscriptions will still be able to complete the RBAC aspct of the lab, but cloudslice students will also be able to complete this lab

Repro steps:
Just try the lab in the CloudSlice service - it si impossible and we have had to tell students not to do it for now

**Comment by staleycyn** [comment]
Closing since this is being discussed in an internal Teams chat.
