### ISSUE TITLE
Standard VM username (and passwords though this has been sorted already)

### ISSUE THREAD

**Issue by sayedimac** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#696]
# Module: 4, 5, 6, 7, 10, 11
#### Step: 00

Template Parameter File

I see the VM Admin Password is already removed and the user will be prompted for this during the run, but I believe we should also let the user decide the admin username as opposed to using Student which leaves the subscription open to a dictionary style attack as the username is consistently the same. I only know this because I delivered an AZ-500 course 2 weeks ago and during this time I deployed the VM's from lab 06 for demo purposes. But on the Thursday I deployed Sentinel and within 24 hours all 4 VM's were compromised and multiple (around 300) outgoing RDP connections where created.
So, I believe if we let each user select their own username and password, the environment will be a little more secure than it is with a standard username.

If this is ok, I will update the lab and create a PR if you like?

Repro steps:

1.
1.
1.

**Comment by staleycyn** [comment]
This has been escalated to the cyber defense team. They will review and decide what to do across the courses. Closing for now.
