### ISSUE TITLE
Mod 10 Task 1 step 6 --> creation of VM

### ISSUE THREAD

**Issue by apimparkar11** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#697]
# Module: 10
#### Step: 6

Description of issue: It says to skip step 5 & 6 in the pink box. We need step 6 to create VM for the lab which is not automatically created. Skipping these steps doesnt let learner to continue with the lab and this step should be a mandatory.

Repro steps:

1.
1.
1.

**Comment by staleycyn** [comment]
Mod 10, Task 1, Step 6 does not have a pink box that says to skip certain steps. If this is specific to an Authorized Lab Hosters version, then please log a support ticket with them. If this is something that needs to be fixed on the public instructions, write back. Thanks.

**Comment by TesterTesterson1004** [comment]
I believe this has been fixed @ Skillable - it looks like an alert that had been present to facilitate a cloudslice implementation was updated to reference the right step to skip...
