### ISSUE TITLE
Network Watcher UI change

### ISSUE THREAD

**Issue by ITBlandMCT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#698]
# Module: 06
#### Step: 04

Description of issue
Network Watcher changes

1. At the bottom of the Network Watcher | Connection troubleshoot page, there is a Diagnostic Tests drop-down that either can be ignored, and all 4 tests will run, or we can open it and deselect all and only select "Connectivity".
1. When the Connectivity test runs, the result is either "Success" or "Fail" (Not "Reachable" or "Unreachable").

All of **Task 3** is affected, and **Task 4, Steps 31 & 32**

**Comment by staleycyn** [comment]
Made some changes, see how it goes.
