### ISSUE TITLE
Button has changed from directory to tenant

### ISSUE THREAD

**Issue by TechGuyVincent** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#70]
# Module: 00
#### Step: 00

Description of issue

The +create directory has been changed to +create tenant. 

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
Pls provide the module, exercise, task, and step
rgds
Marcin

**Comment by TechGuyVincent** [comment]
Hi Marcin, 

Its Lab 01 - Task 3, Step 2. 

/V

**Comment by polichtm** [comment]
updated
rgds
Marcin
