### ISSUE TITLE
Lab 08 - Load balance for Scale Set - interface change

### ISSUE THREAD

**Issue by melvinporter** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#701]
# Module: 08
#### Step: 11

Description of issue
Load Balancer interface has changed - instructions do not match the current interface when creating the networking part of the scale set.
![Screenshot 2023-05-12 142257](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/49310608/90807f68-81d6-45c5-9799-0b07cdf67a5f)
![Screenshot 2023-05-12 142404](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/49310608/ad082dc4-2af4-466d-a498-d1e65006221e)

**Comment by melvinporter** [comment]
Task 5 not 6 (apologies)

**Comment by staleycyn** [comment]
fixed.
