### ISSUE TITLE
Virtual network az104-06-vnet01 does not appear in Task 6: Implement Azure Application Gateway

### ISSUE THREAD

**Issue by evaristorivi** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#702]
# Module: 06
#### Step: 07

Description of issue
Virtual network az104-06-vnet01 does not appear in Task 6: Implement Azure Application Gateway
Repro steps:

The other virtual networks appear but not this one.
At the end I complete the lab by replicating the same but in virtual network 3.

**Comment by staleycyn** [comment]
Is there an Issue with the lab instructions that needs to be fixed? Vnet01 was created in Task 1.
