### ISSUE TITLE
No upgrade button

### ISSUE THREAD

**Issue by evaristorivi** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#704]
# Module: 08
#### Step: 11

Description of issue
Right at that moment there is no upgrade button.
![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/34553420/38fc71b4-1971-4026-aad0-ff284538a433)

**Comment by staleycyn** [comment]
Is there something that needs to be fixed?

**Comment by evaristorivi** [comment]
It is not possible to continue the laboratory from this point onwards, having carried out all the above steps.

**Comment by staleycyn** [comment]
Please review this issue: [Issue 705](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/issues/705 )

Perhaps you missed a step? If you are in class, can you ask your instructor?

**Comment by evaristorivi** [comment]
> Please review this issue: [Issue 705](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/issues/705)
> 
> Perhaps you missed a step? If you are in class, can you ask your instructor?

Yes, this helped, "Orchestration mode: Uniform" made the Upgrade button appear. Thanks.
