### ISSUE TITLE
Redundant step?

### ISSUE THREAD

**Issue by TechGuyVincent** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#71]
# Module: 01
#### Step: 04

Description of issue

In the cleanup part (step 4 of the cleanup) it mentions that one should remove the license bind, but the license itself has been removed prior, so it feels like either they should switch places or be removed.  

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
Can you clarify what you mean by "the license itself has been removed prior" ?
rgds
Marcin

**Comment by TechGuyVincent** [comment]
If we delete the users beforehand then the licenses should be made available automatically? Would it be neccessary to actually remove the licenses from the users before/after the deletion of the useraccounts that hold these licenses? Isn't it enough just removing the users?

**Comment by polichtm** [comment]
Valid point - updated
rgds
Marcin
