### ISSUE TITLE
lab 09a - no "run history" tab

### ISSUE THREAD

**Issue by arieluchka** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#710]
# Module: Lab 09a - Implement Web Apps
#### Step: 13-14

Description of issue
there is no "run history" tab. maybe it moved to another place?

Repro steps:

1.
1.
1.

**Comment by staleycyn** [comment]
Cannot reproduce this problem. Use this page to see the tab - https://learn.microsoft.com/en-us/azure/azure-monitor/autoscale/autoscale-get-started#view-the-scale-settings-for-your-resource. If you are in class, please ask your instructor for help. This repo is just for distributing lab instructions. Thank you.
