### ISSUE TITLE
AZ-104 Slides

### ISSUE THREAD

**Issue by timrae-7917** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#712]
Hi Team

Planning on teaching this next week and had to make a bunch of slide to flow with MS Learn.

Ill be teaching again in August and wondering if the course writes will be updating the slides in Late June/July/August at all?
Forward planning reasons mainly,
Yet to test labs tomorrow and Monday and will feedback of any issues.

**Comment by staleycyn** [comment]
Hello - There will be a course update in last July. However, there are no plans to exactly match the slides to the Learn pages. Feedback on the labs are always welcome.
