### ISSUE TITLE
Front end IP has wrong name in the lab 06 step 05

### ISSUE THREAD

**Issue by brentd09** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#714]
# Module: NA
#### Step: 06

Description of issue
The lab shows that the FrontEnd IP is: az104-06-pip4

When it should be az104-06-fe4

Repro steps:
![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/18732050/467e20f4-815d-44b6-90a6-bad4480a1f70)

1.
1.
1.

**Comment by staleycyn** [comment]
Corrected. Thanks.
