### ISSUE TITLE
Lab 04 is broken due to change in  Public IP creation  issue

### ISSUE THREAD

**Issue by prabhjotsinghbakshi** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#715]
Lab 04 is broken due to change in  Public IP creation  issue

**Comment by staleycyn** [comment]
This has been reported in Issue  https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/issues/713. It has the details of what will be fixed.
