### ISSUE TITLE
AZ-104 Labs 1 and 2 are a bad first impression

### ISSUE THREAD

**Issue by jaspar-blue** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#717]
# Module: 01
#### Step: 07

Description of issue
There is already a warning bang to notify there is a known issue where lab participants may be prompted for a Captcha.
Since this is the first lab, and for many learners the first ESI course. We are really giving a BAD first impression. 
There must be a way to create the lab instances with a maximum number of redemption keys per lab and set it to no more than 10.
This should avoid the issue all together.

Repro steps:

![2023-06-20 14_19_53-Manage Azure Active Directory Identities - Work - Microsoft​ Edge](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/137176588/481351ab-bd59-4a77-aac9-4b6be84b57ff)

1.
1.
1.

**Comment by staleycyn** [comment]
I will open a ticket with the lab hoster. Closing here.
