### ISSUE TITLE
Lab01-Task04-Step02-Step06

### ISSUE THREAD

**Issue by sumahmud** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#723]
# Module: 01
#### Step: 2, 6

Description of issue
Azure portal UI for creating a user has been changed.
Now the user creation page has 4 steps:
Basics, Properties, Assignments, Review + Create
<img width="501" alt="image" src="https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/58412718/3c4f2de8-41a4-42cb-b8cc-2e5dd0172e58">

**Previously, all steps were placed in a single page.

Repro steps:
1. Go to users under manage section in AAD page and create a new user.

**Comment by staleycyn** [comment]
Corrected.
