### ISSUE TITLE
(Lab01-Task04-Step04) instructions improvement request

### ISSUE THREAD

**Issue by sumahmud** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#725]
# Module: 01
#### Step: 04

Description of issue
It created confusion to the learners which directory they need to switch back as there are 3 directories available.
Please add the directory name in the instructions. The name of the directory is "First AAD". 
<img width="628" alt="image" src="https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/58412718/abbd483b-e97a-42c8-9d48-ca27c1323074">

Repro steps:

1. Go to Directory + Subscription (directly to the right of the Cloud Shell button) in the Azure portal toolbar.

**Comment by staleycyn** [comment]
I believe the name of the default Azure AD tenant depends on the which Authorized Lab Hoster you are using. That is why we do not provide a specific name.

**Comment by sumahmud** [comment]
However we must use "First AAD" tenant to complete the instructions stated in Task 4-Step4. So it might be better to say explicitly that we need to switch to First AAD.

**Comment by staleycyn** [comment]
Made a change.

**Comment by sumahmud** [comment]
I am sorry to say that your change need a correction. You added "first" only in the bracket which is not correct. 
<img width="756" alt="image" src="https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/58412718/6617fca6-16f7-472c-9252-ca4b6d3678a5">

It should be **"First AAD"** because the user will create a tenant called "First AAD" in the very beginning of the lab and that tenant will be used to create a user.

**Comment by staleycyn** [comment]
Which lab hoster are you using? Can you send a screenshot?

**Comment by sumahmud** [comment]
<img width="339" alt="image" src="https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/58412718/4bdaa482-3cf3-4ec2-84a0-443f58c29805">
