### ISSUE TITLE
Lab 6 Health Probe

### ISSUE THREAD

**Issue by jourdanparham** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#728]
# Module: 06
#### Step: 06

Description of issue: When configuring the inbound rules for the Azure Load Balancer, learners are instructed to create a new health probe with the following details:
Name: az104-06-lb4-hp1
Protocol: TCP
Port: 80
Interval: 5
Unhealthy threshold: 2

However, "unhealthy threshold" is no longer a parameter to configure. Without this as an option, the 2 VMs will not display when refreshing the browser. I believe this is because what is considered an unhealthy probe is now automated based on the docs (https://learn.microsoft.com/en-us/azure/load-balancer/manage-probes-how-to): 
"Regardless of configured time-out threshold, HTTP(S) load balancer health probes will automatically mark the instance as down if the server returns any status code that isn't HTTP 200 OK or if the connection is terminated via TCP reset." Below reflects the current health probe options:

![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/21994425/22525029-32f5-40cf-9e1b-a563e5d563e6)

**Comment by staleycyn** [comment]
Removed the unhealthy threshold instruction.
