### ISSUE TITLE
Confusing description

### ISSUE THREAD

**Issue by TechGuyVincent** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#73]
# Module: 07
#### Step: 09

Description of issue

One should remove "On the Storage account blade, in the Settings section, " since it can raise confusion if the users are in the right place. I would suggest to just remove that part and let the rest be. Or specify the whole way such as SA blade->Settings->Configuration. 

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
Settings section is on the storage account blade. Would you mind clarifying what in particular are you finding confusing about it? 
Are you suggesting that a student might be already looking at the content of the storage account | Settings blade? If so, how did the student end up there?
rgds
Marcin

**Comment by TechGuyVincent** [comment]
Hi Marcin! 

Ah ok, sorry - I think I see the issue. 

There is a mixup between the replication within the configuration settings vs the geo-replication settings in the settings blade. Maybe on should just specify the "Geo-Replication option" or something similar. I think when students are still in the configuration tab reading the instructions they might think its the replication selection WITHIN the configuration settings. 

Hope that makes sense :) 

/V

**Comment by polichtm** [comment]
That is still "On the Storage account blade, in the Settings section, " - isn't it ;) - as per the following image:
![image](https://user-images.githubusercontent.com/10284906/82729933-e4404c00-9cc9-11ea-83d6-eefc2398e3ca.png)

Appreciate the suggestion, but, as far as I can tell, the current version is accurate...
rgds
Marcin
