### ISSUE TITLE
Step Missing in lab 12a task 6

### ISSUE THREAD

**Issue by brentd09** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#731]
# Module: 00
#### Step: 12-13

Description of issue
12. Minimize the Cloud Shell pane (but do not close it) and, on the web app blade, in the Settings section, click Scale out (App Service plan).
13.  Select the Run history tab, and check the Observed resource instance count.

The "Run history tab" that is mentioned in step 13 does not appear until you click on the "Autoscale Settings" 
This needs to be added as a step between 12 and 13 to make sense of the lab instructions.

**Comment by staleycyn** [comment]
Corrected.
