### ISSUE TITLE
Lab 07 Ex 1 Task 5 - File share creation fails due to new default backup setting

### ISSUE THREAD

**Issue by SkillableMG** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#732]
* Lab 07 - Manage Azure Storage
* Exercise 1
* Task 5: Create and configure an Azure Files shares
* Step 2

Azure portal has added a new default configuration when creating file shares that currently results in a failure to create the file share specified at the above-referenced step within the lab hosting environment.

The **Enable backup** checkbox on the **Backup** tab is now checked by default, resulting in the the attempted creation of a key vault resource along with the file share. Because the key vault resource is not permitted by lab policies, file share creation fails to validate.

As backup does not need to be enabled to perform lab activities, we propose that the instructions be updated to require the user to uncheck the **Enable backup** box.

![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/134323425/58cf853a-8c9d-452a-bc42-749f65560a4f)
![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/134323425/2db06209-aaa9-4843-9426-2a971c4d2c1d)

https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/blob/25eeda45f615b816c6d7a3612b6faa95956d8b8f/Instructions/Labs/LAB_07-Manage_Azure_Storage.md?plain=1#L236-L241

**Comment by staleycyn** [comment]
Corrected. Thanks for reporting.
