### ISSUE TITLE
user is already created in the lab environment

### ISSUE THREAD

**Issue by sumahmud** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#735]
# Module: 02
#### Step: 02

Description of issue
User is already created in the lab environment. So learners do not need to create any.
Please add an instruction to let the learners know that learners do not need to create an user in case it already exists.

Repro steps:

1.
1.
1.

**Comment by staleycyn** [comment]
Which Authorized Lab Hoster are you using? If the hoster already has the user created, please submit a help desk ticket with them. Not all hosters create the user.

**Comment by sumahmud** [comment]
We are using Cloud Slice.

**Comment by sumahmud** [comment]
At least, if you leave a message like "please check if the user is already created", that will be kind to the learners. 
Expect your consideration.

**Comment by staleycyn** [comment]
If the message is only needed in the cloud slice version, then ask the Lab Hoster to add a note. This public GitHub is for all authorized lab hosters. Many of them do not use cloud slice.
