### ISSUE TITLE
Lab 6 - error with Task 1 - Unexpected character encountered while parsing value

### ISSUE THREAD

**Issue by rykku** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#736]
# Module: [AZ-104-MicrosoftAzureAdministrator](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator)
#### Step: 6

Error in task 1, step 6. when deploying vm in powershell error appears below.

PS /home/x> New-AzResourceGroupDeployment `                                                                             
>> -ResourceGroupName $rgName `
>> -TemplateFile $HOME/az104-06-vms-loop-template.json `
>> -TemplateParameterFile $HOME/az104-06-vms-loop-parameters.json
New-AzResourceGroupDeployment: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

**Comment by staleycyn** [comment]
Please ask your instructor for assistance. Please ensure there are no spaces or return characters in the command line.
