### ISSUE TITLE
Additional instruction is required

### ISSUE THREAD

**Issue by sumahmud** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#741]
# Module: 09
#### Step: 13

Description of issue
There is no autoscale settings in the page.
We need to open Manage Rules Based Scaling as showed in the screenshot to open the autoscale page.
<img width="1122" alt="image" src="https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/58412718/04548c12-13c5-4dec-a73b-beccb4d825af">

So additional step is required like **"please select "Manage rules based scaling" to open the autoscaling page."** 

Repro steps:

1. Go to scale out (App Service Plan)

**Comment by renaudwangler** [comment]
Please refer to your lab hoster, since the modification you suggest is allready in the curent lab instructions in this repository ;)

**Comment by staleycyn** [comment]
These are the instructions?

![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/45440075/dc2d1f44-593a-4386-bbed-7816b4f94dd1)

**Comment by sumahmud** [comment]
Thanks for the confirmation. Labs are updated already. Please close the issue.
