### ISSUE TITLE
New Lab 09c does not match the UI

### ISSUE THREAD

**Issue by ITBlandMCT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#744]
# Module: 09
#### Step: 06

Description of issue
New Lab does not match the UI
- After clicking **OK** for the environment, the student needs to click **Create** to return to the Container App creation screen.
- After **Step 6**, the student must designate a Container Registry and Image before they can create the Container App. (**_mcr.microsoft.com/azuredocs/containerapps-helloworld:latest_**, I presume)
- The Ingress tab _should_ be completed so we can verify the container app is running.
- Why not connect to the container?

**Comment by staleycyn** [comment]
Made some changes, should be better. If not, write back.

**Comment by ITBlandMCT** [comment]
Fantastic! Thanks.
(In Task 2, Step 3 there seems to be an extra "*")

**Comment by staleycyn** [comment]
Found it and fixed it.
