### ISSUE TITLE
Knowledge-check questions on lab08 of AZ-104 need change

### ISSUE THREAD

**Issue by noraelmesbahi** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#746]
# Course: AZ-104 Azure Administrator
### Lab/Demo: Lab08 [Implement Intersite Connectivity]

Description of issue: The knowledge check questions at the end of the lab most of them are related to VPN/ER and vWAN which are not part of the scope of the course anymore. So they would need to be changed.

**Comment by staleycyn** [comment]
This was referred to the lab hoster, so it will be closed here.
