### ISSUE TITLE
Created user az104-aaduser-xxx unable to view Resource Groups/All Resources

### ISSUE THREAD

**Issue by aniok-msft** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#750]
# Module: 02
### Tasks / Steps: Tasks 01(Step 03) and Task 3 (Steps, 06-08)

Description of issue

Task 01 **Implement Management Groups** / Step 03
I did NOT see the message “You are registered as a directory admin but do not have the necessary permissions to access the root management group”.

Task 03 **Assign RBAC roles** / Steps 06-08
While the Properties blade says user (az104-02-aaduser-xxxxx) can manage access to all Azure subscriptions and management groups in this tenant [see screenshot below, No is greyed out], when I sign as user az104-02-aaduser-xxxxx in an InPrivate session, I cannot see any Resource Groups or Resources (i.e. steps 7 & 8)

If you do NOT see the message above in Task 01, Step 3, is “Yes” supposed to be the selected under the “Access management for Azure resources” section albeit greyed out?

What is the workaround in this scenario? Learner is unable to complete the rest of Task 3 for this lab

[Lab 2 issues (screenshot).docx](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/files/12389378/Lab.2.issues.screenshot.docx)

**Comment by staleycyn** [comment]
I cannot reproduce this issue. If you are a MSFT FTE, please use our Teams Collaboration channel to get assistance from your peers.  Or you can retry the steps in the case of a temporary problem. Or you can ping the LODS help desk to see if anyone else has reported the problem. Write back.
