### ISSUE TITLE
Lab 9A - potential issue, not prompted for creds

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#754]
# Module: 9A
#### Step: 06

Description of issue

I'm not particularly savvy with the underlying tech for this lab, but I noticed something odd when testing it just now:  In **Exercise 1/Task 4/Step 6**, I consistently got the error _"...fatal: could not read Username for '<URL>': No such file or directory..."_, and I was never prompted for credentials.

I took the lab several times, being careful to follow instructs verbatim to create the webapp, staging slot, and use the URLs correctly, but these tests all saw same issue consistently. 

 I _could_ get by this issue if I substituted (in Step 5) this format, where I am supplying the user/pwd in the URL:

git remote add [deployment_user_name] https://[deployment_user_name]:[deployment_user_name_password]@[the rest of the URL]

i.e.

git remote add mydeploymentusername https://mydeploymentusername:mypassword@webapp########-staging.scm.azurewebsites.net:443/webapp########.git

**Comment by kumud-sharma** [comment]
I am also facing the same issue

**Comment by qanh798gm** [comment]
Me too :((

**Comment by akn9050** [comment]
Hi @whoami-anoint , @polichtm @staleycyn, is anyone checking on this issue?  A large audience is doing AZ-104 labs.

**Comment by staleycyn** [comment]
There is a known issue with git authentication. 

Task 4, step 6, now requires the credentials to be passed with the push command. 

Task 3, step 4, reminds you to select a user and pwd that can be used in the URI.
