### ISSUE TITLE
Lab 01 - Trial name has changed from 'Azure Active Directory Premium P2' to 'Microsoft Entra ID P2' in one Step

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#757]
# Module: 01
#### Step: 05

Description of issue

Although the previous steps still have the item called **'Azure Active Directory Premium P2'**, once it has been assigned it appears to have been renamed to **'Microsoft Entra ID P2'**, so this step may need to be updated:

![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/49700217/e3cdf702-0d93-48e3-ad15-6339ff79d0fd)

Uncertain if (as time goes on) the previous references to 'Azure Active Directory Premium P2' will also be changing...probably.

**Comment by staleycyn** [comment]
Corrected.
