### ISSUE TITLE
Module 8 Storage Account and VMSS Extension Issue

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#77]
# Module: 08
#### Step: 04

Description of issue
The lab has us create a Storage Account and upload a script file to it early in the lab to use to add a Script Extension to a VM.  That works fine since the VM and the Storage account are in the same region.  Later in step 6 we are working with a Virtual Machine Scale Set that was to be created in a different Region than the VMs earlier.  That is where the problem is. The Scale Set is to add an Script Extension from the same storage which can NOT be done if in a different Region. 

My solution is to NOT put the Virtual Machine Scale Set in a different Region as mentioned in Step 5.  It should use the SAME Region. Then it should work fine. I am not sure why the different Region requirement is used..

Cheers,
Jeff Smalley MCT
Chicagoville

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
Hi Jeff,
as far as I recall, that's intentional in order to minimize the possibility of hitting the vCore limits. To remediate, it was sufficient to add a boot diagnostics storage account to the VMSS provisioning process
rgds
Marcin

**Comment by JeffSmalley** [comment]
I am not sure adding a Boot Diagnostics Storage Account fixes anything.  We need to add a file in the VMSS via a Storage Account. That Storage Account is not accessible if the VMSS is in a different Region than the Storage Account. The instructions don't work. Either we have to create a new Storage Account in the new region and upload the needed files or we need to create the VMSS in the same region of the original Storage Account...

Jeff

**Comment by polichtm** [comment]
Hi Jeff,
Boot Diagnostics storage account for a VMSS resides in the same region as VMSS.
Rgds
Marcin

**Comment by JeffSmalley** [comment]
Okay, I see where you are going with adding Boot Diagnostics.  It still doesn't help since the lab has you download a file from the storage account added earlier. The new Storage Account made with a Boot Diagnostics won't have the file we needed. One way or another the lab needs to be fixed.  

My suggestion is to delete the first 2 Virtual Machines that are made at the beginning of the lab, then add the Virtual Machine Scale Set in the SAME Region of the original Storage Account. That way we don't have issues with vCPU limits and don't have any issues with re-uploading the file needed to add the Extensions to the Scale Sets.. Once we start with the Scale Sets, the original 2 VMs are not used any more.

Cheers,
Jeff

**Comment by polichtm** [comment]
Hi Jeff,
appreciate the suggestion - instructions have been updated to account for the need to upload the configuration script to the second storage account. Hope this works for you...
Deleting VMs in between the exercises could potentially introduce an extra wait time...
rgds
Marcin

**Comment by JeffSmalley** [comment]
Marcin,
Does the vCPU limits enforce VMs that are deallocated?  If not, the lab could just have the VMs shutdown before the Scale Sets are created..

Trying to keep things simple as possible. :)

Jeff

**Comment by mpolicht** [comment]
Hi Jeff,
understood...
unfortunately even deallocated VMs count towards the quota limits
rgds
Marcin
