### ISSUE TITLE
Mismatch diagram vs. instruction

### ISSUE THREAD

**Issue by anrdemuc** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#780]
# Module: 00
#### Step: 06

Description of issue
The Architecture diagram 
refers vNet **az104-8-vnet1** 10.80.0.0/20
Instructions 
refers vNet **az104-08-rg01-vnet** 10.80.0.0/20

Repro steps:
1.
![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/93244949/a8541982-5282-4bb3-9117-78b3a7846920)

**Comment by staleycyn** [comment]
corrected the lab instruction.
