### ISSUE TITLE
Lab 03b - Manage Azure resources by Using ARM Templates

### ISSUE THREAD

**Issue by AaronSaikovski** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#79]
Lab error/missing step - AZ-104
Lab 03b - Manage Azure resources by Using ARM Templates
Task 2: Create an Azure managed disk by using an ARM template
step 9: Back on the Custom deployment blade, specify the following settings:
disk size should be 32 not "32" - should be called out. if you include the "" then the deployment fails
missing encryption type setting - should be platform

**Comment by polichtm** [comment]
Hi Aaron,
There is no indication that that entry should include double quotes
rgds
Marcin
