### ISSUE TITLE
Forgotten Colon in Code Snippet

### ISSUE THREAD

**Issue by wamikabro** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#795]
# Module: web-development-101-arrays
#### Step: 2

Description of issue
In the 4th line of example code snippet, colon is missing after the word "price"

Repro steps:
https://learn.microsoft.com/en-us/training/modules/web-development-101-arrays/
1. Navigate to the web-development-101-arrays module.
2. Access the 5-exercise-operations lab/demo.
3. Select the task titled "Build your business."
4. Proceed to Step 2.
5. Locate the 4th line of the example code snippet.
6. Observe that a colon is missing after the word "price" in that line.

**Comment by staleycyn** [comment]
I think this is posted in the wrong GitHub repository. We do not have a lab like this.
