### ISSUE TITLE
lab 9a task 6 part 5

### ISSUE THREAD

**Issue by AaronSaikovski** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#80]
there is a typo in lab 9a task 6 part 5 - looks like a copy paste job from lab 8
Click Add and, back on the az10408vmss0 - Scaling blade, specify the following settings (leave others with their default values):
should be App services plan scaling

**Comment by polichtm** [comment]
valid point - updated
rgds
Marcin
