### ISSUE TITLE
Missing Interactive Lab on AZ104 Lab 09c

### ISSUE THREAD

**Issue by tkboisvert** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#809]
# Module: AZ-104
## Lab/Demo: 9c

Description of issue

The ineractive lab is missing from the guide, but still can be accessed here:

https://mslabs.cloudguides.com/guides/AZ-104%20Exam%20Guide%20-%20Microsoft%20Azure%20Administrator%20Exercise%2015

**Comment by staleycyn** [comment]
Lab 09c is Container Apps. There isn't an interactive lab guide. Kubernetes was removed from the exam and there is no longer a lab about that.
