### ISSUE TITLE
AZ104_Lab 11 - Implement Monitoring

### ISSUE THREAD

**Issue by darlingtonogbuefi** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#810]
# Module: AZ104
#### Step: 00

Description of issue: most of the instructions in Task 7: Review Azure Log Analytics functionality  (Lab 11 - Implement Monitoring) probably needs to be updated or the description/illustration needs to be improved upon...because it seems the steps/titles used in the task are outdated/do not exist in the current azure monitor layout. 
I could not find the "Track VM availability", "VMComputer "

Repro steps:

1.
1.
1.

**Comment by staleycyn** [comment]
This lab will be updated as part of a new set of proposed labs. Thanks.
