### ISSUE TITLE
Module 02 Lab times need to be extended

### ISSUE THREAD

**Issue by rtrader58** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#812]
# Module: 02 Labs

Length of time for the all of Module 2 labs is not sufficient.  Even after extending the allotted number of times.  

Most of my students timed out and cancelled before they could finish the lab.  This made it very frustrating to the student.  Even after launching the labs a second time most students were still unable to finish the lab before it cancelled.

Extend the lab time.

**Comment by staleycyn** [comment]
Please submit a support ticket to the lab hoster. They control how long the lab is active.  I doubled the time estimate on the GitHub pages, but not all hosters use that information. If you provide the lab hosting environment, I can try to find their support desk email.
