### ISSUE TITLE
Lab 4 : domain name is already in use when associating the IP address

### ISSUE THREAD

**Issue by gchoquetMS** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#814]
# Module: 00
#### Step: domain name is already in use

Description of issue
When in the Configuration Details ensure the name is az104-04-pip1. it says the domain name is already in use when associating the ip address. Work around : create a new IP Address. 
Impact all participants.

**Comment by MSFT-MarcoEs** [comment]
![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/38212502/6506a3f3-9980-498d-9c59-85c30ccbc7df)

**Comment by MSFT-MarcoEs** [comment]
Another resolution is to associate it from the Public IP instead from the NIC

Error image:
![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/38212502/03a8ff3f-fef3-4fd5-9698-23843f1ad21f)

**Comment by SkillableMG** [comment]
We have also confirmed this issue at step 15 of Task 3, and again at step 21 for the other NIC.

It appears most likely that this is a new Azure portal bug, as the "domain name is already in use" error shows up when the default (new) IP is selected, and the message does not clear or change when the correct `az104-04-pip0` is selected instead. The displayed conflicted domain name matches the name of the default (new) IP. 

![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/134323425/f390904c-2569-40f5-adf6-86a7653c1d96)
![inlineImage](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/134323425/6df10670-7e98-42ed-9b67-9f7b4e40e2be)

The `az104-04-pip0` and `az104-04-pip1` resources have no domain name set and were created without issues.

We also were able to work around this error message by configuring the NICs in Cloud Shell with the below commands, replacing Task 3 steps 10-22.

```
$nic0 = Get-AzNetworkInterface -Name az104-04-nic0 -ResourceGroupName az104-04-rg1
$pip0 = Get-AzPublicIpAddress -Name az104-04-pip0 -ResourceGroupName az104-04-rg1
Set-AzNetworkInterfaceIpConfig -Name ipconfig1 -NetworkInterface $nic0 -PublicIPAddress $pip0
$ipc0 = Get-AzNetworkInterfaceIpConfig -Name ipconfig1 -NetworkInterface $nic0    
$ipc0.PrivateIPAllocationMethod = 'Static'
Set-AzNetworkInterface -NetworkInterface $nic0

$nic1 = Get-AzNetworkInterface -Name az104-04-nic1 -ResourceGroupName az104-04-rg1
$pip1 = Get-AzPublicIpAddress -Name az104-04-pip1 -ResourceGroupName az104-04-rg1
Set-AzNetworkInterfaceIpConfig -Name ipconfig1 -NetworkInterface $nic1 -PublicIPAddress $pip1
$ipc1 = Get-AzNetworkInterfaceIpConfig -Name ipconfig1 -NetworkInterface $nic1    
$ipc1.PrivateIPAllocationMethod = 'Static'
Set-AzNetworkInterface -NetworkInterface $nic1
```

**Comment by staleycyn** [comment]
added a note.

**Comment by microsmith** [comment]
It is not sufficient to just add a comment "this is a known issue. You will need to locate the public ip address and associate it to the NIC separately."  The actual steps to do this need to be added to the lab.

**Basics...**
* Go to "Public IP addresses"
* Click "az104-04-pip0"
* In the Overview pane click "Associate IP"
* Set "Resource type" to "Network interface"
* Set "Network interface" to "az104-04-nic0" 
* Repeat for "az104-04-pip1" and "az104-04-nic1"

**Comment by staleycyn** [comment]
Added.
