### ISSUE TITLE
Confused on existing and New instructions

### ISSUE THREAD

**Issue by akn9050** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#821]
Hi @staleycyn 

Confused on existing and New instructions, which one is aliening with Az-104 exam? will there be any more updates to new instructions or final content is pushed here?

Thanks,
Amit Kumar

**Comment by staleycyn** [comment]
The New Instructions folder is where our proposed new labs are being stored. After the labs are reviewed/approved, we will announce a course update and set a date to cut over. On that day contents of the folder will be moved to the Instructions folder, and these will become the new course labs. This week we will start requesting the reviews. If you still have a question, write back.

**Comment by staleycyn** [comment]
Closing. Feedback on the new labs is welcome.
