### ISSUE TITLE
Lab 04 - Implement Virtual Networking subnet issue

### ISSUE THREAD

**Issue by microsmith** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#822]
# Module: 00
#### Step: 04 and 05

Description of issue

Step 4 says "Be sure to click Add. "
* There is no "Add" at this point.

Step 5, adding the new subnet.
* The value 10.40.0.0/24 overlaps the auto-added "default" subnet.
* **The "default" subnet needs to be deleted first.**  (or "default" needs to be edited and renamed to "subnet0")

**Comment by staleycyn** [comment]
Corrected.
