### ISSUE TITLE
Cloud PowerShell gives status code 'Forbidden'

### ISSUE THREAD

**Issue by isprenkle** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#823]
# Module: Administer Governance and Compliance
#### Step: 6

Description of issue
The json cannot be used as the InputFile. It gives the following error:
New-AzRoleDefinition: Operation returned an invalid status code 'Forbidden'
The user being used for this process has Owner rights on all resources.
Repro steps:

1. Edit the provided file, mentioned in Step 1.
2. Upload the file after editing it.
3. Enter the command given in Step 6.

When attempting to upload the json in the Portal GUI, it gives the error "Invalid JSON content - Malformed JSON: "properties" property not present or value is null."
It seems the labs have not been properly updated for the current version of Azure and should be marked as unavailable until all guides have been confirmed as still operational.

**Comment by staleycyn** [comment]
We cannot reproduce this error. The JSON file is used in the Cloud Shell not in the Portal. Can you ask your instructor for assistance?

![az-defn](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/45440075/211f6866-5562-4301-8513-a37305c9a15c)
