### ISSUE TITLE
Instructions and New instructions

### ISSUE THREAD

**Issue by kramit** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#833]
Why is there now Instructions and 'new instructions' Did someone push to master and included something they shouldn't have here?

# Module: 00
#### Step: 00

Description of issue

Repro steps:

1.
1.
1.

**Comment by staleycyn** [comment]
Please follow the MCT thread on a course update for 23 February - https://techcommunity.microsoft.com/t5/courseware-information/mct-feedback-needed-az-104-new-proposed-labs/ba-p/4033688.

Also, review Issue #821 -  https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/issues/821
