### ISSUE TITLE
New Instructions: Lab 10 - Implement Data Protection

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#836]
# Module: 0?
#### Step: 07

Description of issue

This seems like an 'Azure has updated its UI since instructions were originally written' issue:  When I run through a test Cloudslice QA of this lab, once I encounter this step I'm seeing that it has a different UI then the instructions seem to anticipate.

For example, there is a 'Basics' tab, but no 'Source' tab, that I can see.  There does not appear to be an 'Enable Replication' button on this page, and while at least some of the items referenced to configure in Step 7-12 appear to have an entry on the 'Advanced Settings' tab, it may be a good idea to update the Instructions to 100% match how Azure looks now.  

Here is an example of the UI that I see at this point: 

![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/49700217/b704cf1a-eb70-4491-8156-4ac3fad21f23)

**Comment by staleycyn** [comment]
Good catch. There were some old steps that needed to be removed. Should be all better now. Please try again and write back.

**Comment by TesterTesterson1004** [comment]
That did the trick, thank you...issue resolved!
