### ISSUE TITLE
New Instructions: Lab 11: Implement Monitoring

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#841]
# Module: 0?
#### Step: 08

Description of issue

Can you double-check the code block in this step?  A recent QA indicated that _"The query provided results in an error:"_

![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/49700217/a191e067-ecbd-43e0-b60d-734074f9923d)

and subsequently: _"...When removing the backslash listed as the cause of the error, a new error is produced."_

![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/49700217/63c5755f-831f-41a1-a451-7c49d85cadf8)

Repro steps:

Take lab as-written

**Comment by staleycyn** [comment]
Good catch. Replaced the query and added a link to the Log Analytics Demo Environment (in case they aren't getting enough results). Also, reminder tomorrow morning (0700-0800 PST) I will be updating the Instructions folder with all the new files.

**Comment by TesterTesterson1004** [comment]
Thank you, that should do the trick!  (and I am ready for release! :)
