### ISSUE TITLE
New Instructions - Lab 02b - Manage Governance via Azure Policy (very minor issue)

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#842]
# Module: 0?
#### Step: 05

Description of issue

Text says:

_In the **Enter resource group name to confirm deletion** textbox provide the resource group name, `rg-lock`. Notice you can copy and paste the resource group name._

Should reference RG name like so:

_In the **Enter resource group name to confirm deletion** textbox provide the resource group name, `az104-rg2`. Notice you can copy and paste the resource group name._

**Comment by staleycyn** [comment]
Good one. All better.
