### ISSUE TITLE
New Instructions -  Lab 05 - Implement Intersite Connectivity (minor issue)

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#843]
# Module: 0?
#### Step: 01

Description of issue

Text says:

_In the Azure portal, select for and select the `CoreServicesVnet` virtual network._

Might be better phrased like so:

_In the Azure portal, select the `CoreServicesVnet` virtual network._

**Comment by staleycyn** [comment]
Another good one. All better. Thanks.
