### ISSUE TITLE
New Instructions - Lab 08 - Manage Virtual Machines (minor issue)

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#844]
# Module: 0?
#### Step: 01

Description of issue

Azure UI has changed slightly, text says:

_On the **az104-vm1** virtual machine, in the **Settings** blade, select **Size**._

However, this has moved a bit, and text should likely read:

_On the **az104-vm1** virtual machine, in the **Availability + scale** blade, select **Size**._

**Comment by staleycyn** [comment]
Better. Thanks.

**Comment by Lenin82** [comment]
Phj

пт, 23 февр. 2024 г., 02:36 staleycyn ***@***.***>:
