### ISSUE TITLE
New Instructions - Lab 10 - Implement Data Protection (minor issues)

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#845]
# Module: 0?
#### Step: 08 (and task 5/step 5)

Description of issue

**Task 2/Step 8:**

Azure UI has changed slightly - text says:

_Return to the Recovery Services vault blade, click the **Update** link under **Security Settings** label._

However, there are now 3 entries under 'Security Settings' that have the 'update' option present.  Likely text should read:

![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/49700217/45d9343f-a9d5-403e-b2dc-478a8bd8f280)

_Return to the Recovery Services vault blade, click the **Update** link under **Security Settings > Soft Delete and security settings** label._

**Task 5/Step 5:**

Azure UI has changed slightly - text says:

_In the **Operations** blade, select **Disaster recovery**._

Likely now should read:

_In the **Backup + Disaster recovery** blade, select **Disaster recovery**._

**Comment by staleycyn** [comment]
Ready. Thanks for your help.
