### ISSUE TITLE
Missing az104-02a-customroledefinition.json file interactive lab simulator (module 2 - create a custom RBAC role -Manage subscription and RBAC) 

### ISSUE THREAD

**Issue by shahrampc** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#847]
# Module: 02
#### Step: 01

Description of issue
I would like to download the az104-02a-customroledefinition.json file for (module 2 - create a custom RBAC role -Manage subscription and RBAC)  , but i can't find the json file, wonder if someone has the file?
Thank you,

**Comment by shahrampc** [comment]
![json](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/25259805/cbd1abf5-ca9b-48c3-a761-5d2167db7807)

**Comment by shahrampc** [comment]
I did write and upload the code and followed the instruction using interactive lab simulator , but i got **"New-AzRoleDefinition: File /home/shahram/az104-02a-customroledefinition does not exist"**
![error_az](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/25259805/b7e67786-8db7-4b0e-8b1c-99d963c5bf39)
![code](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/25259805/4077a4ba-95b8-4f25-83dd-cb2629dfe405)

**Comment by staleycyn** [comment]
This has been uploaded - https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/tree/master/Allfiles/Interactive%20Lab%20Simulation%20Files/02
