### ISSUE TITLE
[CloudSlice] unable to create a new custom RBAC role due to the limit

### ISSUE THREAD

**Issue by msftnutta** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#850]
# Module: 2
### Task: 3

![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/98095529/d8d02d98-cf90-4433-8e0c-8859663a7a9a)

**Comment by msftnutta** [comment]
a ticket has been lodged to Skillable

![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/98095529/6f0bb4da-82a7-4bfb-99a7-fdd1a0debc2b)

**Comment by msftnutta** [comment]
![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/98095529/d999e395-fd9e-4dd6-9ceb-99c245f862a5)

tested today and Skillalble has fixed this issue. 

Please close this, thank you.

**Comment by staleycyn** [comment]
This has been resolved.
