### ISSUE TITLE
Error in lab

### ISSUE THREAD

**Issue by TommyKobber** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#851]
# Module: 08
#### Step: 10

As we detached the disk in step 6, which is necessary to resize the disk, there will be no disks attached.

Repro steps:

11:  Click "Attach existing disks" and then choose the disk you created in step 4. Note: You may have to wait 5 minutes or longer before the disk is available in the dropdown box.
1.
1.

**Comment by staleycyn** [comment]
Corrected. Thanks.
