### ISSUE TITLE
Deprecated functionality in Lab 10

### ISSUE THREAD

**Issue by TommyKobber** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#852]
# Module: 10
#### Step: 09

The function "Archive to Storage Account" has been deprecated since March 31st on new rules according to [https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/migrate-to-azure-storage-lifecycle-policy?tabs=portal]

Repro steps:

Delete steps 1-11
1.
1.

**Comment by renaudwangler** [comment]
Hello.
I think you misunderstood the link you refer to : The storage ("archiving") of diagnostics settings is not deprecated : the "lifecycle policy" within the diagnostics settings is ;)
In my understanding there is nothing wrong in the way the lab steps are labeled : there is no more support for configuring the lifecycle in the diagnostic settings : we have to set it in the storage lifecycle policy instead.
Hope this helps (and sorry for my poor english level)

**Comment by TommyKobber** [comment]
Worked like a charm this morning.
