### ISSUE TITLE
Multiple lab noted issues

### ISSUE THREAD

**Issue by Nldtxgh** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#853]
Lab autos log in as Admin account, no need for student to do so, should tell them to open up Edge browser before pasting portal.
Mod 1 Step to get into First AAD tenant needs to tell students to use Switch option to move from LOD to the new tenant.
Mod 2 Add members to VM Contributor group there are two groups with either helpdesk or HelpDesk Group (the step has lower case helpdesk)
Mod 3 Step 5 change to disk_name on line 4 and 15 in template file
Using cloud shell URL instead of menu item by search area
Add note Step 8 if CTRL S doesn't work, can right click in Editor and select save/quit.
Step 9 go to end of New-AZRGBDeployment pasted code and Enter to Execute
Mod 4 Using the VS code to edit template, make sure to switch to trusted mode.
Right click selected code to see the "Change all Occurrences."
File Menu and Save
Deploy custom template import template file save and then parameters and save before Create (Missing parameters file import)
Mod 5 Add note: Task 5 if the IP is not there, wait a few and it should refresh and show both Public and private IPs
Mod 6 Task 1 Step 1 should be reworded to say make sure you completed the previous task to download files
might need to extend lab time with button Task 2 AZLB setup VM deployment completion takes a minute or two
Add backend 2 VMs missing the click Save to add step
Sets up application gateway as well (5-10 to finish creation-must wait)
Backend Health URL just the IP address not the (pip info)
Mod 8 Virtual Machines Task 1-3 is redundant with launching the portal and logging in and even setting the availability zones first since table has those options identified.
Like in Mod 11 It has the download then in Task 1 says if necessary…
might need to extend lab time with button The Edit Names popup acts funny with pasting the vm name, paste first from step then copy/paste in the popup and edit for
second.
Size is under Blade to left for Availability and Scaling not in center details, resize of VM takes 2-8 minutes. (screen below step shows the blade area)-refresh browser if looks
like it is hanging.
Step about detaching the disk and then resizing, going back to VM disks and seeing its new Standard SSD is confusing, detach disk won't be visible anymore, so need a step
to identify to reattach and check the new type.
Typo on the second Add rule to vmss1 scaling, should be decrease percent not (percentage) by Operation Action under drop down.
Task 5 paste into ISE and then copy and paste as plain text in the Cloudshell
delete get credential if comes back after vm creation.
Mod 10 Backup VMs After storage account creation on Step 6 the Diagnostic settings is under Properties at the top - Not clear the Diagnostic Setting is under the properties of
the Storage account, not under the Monitoring area of the tiles to the left
might need to extend lab time with button.
Mod 11 Monitoring
might need to extend lab time with button Some labs have RG already, others you have to create a new one like in the final Mod 11-Inconsistency
Wait to create until after the Action group and following steps or it will error because Missing step to get Alert Rule a name under the Details area-once created might have
to refresh browser to show in view.

**Comment by staleycyn** [comment]
Corrected - Deploy custom template import template file save and then parameters and save before Create (Missing parameters file import)
Corrected - Add backend 2 VMs missing the click Save to add step
Corrected - Step about detaching the disk and then resizing, going back to VM disks and seeing its new Standard SSD is confusing, detach disk won't be visible anymore, so need a step to identify to reattach and check the new type.

Reminder - This GitHub does not provide steps that are specific to a hosting environment. For example, there are no instructions in this GitHub to create a tenant or log into the hosted virtual machine. Likewise, any editor (not just VS) could be used. Those things are specific to Skillable's environment. And I think all of Skillable's labs have the option to extend the lab time.

Write back if there is something else. Thanks.
