### ISSUE TITLE
Wrong parameter on SA name for Lab 3 Task 3

### ISSUE THREAD

**Issue by lnezsierra** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#855]
# Module: 03
#### Step: 03

Description of issue
Name provided for SA is not unique
Repro steps:

1. Step number 3 of task 3 provides sacloudshell as the name for the creation of a new SA for Cloudshell. As the name is not unique, it fails for the students
Screenshot attached
<img width="1024" alt="Captura de pantalla 2024-03-11 155447" src="https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/158315751/0b8a0d9c-06c3-458e-bb0a-17e344f1ea56">

**Comment by lnezsierra** [comment]
The student tried sacloudshell2315 because I suggested it, but the instructions (on the right of the screenshot) said specifically "sacloudshell" and that is not gonna be unique

**Comment by lnezsierra** [comment]
Thanks Cindy! I understand where this is coming from but this is my view:
If we put "sacloudshell" as the text to be copied, every student is going to try that first and it won't ever be unique for any of them (no matter where they are doing the labs, the name must be globally unique). 
I suggest we just leave the "must be globally unique, between 3 and 24 characters in length and use numbers and lower-case letters only" as it is on the other labs of this same course

**Comment by staleycyn** [comment]
Fair enough. Made the correction. Thanks.

**Comment by lnezsierra** [comment]
[heart]         Laura Núñez Sierra reacted to your message:
________________________________
