### ISSUE TITLE
Wrong PowerShell script

### ISSUE THREAD

**Issue by bechynsky** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#856]
# Module: 08
#### Step: 03

Description of issue

There is wrong PowerShell script. Missing ` character on end of line starting -Script and passing string to -Credential parameter not calling function.

Correct script

```
 New-AzVm `
 -ResourceGroupName 'az104-rg8' `
 -Name 'myPSVM' `
 -Location 'East US' `
 -Image 'Win2019Datacenter' `
 -Zone '1' `
 -Size 'Standard_D2s_v3' `
 -Credential (Get-Credential) 
```

**Comment by staleycyn** [comment]
corrected.
