### ISSUE TITLE
Issue with Lab 10 Policy sub types: Enhanced and Standard

### ISSUE THREAD

**Issue by JamesFCroft** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#859]
# Module: 00
#### Step: 06

Description of issue
Step 06 says to set Retain instant recovery snapshot(s) for | **12** Days(s) - However the type set in step 4 is "Standard" where valid days are 1 to 5
Fix is to either set Step 4 to Enhanced or lower the value in Step 6 to a max of **5**. 

Repro steps:

1. Do Step 4
1. Do Step 5
1. Do Step 6

**Comment by staleycyn** [comment]
Corrected. Thanks.
