### ISSUE TITLE
lab 9c text errors

### ISSUE THREAD

**Issue by Franlusan** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#87]
![Capture](https://user-images.githubusercontent.com/50480392/84012718-4494e600-a978-11ea-944b-b17e0e07e000.JPG)
# Module: 9
#### Step: 4 and 7

Description of issue
Step 4 says click Next: Scale-create kubernets cluster 
Step 7 says click Next: Monitoring
Repro steps:
1.Step 4 should say click Next: Node pools
1.Step 7 should say click Next: Integration
1.

**Comment by polichtm** [comment]
What exactly are you referring to?
Here is the relevant text in the current instructions:
![image](https://user-images.githubusercontent.com/10284906/84019167-ec95b980-a94e-11ea-895b-e875dbdd9ed1.png)
rgds
Marcin

**Comment by Franlusan** [comment]
Maybe your text has been updated recently. I downloaded it a few weeks ago

[cid:image001.jpg@01D63D8E.72DB18A0]


Francisco Luque Santiago
http://www.franciscoluque.com<http://www.franciscoluque.com/>    http://www.tuaulavirtual.es<http://www.tuaulavirtual.es/>
MCSE, Trainer Windows, Security, Exchange, Hyper-V, SCCM, Office 365, Azure administrator
PeopleCert ITIL 4 Accredited Trainer, Traductor técnico inglés- francés-español
Skype: jf.luque


De: polichtm <notifications@github.com>
Enviado el: lunes, 8 de junio de 2020 12:12
Para: MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator <AZ-104-MicrosoftAzureAdministrator@noreply.github.com>
CC: Franlusan <jf.luque@outlook.com>; Author <author@noreply.github.com>
Asunto: Re: [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator] lab 9c text errors (#87)


What exactly are you referring to?
Here is the relevant text in the current instructions:
[image]<https://user-images.githubusercontent.com/10284906/84019167-ec95b980-a94e-11ea-895b-e875dbdd9ed1.png>
rgds
Marcin

**Comment by polichtm** [comment]
Pls make sure to check the _current_ version of the GitHub content
rgds
Marcin
