### ISSUE TITLE
Mod 7 Lab 8 Service Endpoint functionality removed from Subnet blade

### ISSUE THREAD

**Issue by thhatty** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#885]
# Module: 7
#### Step: 5

Description of issue
Step 5 asks user to select the subnet blade and go into the subnet itself to enable the service endpoint. This feature has been removed from the subnet blade however, and must be done through the dedicated service endpoint blade found below the subnet settings.

Repro steps:

1. (following current instructions) Under Settings category, click subnets.
2. In the service endpoint section, choose microsoft.storage in the services dropdown. hit save. 
3. These steps are not currently available due to a UI change. 

Steps should be changed to something like:
1.Under the settings category, click Service endpoints
2.Click +add on the top bar
3. Select Microsoft.Storage in the services dropdown
4. Select default subnet in the subnets dropdown
5. click Add

**Comment by staleycyn** [comment]
Corrected. Thanks for reporting.
