### ISSUE TITLE
Issues with AZ-104 Labs 

### ISSUE THREAD

**Issue by teriaavibes** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#886]
# Module: 01
#### Step: NA

Description of issue 

Cleanup is supposed to be clean up

Repro steps:

Look at the lab file and dictionary https://dictionary.cambridge.org/dictionary/english/clean-up

**Comment by staleycyn** [comment]
Is there a problem with the lab? If so, please provide detailed steps on what needs to be corrected.
