### ISSUE TITLE
Course has been updated but the labs have not

### ISSUE THREAD

**Issue by brentd09** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#898]
Can you help us understand why the labs, especially the lab order, have not been updated, now that the new AZ-104 course has been created? Storage and Networking Learning Paths are in reverse order from the original AZ-104 but the labs are not reflecting that. I also see that the learning modules in each learning path are not always aligned with the lab order of the original AZ-104 labs.

Are we to teach all of the theory for one or more learning paths (and all of the learning modules for each learning path) before we get the students to do their labs? This seems the only way around this issue at present.  

My Preference would be to have shorter learning sessions with aligned targeted labs helping the students internalise the information better. But as it currently stands we now have old labs that are out of sync with the new learning modules, and this makes small targeted learning sessions very difficult to do without creating a lot of confusion.

To solve the Storage and Networking order issue, I intend to teach the learning paths so that the lab order makes sense, this means I will teach Networking before Storage to align with the current lab order.

**Comment by brentd09** [comment]
As I have looked into the course structure I have now seen many more examples of how the learning paths and the labs do not align regarding content and order.
<br>
To give just one example:
<br> 
The "Manage Identity and Governance" Learning path has 8 units:
- [Understand Microsoft Entra ID](https://learn.microsoft.com/en-gb/training/modules/understand-azure-active-directory/)
- [Configure user and group accounts](https://learn.microsoft.com/en-gb/training/modules/configure-user-group-accounts/)
- [Configure subscriptions](https://learn.microsoft.com/en-gb/training/modules/configure-subscriptions/)
- [Configure Azure Policy](https://learn.microsoft.com/en-gb/training/modules/configure-azure-policy/)
- [Configure role-based access control](https://learn.microsoft.com/en-gb/training/modules/configure-role-based-access-control/)
- [Create Azure users and groups in Microsoft Entra ID](https://learn.microsoft.com/en-gb/training/modules/create-users-and-groups-in-azure-active-directory/)
- [Secure your Azure resources with Azure role-based access control (Azure RBAC)](https://learn.microsoft.com/en-gb/training/modules/secure-azure-resources-with-rbac/)
- [Allow users to reset their password with Microsoft Entra self-service password reset](https://learn.microsoft.com/en-gb/training/modules/allow-users-reset-their-password/)


However, the Labs for this learning path are in this order:
- [LAB_01-Manage_Entra_ID_Identities.md](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/blob/master/Instructions/Labs/LAB_01-Manage_Entra_ID_Identities.md)
- [LAB_02a_Manage_Subscriptions_and_RBAC_Entra.md](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/blob/master/Instructions/Labs/LAB_02a_Manage_Subscriptions_and_RBAC_Entra.md)
- [LAB_02b-Manage_Governance_via_Azure_Policy.md](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/blob/master/Instructions/Labs/LAB_02b-Manage_Governance_via_Azure_Policy.md)
- [LAB_03b-Manage_Azure_Resources_by_Using_ARM_Templates.md](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/blob/master/Instructions/Labs/LAB_03b-Manage_Azure_Resources_by_Using_ARM_Templates.md)

**Comment by staleycyn** [comment]
All the ILT course pages were recently updated to include only the Learning Paths. The [AZ-104](https://learn.microsoft.com/en-us/training/courses/az-104t00) course page does have the LPs out of order. I have made the change, but it will take a few days to publish to the frontend. 

Does this fix the problem? If not, write back. Good catch.

**Comment by staleycyn** [comment]
Looks like this has been corrected. Adding that you can create a customized [Collection](https://learn.microsoft.com/teamblog/announcing-learn-collections) of Learn modules to distribute to your students. And there is a new [Plans](https://learn.microsoft.com/training/support/plans) feature which is similar to Collections, but you can add milestones. Happy learning.
