### ISSUE TITLE
Welcome to Azure splash screen on Portal

### ISSUE THREAD

**Issue by melvinporter** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#899]
# Module: All
## Lab/Demo :All

Every time the **Azure Portal** is opened for the first time a "**Welcome to Azure**" splash screen appears.
Instructions should include a note to "**Cancel**" the welcome screen.
![welcome](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/49310608/9afb3ebf-31cf-4ff8-b049-acf03c6a5076)

**Comment by staleycyn** [comment]
@melvinporter - You don't think Admin students can figure out to select the Cancel button? What if they want to go through the Get Started pages?

**Comment by melvinporter** [comment]
I agree with you 100%, however - some students are entirely new to the Azure portal and others may be very pedantic about following steps down to the letter. I teach it often enough to have a reason for making this request. .... not to mention consistency of instructions.

**Comment by brentd09** [comment]
I agree with Melvin, the steps should be able to be followed by everyone. In an environment where you assume how much each student should know, who is to say, how much we can assume, This is an entry-level course for Azure and therefore this is what we should be assuming of the student.

**Comment by staleycyn** [comment]
Added a step.
