### ISSUE TITLE
Move Note up in instructions in Module 8 Lab

### ISSUE THREAD

**Issue by markturpinMSFT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#90]
# Module: 08
#### Step: 16

Description of issue

Please move up the following note to after step 16/before step 17 in task 2.  This will be less confusing for students.

"Note: Disregard the message stating The resource group is in a location that is not supported by one or more resources in the template. Please choose a different resource group. This is expected and can be ignored in this case."

**Comment by polichtm** [comment]
updated
