### ISSUE TITLE
 Lab: 01 - Step missing - need to go back to Entra ID tenant before creating new user.

### ISSUE THREAD

**Issue by melvinporter** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#900]
# Module: 01
#### Step: 04

Step missing - need to go back to Entra ID tenant

4. Return to the **Entra ID** page and select **Licenses**. From here you can purchase a license, manage the licenses you have, and assign licenses to users and groups. Select Licensed features to see what is available. 
**Add the following: Return the the Entra ID Tenant blade by pressing back in the browser or selecting the option in the breadcrumb menu.**

**Comment by staleycyn** [comment]
@melvinporter - You think Admin students should be instructed on how to "return to the Entra ID page"?

**Comment by melvinporter** [comment]
@staleycyn - I agree with you 100%, however - some students are entirely new to the Azure portal and others may be very pedantic about following steps down to the letter. I teach it often enough to have a reason for making this request ... not to mention consistency of instructions.

**Comment by brentd09** [comment]
I agree, the steps should be able to be followed by everyone. In an environment where you assume how much each student should know, who is to say, how much we can assume, This is an entry-level course for Azure and therefore this is what we should be assuming of the student.

**Comment by staleycyn** [comment]
Made a change.
