### ISSUE TITLE
Module 1, Task 2, Step 5 - Clarify which user is added to the group 

### ISSUE THREAD

**Issue by melvinporter** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#901]
# Module: 01
#### Step: 5

Clarify which user is added to the group 

5. In the **Add owners** page, search for and select yourself **(the user currently logged on to the portal, not the invited user)** as the owner. Notice you can have more than one owner.

**Comment by staleycyn** [comment]
Clarified.
