### ISSUE TITLE
Lab 03 - Cloud Shell upload of files

### ISSUE THREAD

**Issue by melvinporter** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#902]
# Module: 03
#### Step: 5

Cloud Shell upload step and edit - clarification

5. Select **_Manage Files_** and then select **_Upload_** to upload the template and parameters file from the downloads directory. You will need to upload each file separately.
![cloudshell](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/49310608/9d92ef55-5cc0-4185-8b45-c81a24d7e8db)

6.

7. Select the **Editor** icon, the **Switch the Classic Cloud Shell** message appears, click **Confirm** to enter the **Classic Cloud Shell** view. (_remove reference to curly brackets here - see diagram above_). In the **Classic Cloud Shell view** select the **Editor** (curly brackets) icon and navigate to the template JSON file on the left in the navigation pane.
8. In the template JSON file change the disk name to **az104-disk3**. Use **Ctrl +S** to save your changes.

**Task 4: Step 4  - has a similar issue to step 8:**
4. In the template JSON file change the disk name to **az104-disk4**. Use **Ctrl +S** to save your changes.

**Comment by WigF1** [comment]
One note with Step 5, you no longer need to add each file separately! After a decade, you can finally select multiple files and it works!

**Comment by staleycyn** [comment]
Made a change.
