### ISSUE TITLE
Lab 04 - Replace prepopulated IPv4 address space and remove default subnet

### ISSUE THREAD

**Issue by melvinporter** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#903]
# Module: 04
#### Step: 5 & 6

**Step 5** Replace the prepopulated IPv4 address space with **10.20.0.0/16** (separate the entries)

**Step 6** Delete the **default** subnet - either before or after creating the other subnets.

**Comment by staleycyn** [comment]
Updated.
