### ISSUE TITLE
Module 4 Peering - new interface

### ISSUE THREAD

**Issue by melvinporter** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#904]
# Module: 04
#### Step: All

Adjust the order of the parameters to be entered - entire lab's accuracy need to be reviewed since the interface has changed.
Remote network is now listed first and the local network listed second.

![peering 1](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/49310608/14223db6-c935-4838-a7fb-fad340f4b8fa)
![peering 2](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/49310608/67cf586a-8d18-48c0-a30d-d02ad7766d1c)

**Comment by staleycyn** [comment]
Made a change.
