### ISSUE TITLE
Lab 08 - Manage Virtual Machines - no scaling tab when creating Load Balancer

### ISSUE THREAD

**Issue by melvinporter** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#906]
# Module: 8
#### Step: 14

Instructions suggest there is a **Scaling** tab - there is no **Scaling** tab. **Remove the contents of Step 14.**

![scaling](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/assets/49310608/1c806983-365d-4608-bac2-8bd691a7a3a0)
14. On the **Scaling** tab, specify the following settings (leave others with their default values) and click **Next** : **Management** >:
**Setting - Value**
Initial instance count - 2
Scaling policy - Manual

**Comment by staleycyn** [comment]
Updated.
