### ISSUE TITLE
Lab 09a - Implement Web Apps - interface correction #2

### ISSUE THREAD

**Issue by melvinporter** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#909]
# Module: 9
#### Step: 9

Clarification of interface

9. On the **Test plan** tab, click **Add request**. In the URL field of the **Add request** panel, paste in your **Default domain** URL. Ensure this is properly formatted and begins with **https://**.

**Comment by staleycyn** [comment]
Updated.
