### ISSUE TITLE
Lab 09a - Implement Web Apps (terminology)

### ISSUE THREAD

**Issue by Mafade** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#912]
# Module: Implement Web Apps
#### Step:04

Description of issue
A learner brought to my attention the use of the name "master" in the instructions of this lab ( Task 3, Step 4) for the branch field.  It's very important to consider the terminology used in our instructions and  remove language that may be considered exclusionary or offensive.
 
Can we please change the name used to be (main) just like the field's name. 
Repro steps:

**Comment by staleycyn** [comment]
@Mafade - This has been corrected. Thank you for reporting.
