### ISSUE TITLE
AZ-104 Lab 09a - Implement Web Apps Bugs

### ISSUE THREAD

**Issue by naonao71** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#922]
# Module: 09
#### Step: 04

Description of issue
The Pricing Plan is set to Premium V3 P0V3 by default. 
If you deploy it as is, it will violate Azure Policy and a deployment error will occur.

Repro steps:
You need to change the Pricing Plan to **Premium V3 P1V3**.

**Comment by staleycyn** [comment]
I was able to deploy a web app for my own subscription without any policy errors. Are you using a lab hosting environment in the classroom? If so, which one? Lab hosters may have policy restrictions and will change the task for their environment. For example, Skillable uses P1V3. Please write back with more details. 

![image](https://github.com/user-attachments/assets/9148ef1f-af37-4e15-8a2f-fd2da5097b7b)

**Comment by naonao71** [comment]
Thank you for your reply. The instructions provided in Japanese on LODS are P0V3. I had thought that the procedures published on GitHub would be used as the LODS procedures, but it seems that is not the case. Therefore, the objective is to change the instructions provided in Japanese on LODS to P1V3. Without doing this, the lab cannot proceed due to a policy error. Thank you for your understanding.



________________________________
差出人: staleycyn ***@***.***>
送信日時: 2024年8月29日 22:31
宛先: MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator ***@***.***>
CC: Naoki Abe ***@***.***>; Author ***@***.***>
件名: Re: [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator] AZ-104 Lab 09a - Implement Web Apps Bugs (Issue #922)


I was able to deploy a web app for my own subscription without any policy errors. Are you using a lab hosting environment in the classroom? If so, which one? Lab hosters may have policy restrictions and will change the task for their environment. For example, Skillable uses P1V3. Please write back with more details.

image.png (view on web)<https://github.com/user-attachments/assets/9148ef1f-af37-4e15-8a2f-fd2da5097b7b>

**Comment by staleycyn** [comment]
This needs to be addressed by the Skillable. I have opened a support ticket with them. Closing this issue for now.
