### ISSUE TITLE
Lab 10 - Web Apps - Cannot use "East US" for App Service Plan, instead use "East US 2"

### ISSUE THREAD

**Issue by MSFT-MarcoEs** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#925]
# Lab: 10 - Web Apps (was 9a)
#### Step: 04

Description of issue: 
- If we select the proposed region, it fails due to region constraints:
![image](https://github.com/user-attachments/assets/6aad1c95-e5b6-47a2-b14d-a8e2383d93d9)

Instead, use "East US 2":
![image](https://github.com/user-attachments/assets/8b6d6893-23d2-44ad-922a-e3ed55dacde9)
![image](https://github.com/user-attachments/assets/bedd8bb6-7821-4769-ac89-f94109feb425)

**Comment by staleycyn** [comment]
Added a note to change the region if the deployment fails.
