### ISSUE TITLE
Lab 7 - Traffic Management (was Lab 6) - Typo: AvZone should read 1 instead of None

### ISSUE THREAD

**Issue by MSFT-MarcoEs** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#926]
# Lab: 07
### Step: 08

Description of issues: 
1. In the step 7 it is required to select Zone 1, so step 8 should read the same:
![image](https://github.com/user-attachments/assets/72224bde-c4f3-446b-a9d3-660272a00c6a)

1. The image between Step 7 and 8 is outdated, it shows that you shouldn't select a zone, which cannot be done now.
![image](https://github.com/user-attachments/assets/a2ff8f68-c8ba-458d-b13b-f4623bcfa82c)

**Comment by staleycyn** [comment]
Deleted the graphic.

**Comment by staleycyn** [comment]
@MSFT-MarcoEs - all better now.
