### ISSUE TITLE
Same issue with LAB01

### ISSUE THREAD

**Issue by TechGuyVincent** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#93]
# Module: 00
#### Step: 07

Description of issue
It doesn't refresh the management group automatically, but users have to constantly refresh and wait for a few minutes after the license has been applied for it to work. Usually works if they sign in/out. 

Suggestion: Maybe redo the LAB01 to not having to use the P1/2 licenses.

**Comment by polichtm** [comment]
appreciate the suggestion - but, in my view, it is important to be familiar with this functionality - even if it takes a few minutes to wait for it to take effect. Updated to account for the wait time.
rgds
Marcin

**Comment by prince006** [comment]
Not closed yet..
