### ISSUE TITLE
Lab 09b - Implement ACI has a new step in creation wizard

### ISSUE THREAD

**Issue by MSFT-MarcoEs** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#937]
#### Step: 05

Description of issue: There is a new Monitoring tab with a configuration that needs to be unchecked and documented in the lab.

![image](https://github.com/user-attachments/assets/497cf3e8-3364-43cb-8bbf-94db39c3d26f)

**Comment by staleycyn** [comment]
Added a step. Thanks.
