### ISSUE TITLE
The Size (Standard D2s v3) Is No Longer Available In The East US Region 

### ISSUE THREAD

**Issue by KohlrabiMan** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#938]
# Module: 00
#### Step: 00

Description of issue: The recommended size in the lab is no longer available for the East US Region. 

Repro steps:

1.Follow the Lab steps to the Basics tab of the Virtual Machine creator
2. Set the Region, OS, and Size as detailed
3. The size will not be available in the region

**Comment by staleycyn** [comment]
VM availability depends on your Azure subscription.  Suggest you try another region or another VM size.
