### ISSUE TITLE
Why the target region is third region "South Central US"?

### ISSUE THREAD

**Issue by ngyewban** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#943]
https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/blob/8034f3f58f9521baf8aa89d46ed43e06f33baac3/Instructions/Labs/LAB_10-Implement_Data_Protection.md?plain=1#L244

**Comment by staleycyn** [comment]
In the "Target region" drop-down you can select any available region. Read more https://learn.microsoft.com/en-us/azure/site-recovery/azure-to-azure-quickstart.
