### ISSUE TITLE
Lab 08/Task 3/Step 2 | VMSS creation options have changed

### ISSUE THREAD

**Issue by Simfukwe** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#944]
# Module: Administer Virtual Machines
#### Step: 2

Description of issue
More options available during the "Virtual Machine Scale Sets" creation process (see attached screenshot). 
![image](https://github.com/user-attachments/assets/f386e612-d905-4781-9461-b9a1d8211c67)

Edit: Mainly the "Scaling" options that are shown in my screenshot. The Lab instructions don't say which to choose in Task 3/Step 2

**Comment by staleycyn** [comment]
Does it matter what you choose? We change it in the next task. What specifically do you want added?

**Comment by Simfukwe** [comment]
I guess not. Just didn't want people to get confused by the interface change and the original screenshot. Thanks!

**Comment by staleycyn** [comment]
Added an entry:

    | Scaling options | **Review and take the defaults**. We will change this in the next task. |
