### ISSUE TITLE
Storagespaces broken

### ISSUE THREAD

**Issue by TechGuyVincent** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#95]
# Module: 00
#### Step: 09

Description of issue: 

Script runs, nothing happens. Machine freezes. 

Repro steps:

The machine does not mount the VM disk drives properly, fails to create the storagespaces and freezes. Run the script several times, same issues. 

1.
1.
1.

**Comment by polichtm** [comment]
Pls sign in to the virtual machine, run the same script from the PowerShell prompt, and provide the outcome
rgds
Marcin

**Comment by TechGuyVincent** [comment]
Hi Marcin! 

It just freezes - no outcome whatsoever. Cloudshell times out before it completes. 

/V

**Comment by polichtm** [comment]
Hi Vincent,
unfortunately I cannot reproduce this. 
Pls try running each command separately from RunCommand and let us know about the outcome
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
