### ISSUE TITLE
Update needed (Instructions) 

### ISSUE THREAD

**Issue by TechGuyVincent** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#96]
# Module: 00
#### Step: 00

Description of issue

Last part of the cleanup - the button layout has changed in the portal. 

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
Pls provide the exercise, task, and step number you're referring to
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
