### ISSUE TITLE
lab 09a step 6 - password complexity requirements

### ISSUE THREAD

**Issue by grundlichkeit** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#97]
# Module: 09
#### Step: 07

Description of issue
no single combination of user credentials with complex requirements is accepted, always getting 
The specified password does not meet the minimum requirements. The password should be at least eight characters long and must contain capital letters, lowercase letters, numbers, and symbols.
eventhough all conditions are applied by using a strong password generator with 50 character length including all the specified conditions

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
Pls provide the repro steps and the list of passwords that you tried
rgds
Marcin

**Comment by grundlichkeit** [comment]
from deployment center, select local git
select app service build service
click deployment credentials & user credentials
username: az10409rg__test
passw: AaZzEe12345/*-  or MY$Wp9s3WUqtUPsx=rFL

**Comment by polichtm** [comment]
The user name has to be globally unique. Have you tried a different one?
rgds
Marcin

**Comment by grundlichkeit** [comment]
yes, me and a student tried different users: student, adminapp, appsvcs and az10409rg__test

**Comment by staleycyn** [comment]
I am also not able to reproduce this error. Ensure the username is unique. The usernames you have provided are not globally unique and you should be seeing a popup with that message. Please understand that this repository is for distributing classroom files to Microsoft Certified Trainers. We are not staffed to offer help with the steps. Thank you for your understanding.

**Comment by polichtm** [comment]
updated
