### ISSUE TITLE
Clarify instructions

### ISSUE THREAD

**Issue by chris-utter** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#98]
# Module: 10
#### Step: 06

Description of issue
Step indicates that "This will automatically transition to the Items to backup step and open the Select virtual machines blade."  This is not the current UI. Rather it returns the user to the Backup wizard page, and the user must click the Add button to identify virtual machines to be backed up
Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
updated
