### ISSUE TITLE
The template to export should be from VM0 not VM1

### ISSUE THREAD

**Issue by Franlusan** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#99]
# Module: 08
#### Step: 13

Description of issue
13. In the Azure portal, search for and select Virtual machines and, on the Virtual machines blade, click az104-08-vm1.
14. On the az104-08-vm1 blade, in the Settings section, click Export template.
Repro steps:

1.The template to export is from VM0 not VM1 BECAUSE THE DATADISKS WERE CREATED IN VM0 
1.
1.

**Comment by polichtm** [comment]
Could you clarify what "datadisks" are you referring to? Pls provide the exercise, task, and step reference
rgds
Marcin

**Comment by Franlusan** [comment]
AZ-104, lab 8, Exercise 1, task 2, step 6 to 13
THE EXTENSIONS ARE ADDED TO VM0 (STEP 8) SO, TO ADD THE EXTENSIONS TO VM1, THE TEMPLATE TO EXPORT IS FROM VM0 TO VM1 (STEP 14)
6. On the Upload blob blade, click the folder icon, in the Open dialog box, navigate to the \Allfiles\Labs\08 folder, select
az104-08-install_IIS.ps1, click Open, and back on the Upload blob blade, click Upload.
7. In the Azure portal, search for and select Virtual machines and, on the Virtual machines blade, click az104-08-vm0.
8. On the az104-08-vm0 virtual machine blade, in the Settings section, click **Extensions, and the click + Add**.
9. On the New resource blade, click Custom Script Extension and then click Create.
10. From the Install extension blade, click Browse.
11. On the Storage accounts blade, click the name of the storage account into which you uploaded the az104-08-install_IIS.ps1
script, on the Containers blade, click scripts, on the scripts blade, click az104-08-install_IIS.ps1, and then click Select.
12. Back on the Install extension blade, click OK.
13. In the Azure portal, search for and select Virtual machines and, on the Virtual machines blade, click az104-08-vm1.
14. On the az104-08-vm1 blade, in the Settings section, click Export template.
15. On the az104-08-vm1 - Export template blade, click Deploy.

**Comment by polichtm** [comment]
Actually, that's not the case. The extension is added to the template in step 17:
On the Edit template blade, in the section displaying the content of the template, insert the following code starting with line 20 (directly underneath the "resources": [ line):
     {
         "type": "Microsoft.Compute/virtualMachines/extensions",
         "name": "az104-08-vm1/customScriptExtension",
         "apiVersion": "2018-06-01",
         "location": "[resourceGroup().location]",
         "dependsOn": [
             "az104-08-vm1"
         ],
         "properties": {
             "publisher": "Microsoft.Compute",
             "type": "CustomScriptExtension",
             "typeHandlerVersion": "1.7",
             "autoUpgradeMinorVersion": true,
             "settings": {
                 "commandToExecute": "powershell.exe Install-WindowsFeature -name Web-Server -IncludeManagementTools && powershell.exe remove-item 'C:\\inetpub\\wwwroot\\iisstart.htm' && powershell.exe Add-Content -Path 'C:\\inetpub\\wwwroot\\iisstart.htm' -Value $('Hello World from ' + $env:computername)"
           }
         }
     },   
Note: This section of the template defines the same Azure virtual machine custom script extension that you deployed earlier to the first virtual machine via Azure PowerShell.

rgds
Marcin
